# Generated by Django 6.1 on 2026-08-17 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelers', '0003_alter_traveler_registration_status_travelerstatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryReagent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكواشف')),
                ('type', models.CharField(max_length=100, verbose_name='النوع')),
                ('lot_number', models.CharField(max_length=50, verbose_name='رقم اللوت')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('quantity', models.FloatField(default=0, verbose_name='الكمية')),
                ('unit', models.CharField(default='ml', max_length=20, verbose_name='الوحدة')),
                ('minimum_stock', models.FloatField(default=100, verbose_name='الكمية الدنيا')),
                ('status', models.CharField(choices=[('AVAILABLE', 'متوفر'), ('LOW_STOCK', ' منخفضة'), ('EXPIRED', 'منتهي'), ('MAINTENANCE', 'صيانة')], default='AVAILABLE', max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('assigned_test', models.CharField(blank=True, max_length=30, verbose_name='الاختبار المخصص')),
            ],
            options={
                'verbose_name': 'كواشف',
                'verbose_name_plural': 'الكواشف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChemistryEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('type', models.CharField(max_length=100, verbose_name='نوع الجهاز')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='المصنّع')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='الموديل')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='رقم السلسلة')),
                ('status', models.CharField(choices=[('AVAILABLE', 'متاح'), ('IN_USE', 'في الاستخدام'), ('MAINTENANCE', 'صيانة'), ('OUT_OF_SERVICE', 'منهك الخدمة')], default='AVAILABLE', max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('last_calibration', models.DateField(blank=True, null=True, verbose_name='آخر معايرة')),
                ('next_calibration', models.DateField(blank=True, null=True, verbose_name='المعايرة القادمة')),
                ('calibration_status', models.CharField(blank=True, max_length=20, verbose_name='حالة المعايرة')),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL, verbose_name='المحلل المنسوب')),
            ],
            options={
                'verbose_name': 'جهاز مخبري',
                'verbose_name_plural': 'الأجهزة المخبرية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChemistryAnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(max_length=30, verbose_name='نوع الاختبار')),
                ('reagent_used', models.CharField(blank=True, max_length=100, verbose_name='الكواشف المستخدمة')),
                ('result_value', models.FloatField(blank=True, null=True, verbose_name='قيمة النتيجة')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('limit_value', models.FloatField(blank=True, null=True, verbose_name='قيمة الحد')),
                ('compliance', models.CharField(blank=True, choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], max_length=20, verbose_name='الامتثال')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('status', models.CharField(default='IN_PROGRESS', max_length=20, verbose_name='الحالة')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المحلل')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to='travelers.traveler', verbose_name='المسافر')),
                ('equipment_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to='chemistry.chemistryequipment', verbose_name='الجهاز المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة تحليل كيميائي',
                'verbose_name_plural': 'جلسات التحليل الكيميائي',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChemistryTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=200, verbose_name='المنتج')),
                ('test_type', models.CharField(choices=[('MOISTURE', 'رطوبة'), ('FAT', 'دهون'), ('PROTEIN', 'بروتين'), ('ASH', 'رماد'), ('AFLATOXIN', 'أفلاتوكسين'), ('PESTICIDE', 'بesticides'), ('HEAVY_METAL', 'معادن ثقيلة'), ('MICROBIOLOGICAL', 'حيوية')], max_length=30, verbose_name='نوع الاختبار')),
                ('priority', models.CharField(choices=[('NORMAL', 'طبيعي'), ('URGENT', 'عاجل'), ('CRITICAL', 'حرج')], default='NORMAL', max_length=20, verbose_name='الأولوية')),
                ('sla_unit', models.CharField(choices=[('HOURS', 'ساعات'), ('DAYS', 'أيام')], default='DAYS', max_length=10, verbose_name='وحدة SLA')),
                ('sla_value', models.PositiveIntegerField(default=2, verbose_name='قيمة SLA')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_ANALYSIS', 'قيد التحليل'), ('RESULT_ENTERED', 'دخلت النتيجة'), ('SUBMITTED', 'مرسلة للمراجعة'), ('RETURNED', 'مرتجعة'), ('APPROVED', 'معتمدة')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستلام')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('specification_version', models.CharField(blank=True, max_length=20, verbose_name='نسخة المواصفة')),
                ('specification_limit', models.FloatField(blank=True, null=True, verbose_name='الحد الأقصى للمواصفة')),
                ('result_value', models.FloatField(blank=True, null=True, verbose_name='قيمة النتيجة')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('compliance_status', models.CharField(blank=True, choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('PENDING', 'في الانتظار')], max_length=20, verbose_name='حالة الامتثال')),
                ('analyst_comment', models.TextField(blank=True, verbose_name='تعليق المحلل')),
                ('returned_reason', models.TextField(blank=True, verbose_name='سبب الإرجاع')),
                ('qc_required', models.BooleanField(default=True, verbose_name='يحتاج QC')),
                ('qc_passed', models.BooleanField(blank=True, null=True, verbose_name='Passed QC')),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chemistry_tests', to=settings.AUTH_USER_MODEL, verbose_name='المحلل المنسوب')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_tests', to='travelers.traveler', verbose_name='المسافر')),
            ],
            options={
                'verbose_name': 'اختبار كيميائي',
                'verbose_name_plural': 'الاختبارات الكيميائية',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(max_length=30, verbose_name='نوع الاختبار')),
                ('control_sample', models.CharField(max_length=50, verbose_name='عينة التحكم')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='نتيجة التحكم')),
                ('expected_range', models.CharField(blank=True, max_length=100, verbose_name='النطاق المتوقع')),
                ('status', models.CharField(choices=[('PENDING', 'في انتظار'), ('PASSED', 'ممر'), ('FAILED', 'فشل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التنفيذ')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_qc', to=settings.AUTH_USER_MODEL, verbose_name='نفذ')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_records', to='travelers.traveler', verbose_name='العينة')),
            ],
            options={
                'verbose_name': 'سجل QC',
                'verbose_name_plural': 'سجلات QC',
                'ordering': ['-performed_at'],
            },
        ),
    ]
