# Generated by Django 5.0.14 on 2026-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistrytest',
            name='test_type',
            field=models.CharField(choices=[('MOISTURE', 'رطوبة'), ('FAT', 'دهون'), ('PROTEIN', 'بروتين'), ('ASH', 'رماد'), ('AFLATOXIN', 'أفلاتوكسين'), ('PESTICIDE', 'مبيدات'), ('HEAVY_METAL', 'معادن ثقيلة'), ('MICROBIOLOGICAL', 'حيوية')], max_length=30, verbose_name='نوع الاختبار'),
        ),
    ]
