# Generated by Django 5.0.14 on 2026-07-31 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_registration', models.CharField(max_length=20, verbose_name='تسجيل الطائرة')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التفتيش')),
                ('cleanliness_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='النظافة')),
                ('water_quality_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='جودة المياه')),
                ('toilets_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='المراحيض')),
                ('medical_waste_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='النفايات الطبية')),
                ('pest_control_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='مكافحة الآفات')),
                ('rodent_control_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='مكافحة القوارض')),
                ('food_safety_status', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='COMPLIANT', max_length=20, verbose_name='سلامة الغذاء')),
                ('findings', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('overall_status', models.CharField(choices=[('PASSED', 'نجح'), ('FAILED', 'فشل'), ('CONDITIONAL', 'مشروط')], default='PASSED', max_length=20, verbose_name='الحالة العامة')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='صدرت الشهادة')),
            ],
            options={
                'verbose_name': 'تفتيش طائرة',
                'verbose_name_plural': 'تفتيش الطائرات',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='AirportScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening_type', models.CharField(choices=[('ARRIVAL', 'وصول'), ('DEPARTURE', 'مغادرة'), ('TRANSIT', 'عبور'), ('CREW', 'طاقم')], max_length=20, verbose_name='النوع')),
                ('body_temperature', models.FloatField(blank=True, null=True, verbose_name='درجة الحرارة')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='تشبع الأكسجين')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='الأعراض')),
                ('risk_level', models.CharField(choices=[('GREEN', 'أخضر'), ('YELLOW', 'أصفر'), ('RED', 'أحمر')], default='GREEN', max_length=10, verbose_name='مستوى الخطر')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('CLEARED', 'مؤهل'), ('QUARANTINED', 'محجور'), ('REFERRED', 'مُحال')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('screened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفحص')),
            ],
            options={
                'verbose_name': 'فحص مطار',
                'verbose_name_plural': 'فحوصات المطارات',
                'ordering': ['-screened_at'],
            },
        ),
        migrations.CreateModel(
            name='AirportTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal_code', models.CharField(max_length=20, verbose_name='رمز الصالة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعة')),
                ('location_geo', models.JSONField(blank=True, default=dict, verbose_name='الموقع الجغرافي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'صالة مطار',
                'verbose_name_plural': 'صالات المطارات',
                'ordering': ['terminal_code'],
            },
        ),
        migrations.CreateModel(
            name='CrewHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_status', models.CharField(choices=[('FIT', 'لائق'), ('UNFIT', 'غير لائق'), ('UNDER_OBSERVATION', 'قيد المراقبة')], default='FIT', max_length=20, verbose_name='الحالة الصحية')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='درجة الحرارة')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='الأعراض')),
                ('medical_clearance_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التصريح')),
                ('next_clearance_date', models.DateField(blank=True, null=True, verbose_name='التصريح القادم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سجل صحة طاقم',
                'verbose_name_plural': 'سجلات صحة الأطقم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_code', models.CharField(max_length=20, verbose_name='رمز النقطة')),
                ('point_type', models.CharField(choices=[('ARRIVAL', 'وصول'), ('DEPARTURE', 'مغادرة'), ('TRANSIT', 'عبور'), ('CREW', 'طاقم')], max_length=20, verbose_name='النوع')),
                ('location_geo', models.JSONField(blank=True, default=dict, verbose_name='الموقع الجغرافي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نقطة فحص',
                'verbose_name_plural': 'نقاط الفحص',
                'ordering': ['point_code'],
            },
        ),
    ]
