# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport_health', '0001_initial'),
        ('carriers', '0001_initial'),
        ('travelers', '0002_country_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftinspection',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='carriers.flight', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='aircraftinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش'),
        ),
        migrations.AddField(
            model_name='airportscreening',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_screenings', to='carriers.flight', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='airportscreening',
            name='screened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airport_screenings', to=settings.AUTH_USER_MODEL, verbose_name='المُفحص'),
        ),
        migrations.AddField(
            model_name='airportscreening',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_screenings', to='travelers.traveler', verbose_name='المسافر'),
        ),
    ]
