# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport_health', '0002_initial'),
        ('carriers', '0001_initial'),
        ('ports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airportterminal',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='ports.port', verbose_name='المنفذ'),
        ),
        migrations.AddField(
            model_name='crewhealthrecord',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_health_records', to=settings.AUTH_USER_MODEL, verbose_name='طاقم'),
        ),
        migrations.AddField(
            model_name='crewhealthrecord',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_records', to='carriers.flight', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='screeningpoint',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_points', to='airport_health.airportterminal', verbose_name='الصالة'),
        ),
        migrations.AddField(
            model_name='airportscreening',
            name='screening_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='airport_health.screeningpoint', verbose_name='نقطة الفحص'),
        ),
        migrations.AlterUniqueTogether(
            name='airportterminal',
            unique_together={('port', 'terminal_code')},
        ),
        migrations.AlterUniqueTogether(
            name='screeningpoint',
            unique_together={('terminal', 'point_code')},
        ),
    ]
