# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('SCREENINGS', 'تقرير الفحوصات'), ('EPIDEMIC', 'تقرير وبائي'), ('PORT_PERFORMANCE', 'أداء المنافذ'), ('FOOD', 'الحجر الغذائي'), ('LAB', 'أداء المختبرات'), ('COMPREHENSIVE', 'تقرير شامل')], max_length=30, verbose_name='النوع')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='الصيغة')),
                ('status', models.CharField(choices=[('PROCESSING', 'قيد الإنشاء'), ('READY', 'جاهز'), ('FAILED', 'فشل')], default='PROCESSING', max_length=20, verbose_name='الحالة')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='المعاملات')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='الملف')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
    ]
