# Generated by Django 5.0.14 on 2026-09-29 20:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_employeeprofile_degree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('HIRE', 'توظيف'), ('PROMOTION', 'ترقية'), ('TRANSFER', 'نقل'), ('DEMOTION', 'خفض'), ('LEAVE_START', 'بداية الإجازة'), ('LEAVE_END', 'انتهاء الإجازة'), ('SUSPENSION', 'تعليق'), ('TERMINATION', 'إنهاء الخدمة'), ('REINSTATE', 'إعادة تعيين'), ('PROBATION_END', 'نهاية فترة الاختبار'), ('CONTRACT_RENEWAL', 'تجديد العقد')], max_length=30, verbose_name='الحدث')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان (للأحداث غير القياسية)')),
                ('old_position', models.CharField(blank=True, max_length=150, verbose_name='المنصب السابق')),
                ('new_position', models.CharField(blank=True, max_length=150, verbose_name='المنصب الجديد')),
                ('old_department', models.CharField(blank=True, max_length=100, verbose_name='القسم السابق')),
                ('new_department', models.CharField(blank=True, max_length=100, verbose_name='القسم الجديد')),
                ('old_sector', models.CharField(blank=True, max_length=50, verbose_name='القطاع السابق')),
                ('new_sector', models.CharField(blank=True, max_length=50, verbose_name='القطاع الجديد')),
                ('old_entry_point', models.CharField(blank=True, max_length=100, verbose_name='نقطة الدخول السابقة')),
                ('new_entry_point', models.CharField(blank=True, max_length=100, verbose_name='نقطة الدخول الجديدة')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب/الملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_timeline_entries', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='accounts.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'أحداث المسار الوظيفي',
                'verbose_name_plural': 'الأحداث الوظيفية',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', '-start_date'], name='hr_employee_employe_3e3fc1_idx'), models.Index(fields=['employee', 'event'], name='hr_employee_employe_c8b52a_idx')],
            },
        ),
    ]
