# Generated by Django 5.0.14 on 2026-09-30 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employeeprofile_degree_and_more'),
        ('hr', '0001_initial'),
        ('masterdata', '0008_entrypoint_location_geo'),
        ('organization', '0007_sector_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('TRANSFER', 'نقل'), ('PROMOTION', 'ترقية'), ('DEMOTION', 'خفض')], max_length=20, verbose_name='نوع الطلب')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُقدَّم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النفاذ المطلوب')),
                ('reason', models.TextField(blank=True, verbose_name='المبرِّر')),
                ('is_self_service', models.BooleanField(default=False, help_text='true إذا رفع الموظف الطلب بنفسه بدل HR.', verbose_name='طلب ذاتي')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('decision_note', models.TextField(blank=True, verbose_name='ملاحظات القرار')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_requests', to='accounts.employeeprofile', verbose_name='الموظف')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests_filed', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='organization.department', verbose_name='القسم المطلوب')),
                ('target_entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='masterdata.entrypoint', verbose_name='نقطة الدخول المطلوبة')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='organization.orgposition', verbose_name='المنصب المطلوب')),
                ('target_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='organization.sector', verbose_name='القطاع المطلوب')),
            ],
            options={
                'verbose_name': 'طلب نقل/ترقية',
                'verbose_name_plural': 'طلبات النقل والترقية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالتغيير')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='hr.postingrequest', verbose_name='طلب النقل')),
            ],
            options={
                'verbose_name': 'سجل حالة طلب النقل',
                'verbose_name_plural': 'سجل حالات طلبات النقل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postingrequest',
            index=models.Index(fields=['employee', '-created_at'], name='hr_postingr_employe_4eeec6_idx'),
        ),
        migrations.AddIndex(
            model_name='postingrequest',
            index=models.Index(fields=['status', '-created_at'], name='hr_postingr_status_7a4e0b_idx'),
        ),
    ]
