# Generated by Django 5.0.14 on 2026-09-30 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employeeprofile_degree_and_more'),
        ('hr', '0002_postingrequest_postingstatuslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غائب'), ('LATE', 'متأخر'), ('EARLY_LEAVE', 'انصراف مبكر'), ('REMOTE', 'عمل عن بُعد'), ('ON_LEAVE', 'إجازة'), ('OFF_DAY', 'يوم راحة')], default='PRESENT', max_length=20, verbose_name='الحالة')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق العمل الإضافي')),
                ('shift_code', models.CharField(blank=True, help_text='يُحفظ كنص لتفادي تعديل الجداول؛ يُنظَّم كمناوبات في مرحلة لاحقة.', max_length=40, verbose_name='رمز الوردية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('external_ref', models.CharField(blank=True, max_length=80, verbose_name='مرجع خارجي')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_approved', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.employeeprofile', verbose_name='الموظف')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL, verbose_name='سجّل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور والانصراف',
                'ordering': ['-date', 'employee__full_name_ar'],
                'indexes': [models.Index(fields=['date', 'status'], name='hr_attendan_date_2ec03d_idx'), models.Index(fields=['employee', '-date'], name='hr_attendan_employe_f69f87_idx'), models.Index(fields=['is_approved', '-date'], name='hr_attendan_is_appr_c36472_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_employee_date', violation_error_message='يوجد سجل حضور لهذا الموظف في هذا التاريخ'),
        ),
    ]
