# Generated by Django 5.0.14 on 2026-09-30 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employeeprofile_degree_and_more'),
        ('hr', '0003_attendancerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('requires_document', models.BooleanField(default=False, help_text='مثل الإجازة المرضية: لا يُعتمد الطلب بلا مرفق.', verbose_name='تطلب مستنداً')),
                ('max_consecutive_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='أقصى عدد أيام متتالية')),
                ('default_entitlement_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='أيام سنوية افتراضية')),
                ('suspends_assignment', models.BooleanField(default=False, verbose_name='توقف التعيين الهيكلي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُقدَّم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('year', models.PositiveSmallIntegerField(help_text='سنة بدء الإجازة، بها يُحتسب الرصيد.', verbose_name='السنة')),
                ('is_half_day', models.BooleanField(default=False, verbose_name='نصف يوم')),
                ('days', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='عدد الأيام')),
                ('reason', models.TextField(blank=True, verbose_name='المبرِّر')),
                ('document', models.CharField(blank=True, help_text='مطلوب للأنواع التي تستند مستنداً؛ يُربط بمخزن الملفات لاحقاً.', max_length=255, verbose_name='المرفق')),
                ('is_self_service', models.BooleanField(default=False, verbose_name='طلب ذاتي')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('decision_note', models.TextField(blank=True, verbose_name='ملاحظات القرار')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.employeeprofile', verbose_name='الموظف')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests_filed', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_substitution', to='accounts.employeeprofile', verbose_name='البديل أثناء الإجازة')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالتغيير')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='hr.leaverequest', verbose_name='طلب الإجازة')),
            ],
            options={
                'verbose_name': 'سجل حالة طلب الإجازة',
                'verbose_name_plural': 'سجل حالات طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('entitled_days', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='أيام مستحقة')),
                ('carried_over_days', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='أيام مرحَّلة من العام الماضي')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='accounts.employeeprofile', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='hr.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['-year', 'leave_type__order'],
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'year', 'status'], name='hr_leavereq_employe_c262fc_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', '-created_at'], name='hr_leavereq_status_0a380a_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='uniq_leave_balance_employee_type_year', violation_error_message='يوجد رصيد لهذا الموظف في هذا النوع لهذه السنة'),
        ),
    ]
