# Generated by Django 5.0.14 on 2026-09-30 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employeeprofile_degree_and_more'),
        ('hr', '0004_leavetype_leaverequest_leavestatuslog_leavebalance_and_more'),
        ('organization', '0007_sector_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('provider', models.CharField(blank=True, help_text='داخلية أو خارجية.', max_length=150, verbose_name='الجهة المنفّذة')),
                ('delivery_mode', models.CharField(choices=[('INTERNAL', 'داخلي'), ('EXTERNAL', 'خارجي'), ('ONLINE', 'عن بُعد'), ('ON_THE_JOB', 'تدريب ميداني')], default='INTERNAL', max_length=20, verbose_name='طريقة التدريب')),
                ('duration_hours', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الساعات')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة')),
                ('is_mandatory', models.BooleanField(default=False, help_text='الدورات الإلزامية تُحتسب في خطة الفرد السنوية.', verbose_name='إلزامي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خطة تدريبية',
                'verbose_name_plural': 'الخطط التدريبية',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='الاسم')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('review_due_date', models.DateField(blank=True, null=True, verbose_name='موعد التقييم')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة'), ('ARCHIVED', 'مؤرشفة')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('is_anonymous_peer_review', models.BooleanField(default=False, verbose_name='تقييم الأقران مجهول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_cycles', to='organization.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'دورة تقييم أداء',
                'verbose_name_plural': 'دورات تقييم الأداء',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='المؤشر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('weight', models.DecimalField(decimal_places=2, help_text='نسبة مئوية؛ مجموع أوزان الدورة 100.', max_digits=5, verbose_name='الوزن')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='hr.performancecycle', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'مؤشر أداء',
                'verbose_name_plural': 'مؤشرات الأداء',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُقدَّم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('RETURNED', 'مُعادة')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية')),
                ('rating', models.CharField(blank=True, help_text='مشتق من الدرجة النهائية: التقدير يُحسب ولا يُكتب.', max_length=20, verbose_name='التقدير')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط القوة')),
                ('improvements', models.TextField(blank=True, verbose_name='نقاط التحسين')),
                ('comments', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_self_service', models.BooleanField(default=False, verbose_name='تقييم ذاتي')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('decision_note', models.TextField(blank=True, verbose_name='ملاحظات القرار')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hr.performancecycle', verbose_name='الدورة')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews_decided', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='accounts.employeeprofile', verbose_name='الموظف')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews_authored', to=settings.AUTH_USER_MODEL, verbose_name='المُقيِّم')),
            ],
            options={
                'verbose_name': 'تقييم أداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewKPIScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة')),
                ('comment', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='hr.performancekpi', verbose_name='المؤشر')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_scores', to='hr.performancereview', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'درجة مؤشر',
                'verbose_name_plural': 'درجات المؤشرات',
                'ordering': ['kpi__order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REQUESTED', 'مطلوب'), ('APPROVED', 'معتمد'), ('IN_PROGRESS', 'جارٍ'), ('COMPLETED', 'مكتمل'), ('FAILED', 'راسب'), ('CANCELLED', 'ملغى'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='تاريخ طلب الاشتراك')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة الاجتياز')),
                ('certificate_ref', models.CharField(blank=True, max_length=80, verbose_name='رقم الشهادة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_self_service', models.BooleanField(default=False, verbose_name='طلب ذاتي')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('decision_note', models.TextField(blank=True, verbose_name='ملاحظات القرار')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_enrollments_decided', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='accounts.employeeprofile', verbose_name='الموظف')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_enrollments_filed', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='hr.trainingplan', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'تسجيل تدريبي',
                'verbose_name_plural': 'التسجيلات التدريبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالتغيير')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='hr.trainingenrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'سجل حالة التسجيل التدريبي',
                'verbose_name_plural': 'سجل حالات التسجيلات التدريبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancekpi',
            constraint=models.UniqueConstraint(fields=('cycle', 'name'), name='uniq_kpi_name_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['cycle', 'status'], name='hr_performa_cycle_i_5a1c30_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='uniq_review_per_employee_cycle'),
        ),
        migrations.AddConstraint(
            model_name='reviewkpiscore',
            constraint=models.UniqueConstraint(fields=('review', 'kpi'), name='uniq_kpi_score_per_review'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['employee', 'status'], name='hr_training_employe_de2966_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['plan', 'status'], name='hr_training_plan_id_12f684_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REJECTED']), _negated=True), fields=('employee', 'plan'), name='uniq_active_enrollment_per_employee_plan', violation_error_message='مسجَّل في هذه الدورة بالفعل (تسجيل قائم غير ملغى)'),
        ),
    ]
