# Generated by Django 5.0.14 on 2026-09-14 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0005_add_public_result_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHOIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('environment', models.CharField(choices=[('DEV', 'تطويري'), ('SANDBOX', 'تجريبي'), ('PRODUCTION', 'إنتاجي')], default='SANDBOX', max_length=20, verbose_name='البيئة')),
                ('base_url', models.URLField(verbose_name='رابط الأساس')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='معرف العميل')),
                ('client_secret_encrypted', models.TextField(blank=True, verbose_name='السر المشفر')),
                ('authentication_type', models.CharField(choices=[('OAUTH2', 'OAuth2'), ('API_KEY', 'مفتاح API'), ('NONE', 'بدون')], default='OAUTH2', max_length=20, verbose_name='نوع المصادقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر نجاح')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ')),
            ],
            options={
                'verbose_name': 'تكامل WHO',
                'verbose_name_plural': 'تكاملات WHO',
            },
        ),
        migrations.CreateModel(
            name='DiseaseMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd11_uri', models.URLField(blank=True, verbose_name='رابط ICD-11')),
                ('who_disease_code', models.CharField(blank=True, max_length=50, verbose_name='كود WHO')),
                ('is_notifiable', models.BooleanField(default=False, verbose_name='واجب الإبلاغ دولياً')),
                ('reporting_timeline', models.CharField(blank=True, max_length=20, verbose_name='زمن الإبلاغ')),
                ('mapped_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الربط')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_sync_status', models.CharField(blank=True, max_length=20, verbose_name='حالة المزامنة')),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who_master', to='laboratory.disease', verbose_name='المرض')),
            ],
            options={
                'verbose_name': 'خريطة مرض WHO',
                'verbose_name_plural': 'خرائط أمراض WHO',
            },
        ),
        migrations.CreateModel(
            name='WHOSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('EVENT_SUBMIT', 'إرسال حدث'), ('DISEASE_SYNC', 'مزامنة أمراض'), ('SPAR_SYNC', 'مزامنة SPAR'), ('ALERT_SYNC', 'مزامنة تنبيهات'), ('TEST_CONNECTION', 'اختبار اتصال'), ('STATUS_CHECK', 'فحص الحالة')], max_length=30, verbose_name='العملية')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'صادر'), ('INBOUND', 'وارد')], default='OUTBOUND', max_length=10, verbose_name='الاتجاه')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المورد')),
                ('local_ref', models.CharField(blank=True, max_length=100, verbose_name='مرجع محلي')),
                ('remote_ref', models.CharField(blank=True, max_length=100, verbose_name='مرجع خارجي')),
                ('request_id', models.CharField(blank=True, max_length=100, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار'), ('PROCESSING', 'قيد المعالجة'), ('SUCCESS', 'نجح'), ('FAILED', 'فشل'), ('RETRY', 'إعادة محاولة'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='رمز HTTP')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الطلب')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='who.whointegration', verbose_name='التكامل')),
            ],
            options={
                'verbose_name': 'سجل مزامنة WHO',
                'verbose_name_plural': 'سجلات مزامنة WHO',
                'ordering': ['-started_at'],
            },
        ),
    ]
