# Generated by Django 5.0.14 on 2026-09-26 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_add_public_result_code'),
        ('who', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WHOICDMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('who_release', models.CharField(max_length=32, verbose_name='إصدار WHO')),
                ('foundation_uri', models.URLField(blank=True, max_length=500, verbose_name='رابط كيان الأساس')),
                ('mms_uri', models.URLField(blank=True, max_length=500, verbose_name='رابط MMS')),
                ('icd_11_code', models.CharField(blank=True, max_length=64, verbose_name='كود ICD-11')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='العنوان بالإنجليزية')),
                ('title_ar', models.CharField(blank=True, max_length=500, verbose_name='العنوان بالعربية')),
                ('mapping_status', models.CharField(choices=[('PENDING', 'بانتظار'), ('PROPOSED', 'مقترح'), ('REVIEW', 'مراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=32, verbose_name='حالة الربط')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='درجة الثقة')),
                ('match_type', models.CharField(blank=True, choices=[('EXACT', 'مطابقة تامة'), ('SEMANTIC', 'مطابقة دلالية'), ('UNSPECIFIED', 'غير محددة'), ('MANUAL', 'يدوية'), ('NO_MATCH', 'لا يوجد تطابق')], max_length=32, verbose_name='نوع التطابق')),
                ('source_query', models.CharField(blank=True, max_length=255, verbose_name='استعلام المصدر')),
                ('is_current', models.BooleanField(default=True, verbose_name='الربط الحالي')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_icd_mappings', to='laboratory.disease', verbose_name='المرض')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_icd_mapping_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'خريطة ICD-11 من WHO',
                'verbose_name_plural': 'خرائط ICD-11 من WHO',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['disease'], name='who_icd_disease_idx'), models.Index(fields=['who_release'], name='who_icd_release_idx'), models.Index(fields=['icd_11_code'], name='who_icd_code_idx'), models.Index(fields=['mapping_status'], name='who_icd_status_idx'), models.Index(fields=['is_current'], name='who_icd_current_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='whoicdmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('disease', 'who_release', 'is_current'), name='uniq_current_who_mapping_per_release'),
        ),
    ]
