# Generated by Django 5.0.14 on 2026-07-31 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('region', models.CharField(choices=[('KHARTOUM', 'الخرطوم'), ('EAST', 'شرقي'), ('CENTRAL', 'وسط'), ('KORDOFAN', 'كردفان'), ('DARFUR', 'دارفور'), ('NORTH', 'شمالي')], max_length=30, verbose_name='المنطقة')),
                ('color', models.CharField(default='#2E7D32', max_length=9, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قطاع',
                'verbose_name_plural': 'القطاعات',
                'ordering': ['name_ar'],
            },
        ),
    ]
