# Generated by Django 5.0.14 on 2026-08-01 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=30, unique=True, verbose_name='رقم الشهادة')),
                ('traveler_name', models.CharField(max_length=150, verbose_name='اسم حامل الشهادة')),
                ('passport_number', models.CharField(max_length=20, verbose_name='رقم جواز السفر')),
                ('certificate_type', models.CharField(choices=[('VACCINATION', 'شهادة تطعيم'), ('MEDICAL', 'شهادة طبية'), ('FITNESS', 'شهادة لياقة')], default='VACCINATION', max_length=20, verbose_name='نوع الشهادة')),
                ('disease', models.CharField(blank=True, max_length=100, verbose_name='المرض/التطعيم')),
                ('issued_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_valid', models.BooleanField(default=True, verbose_name='سارية')),
            ],
            options={
                'verbose_name': 'شهادة صحية',
                'verbose_name_plural': 'الشهادات الصحية',
                'ordering': ['-issued_date'],
            },
        ),
    ]
