# Generated by Django 5.0.14 on 2026-08-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_sector'),
        ('masterdata', '0004_alter_entrypoint_sector'),
        ('ports', '0004_alter_port_sector'),
        ('public', '0003_healthcertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
