# Generated by Django 5.0.14 on 2026-08-27 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_delete_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, default='apps', max_length=60, verbose_name='الأيقونة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة خدمة',
                'verbose_name_plural': 'فئات الخدمات',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, default='task', max_length=60, verbose_name='الأيقونة')),
                ('route', models.CharField(blank=True, help_text='المسار الداخلي للواجهة (مثل /services/food-safety/import)', max_length=255, verbose_name='المسار')),
                ('external_url', models.CharField(blank=True, max_length=500, verbose_name='رابط خارجي')),
                ('audience', models.CharField(choices=[('PUBLIC', 'عام'), ('INDIVIDUAL', 'أفراد'), ('BUSINESS', 'أعمال'), ('GOVERNMENT', 'جهات حكومية'), ('EMPLOYEE', 'موظفون')], default='PUBLIC', max_length=20, verbose_name='الجمهور')),
                ('requires_auth', models.BooleanField(default=False, verbose_name='يتطلب مصادقة')),
                ('identity_provider', models.CharField(choices=[('NONE', 'لا يتطلب هوية'), ('SUDAPASS', 'سوداباس (الهوية الرقمية)'), ('CREDENTIALS', 'اسم مستخدم وكلمة مرور')], default='NONE', max_length=20, verbose_name='موفّر الهوية')),
                ('target_system', models.CharField(blank=True, help_text='النظام المتخصص الذي تنفَّذ فيه الخدمة', max_length=100, verbose_name='النظام التشغيلي')),
                ('status', models.CharField(choices=[('ACTIVE', 'متاح'), ('COMING_SOON', 'قريباً')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='public.servicecategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['category__sort_order', 'sort_order', 'name_ar'],
            },
        ),
    ]
