# Generated by Django 6.1 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_sector_contact_fields'),
        ('public', '0005_servicecategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='sectors',
            field=models.ManyToManyField(blank=True, help_text='إن تركت فارغة فالفئة ظاهرة لجميع القطاعات، وإن حُددت قطاعات فعرضها يقتصر عليها.', related_name='service_categories', to='organization.sector', verbose_name='القطاعات'),
        ),
    ]
