# Generated by Django 5.0.14 on 2026-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_servicecategory_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='identity_provider',
            field=models.CharField(choices=[('NONE', 'لا يتطلب هوية'), ('CREDENTIALS', 'اسم مستخدم وكلمة مرور')], default='NONE', max_length=20, verbose_name='موفّر الهوية'),
        ),
    ]
