# Generated by Django 5.0.14 on 2026-10-01 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_service_identity_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.CharField(choices=[('GREETING', 'Greeting'), ('THANKS', 'Thanks'), ('FAQ', 'Faq'), ('TRAVEL_REQUIREMENTS', 'Travel Requirements'), ('COUNTRY_REQUIREMENTS', 'Country Requirements'), ('VACCINATION', 'Vaccination'), ('DOCUMENTS', 'Documents'), ('QR', 'Qr'), ('CERTIFICATE', 'Certificate'), ('TRACKING', 'Tracking'), ('REGISTRATION', 'Registration'), ('SERVICES', 'Services'), ('NOTICE', 'Notice'), ('DISEASE', 'Disease'), ('CONTACT', 'Contact'), ('ESCALATE', 'Escalate'), ('UNKNOWN', 'Unknown')], db_index=True, max_length=30, verbose_name='النية')),
                ('answer_type', models.CharField(choices=[('INFO', 'Info'), ('ACTION', 'Action'), ('ALERT', 'Alert'), ('SOURCE', 'Source'), ('NOT_FOUND', 'Not Found')], db_index=True, default='INFO', max_length=12, verbose_name='نوع الإجابة')),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=6, verbose_name='درجة الثقة')),
                ('language', models.CharField(default='ar', max_length=2, verbose_name='اللغة')),
                ('source_count', models.PositiveIntegerField(default=0, verbose_name='عدد المصادر')),
                ('message_length', models.PositiveIntegerField(default=0, verbose_name='طول الرسالة')),
                ('has_disclaimer', models.BooleanField(default=False, verbose_name='حمل إخلاء المسؤولية')),
                ('engine', models.CharField(default='rules', max_length=20, verbose_name='المحرّك')),
            ],
            options={
                'verbose_name': 'محادثة مساعد',
                'verbose_name_plural': 'محادثات المساعد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intent', '-created_at'], name='public_assi_intent_fb3b57_idx'), models.Index(fields=['-created_at'], name='public_assi_created_09e1c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.SmallIntegerField(choices=[(1, 'مفيد'), (-1, 'غير مفيد')], verbose_name='التقييم')),
                ('intent', models.CharField(blank=True, choices=[('GREETING', 'Greeting'), ('THANKS', 'Thanks'), ('FAQ', 'Faq'), ('TRAVEL_REQUIREMENTS', 'Travel Requirements'), ('COUNTRY_REQUIREMENTS', 'Country Requirements'), ('VACCINATION', 'Vaccination'), ('DOCUMENTS', 'Documents'), ('QR', 'Qr'), ('CERTIFICATE', 'Certificate'), ('TRACKING', 'Tracking'), ('REGISTRATION', 'Registration'), ('SERVICES', 'Services'), ('NOTICE', 'Notice'), ('DISEASE', 'Disease'), ('CONTACT', 'Contact'), ('ESCALATE', 'Escalate'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=30, verbose_name='النية (نسخة عند التقييم)')),
                ('answer_type', models.CharField(blank=True, choices=[('INFO', 'Info'), ('ACTION', 'Action'), ('ALERT', 'Alert'), ('SOURCE', 'Source'), ('NOT_FOUND', 'Not Found')], default='INFO', max_length=12, verbose_name='نوع الإجابة (نسخة عند التقييم)')),
                ('engine', models.CharField(default='rules', max_length=20, verbose_name='المحرّك')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='public.assistantconversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'تقييم مساعد',
                'verbose_name_plural': 'تقييمات المساعد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intent', '-created_at'], name='public_assi_intent_14ab5d_idx')],
            },
        ),
    ]
