# Generated by Django 5.0.14 on 2026-08-08 12:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_quarantine', '0005_foodshipment_referral_reference_and_more'),
        ('ports', '0002_port_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الإنذار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('reason', models.CharField(choices=[('REPEATED_NON_CONFORMITY', 'تكرار عدم المطابقة'), ('LAB_TREND', 'اتجاه مخبري'), ('FOODBORNE_OUTBREAK', 'تفشٍ مرض منقول بالغذاء'), ('IMPORT_RISK', 'مخاطر استيراد'), ('EXPORT_REJECTION', 'رفض تصدير'), ('RECALL', 'سحب منتج'), ('CUSTOM', 'سبب مخصص')], max_length=30, verbose_name='السبب')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالٍ'), ('CRITICAL', 'حرج')], default='MEDIUM', max_length=20, verbose_name='مستوى الخطر')),
                ('product', models.CharField(blank=True, max_length=200, verbose_name='المنتج')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='المورد')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('recommended_action', models.CharField(blank=True, max_length=255, verbose_name='الإجراء المقترح')),
                ('status', models.CharField(choices=[('NEW', 'جديد'), ('ACKNOWLEDGED', 'تم الاطلاع'), ('INVESTIGATING', 'قيد التحقيق'), ('ACTIONED', 'تم اتخاذ إجراء'), ('CLOSED', 'مغلق')], default='NEW', max_length=20, verbose_name='الحالة')),
                ('raised_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_alerts_raised', to=settings.AUTH_USER_MODEL, verbose_name='مُنشئ الإنذار')),
            ],
            options={
                'verbose_name': 'إنذار غذائي',
                'verbose_name_plural': 'الإنذارات الغذائية',
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodEstablishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('establishment_type', models.CharField(choices=[('RESTAURANT', 'مطعم'), ('FACTORY', 'مصنع'), ('WAREHOUSE', 'مخزن'), ('SUPPLIER', 'مورد'), ('DISTRIBUTOR', 'موزع'), ('RETAILER', 'منفذ بيع')], max_length=20, verbose_name='النوع')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالٍ'), ('CRITICAL', 'حرج')], default='LOW', max_length=20, verbose_name='مستوى المخاطر')),
                ('last_inspection_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تفتيش')),
                ('violations_count', models.PositiveIntegerField(default=0, verbose_name='عدد المخالفات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_establishments', to='ports.port', verbose_name='المنفذ المرتبط')),
            ],
            options={
                'verbose_name': 'منشأة غذائية',
                'verbose_name_plural': 'المنشآت الغذائية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='FoodRecall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recall_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم السحب')),
                ('product', models.CharField(max_length=200, verbose_name='المنتج')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ')),
                ('recall_type', models.CharField(choices=[('WITHDRAWAL', 'سحب احترازي'), ('RECALL', 'استدعاء')], default='RECALL', max_length=20, verbose_name='نوع السحب')),
                ('reasons', models.TextField(blank=True, verbose_name='الأسباب')),
                ('status', models.CharField(choices=[('DECIDED', 'قرار'), ('NOTIFYING', 'إخطار الجهات'), ('WITHDRAWING', 'سحب المنتج'), ('VERIFYING', 'تحقق من السحب'), ('CLOSED', 'مغلق')], default='DECIDED', max_length=20, verbose_name='الحالة')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالٍ'), ('CRITICAL', 'حرج')], default='HIGH', max_length=20, verbose_name='مستوى المخاطر')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت القرار')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_recalls', to=settings.AUTH_USER_MODEL, verbose_name='مُصدر القرار')),
            ],
            options={
                'verbose_name': 'سحب منتج غذائي',
                'verbose_name_plural': 'سحبات المنتجات الغذائية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nc_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم عدم المطابقة')),
                ('source', models.CharField(choices=[('LAB', 'مختبر'), ('IMPORT', 'استيراد'), ('EXPORT', 'تصدير'), ('ESTABLISHMENT', 'منشأة'), ('SURVEILLANCE', 'ترصد')], default='LAB', max_length=20, verbose_name='المصدر')),
                ('product', models.CharField(blank=True, max_length=200, verbose_name='المنتج')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='المورد')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('UNDER_INVESTIGATION', 'قيد التحقيق'), ('CORRECTIVE_ACTION', 'إجراء تصحيحي'), ('RESOLVED', 'تم الحل'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=25, verbose_name='الحالة')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالٍ'), ('CRITICAL', 'حرج')], default='MEDIUM', max_length=20, verbose_name='مستوى المخاطر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('required_action', models.TextField(blank=True, verbose_name='الإجراء المطلوب')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البلاغ')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_non_conformities', to=settings.AUTH_USER_MODEL, verbose_name='المُبلّغ')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='food_quarantine.foodsample', verbose_name='العينة')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'عدم مطابقة غذائية',
                'verbose_name_plural': 'حالات عدم المطابقة الغذائية',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.TextField(verbose_name='الإجراء')),
                ('responsible', models.CharField(blank=True, max_length=255, verbose_name='المسؤول')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('PLANNED', 'مخطط'), ('IN_PROGRESS', 'قيد التنفيذ'), ('VERIFIED', 'تم التحقق'), ('COMPLETED', 'مكتمل')], default='PLANNED', max_length=20, verbose_name='الحالة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنجاز')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_corrective_actions', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('non_conformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='food_surveillance.nonconformity', verbose_name='عدم المطابقة')),
            ],
            options={
                'verbose_name': 'إجراء تصحيحي',
                'verbose_name_plural': 'الإجراءات التصحيحية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.CharField(choices=[('PRODUCT', 'منتج'), ('COUNTRY', 'دولة'), ('SUPPLIER', 'مورد'), ('SHIPMENT', 'شحنة'), ('ESTABLISHMENT', 'منشأة')], max_length=20, verbose_name='نوع التقييم')),
                ('target_name', models.CharField(max_length=255, verbose_name='الكيان المستهدف')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='النتيجة 0-100')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالٍ'), ('CRITICAL', 'حرج')], default='LOW', max_length=20, verbose_name='مستوى المخاطر')),
                ('justification', models.TextField(blank=True, verbose_name='التبرير')),
                ('recommendation', models.TextField(blank=True, verbose_name='التوصية')),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقييم')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='المُقيّم')),
            ],
            options={
                'verbose_name': 'تقييم مخاطر غذائية',
                'verbose_name_plural': 'تقييمات المخاطر الغذائية',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
