# Generated by Django 6.1 on 2026-09-11 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_quarantine', '0025_alter_sampletest_status'),
        ('masterdata', '0006_entrypoint_locality_healthfacility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم النافذة بالعربية')),
                ('window_type', models.CharField(choices=[('SINGLE', 'نافذة واحدة'), ('MULTI', 'عدة نوافذ')], default='SINGLE', max_length=10, verbose_name='نوع النافذة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_windows', to='masterdata.entrypoint', verbose_name='المنفذ')),
            ],
            options={
                'verbose_name': 'نافذة خدمة',
                'verbose_name_plural': 'نوافذ الخدمة',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد المعالجة'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_clerk_transactions', to=settings.AUTH_USER_MODEL, verbose_name='موظّف النافذة')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_transactions', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='food_window.servicewindow', verbose_name='النافذة')),
            ],
            options={
                'verbose_name': 'معاملة شحنة',
                'verbose_name_plural': 'معاملات الشحنات',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCommodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة')),
                ('decision', models.CharField(blank=True, max_length=20, verbose_name='القرار')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_lines', to='food_window.shipmenttransaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'بند معاملة',
                'verbose_name_plural': 'بنود المعاملات',
                'ordering': ['commodity__order'],
            },
        ),
        migrations.CreateModel(
            name='CommodityDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'مطابق'), ('REJECTED', 'مرفوض'), ('HOLD', 'موقوف')], max_length=20, verbose_name='القرار')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت القرار')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodity_decisions', to=settings.AUTH_USER_MODEL, verbose_name='مُصدر القرار')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='food_window.transactioncommodity', verbose_name='بند السلعة')),
            ],
            options={
                'verbose_name': 'قرار سلعة',
                'verbose_name_plural': 'قرارات السلع',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='WindowAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=60, verbose_name='الإجراء')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='food_window.servicewindow', verbose_name='النافذة')),
            ],
            options={
                'verbose_name': 'سجل تدقيق النافذة',
                'verbose_name_plural': 'سجلات تدقيق النوافذ',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WindowCommodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='food_window.servicewindow', verbose_name='النافذة')),
            ],
            options={
                'verbose_name': 'سلعة النافذة',
                'verbose_name_plural': 'سلع النوافذ',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='WindowAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التعيين')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='food_window.servicewindow', verbose_name='النافذة')),
                ('commodities', models.ManyToManyField(blank=True, related_name='assignments', to='food_window.windowcommodity', verbose_name='السلع المدعومة')),
            ],
            options={
                'verbose_name': 'تعيين نافذة',
                'verbose_name_plural': 'تعيينات النوافذ',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='transactioncommodity',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lines', to='food_window.windowcommodity', verbose_name='السلعة'),
        ),
        migrations.AddField(
            model_name='shipmenttransaction',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='food_window.windowcommodity', verbose_name='السلعة'),
        ),
    ]
