# Generated by Django 5.0.14 on 2026-07-31 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربية')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='رقم جواز السفر')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('medical_history', models.JSONField(blank=True, default=dict, verbose_name='التاريخ الطبي')),
                ('registration_status', models.CharField(choices=[('PENDING_DOCUMENTS', 'في انتظار المستندات'), ('UNDER_REVIEW', 'قيد المراجعة'), ('COMPLETED', 'مكتمل'), ('REJECTED', 'مرفوض')], default='PENDING_DOCUMENTS', max_length=20, verbose_name='حالة التسجيل')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travelers', to='travelers.country', verbose_name='الجنسية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travelers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'المسافرون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'جواز السفر'), ('VACCINE', 'شهادة تطعيم'), ('TEST_RESULT', 'نتيجة فحص'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='الملف')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفع')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travelers.traveler', verbose_name='المسافر')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
