# Generated by Django 5.0.14 on 2026-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='risk_level',
            field=models.CharField(choices=[('GREEN', 'أخضر'), ('YELLOW', 'أصفر'), ('RED', 'أحمر')], default='GREEN', max_length=10, verbose_name='مستوى الخطر'),
        ),
    ]
