# Generated by Django 5.0.14 on 2026-08-07 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0002_country_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='registration_status',
            field=models.CharField(choices=[('PENDING_DOCUMENTS', 'في انتظار المستندات'), ('UNDER_REVIEW', 'قيد المراجعة'), ('ACTION_REQUIRED', 'إجراء مطلوب'), ('COMPLETED', 'مكتمل'), ('REJECTED', 'مرفوض')], default='PENDING_DOCUMENTS', max_length=20, verbose_name='حالة التسجيل'),
        ),
        migrations.CreateModel(
            name='TravelerStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traveler_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالتغيير')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='travelers.traveler', verbose_name='المسافر')),
            ],
            options={
                'verbose_name': 'سجل حالة الطلب',
                'verbose_name_plural': 'سجل حالات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
