# Generated by Django 5.0.14 on 2026-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0003_alter_traveler_registration_status_travelerstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='medical_file_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الملف الطبي الموحد'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='qr_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='رمز QR للملف الطبي'),
        ),
    ]
