# Generated by Django 5.0.14 on 2026-09-14 08:25

import apps.ihr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency_eoc', '0005_emergencyevent_case_count_emergencyevent_death_count_and_more'),
        ('laboratory', '0005_add_public_result_code'),
        ('masterdata', '0007_merge_sdpor_to_ep_port_sudan'),
        ('organization', '0007_sector_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPARIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('max_score', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='الدرجة القصوى')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مؤشر SPAR',
                'verbose_name_plural': 'مؤشرات SPAR',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IHREvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_number', models.CharField(default=apps.ihr.models.ihr_event_number, editable=False, max_length=40, unique=True, verbose_name='رقم الحدث')),
                ('event_type', models.CharField(choices=[('INFECTIOUS_DISEASE', 'مرض معدٍ'), ('ZOONOTIC', 'مرض حيواني المصدر'), ('FOOD_SAFETY', 'سلامة الغذاء'), ('CHEMICAL', 'خطر كيميائي'), ('RADIOLOGICAL', 'خطر إشعاعي'), ('UNKNOWN', 'غير معروف')], default='INFECTIOUS_DISEASE', max_length=30, verbose_name='نوع الحدث')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('date_detected', models.DateField(verbose_name='تاريخ الاكتشاف')),
                ('date_verified', models.DateField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('cases_suspected', models.PositiveIntegerField(default=0, verbose_name='حالات مشتبهة')),
                ('cases_probable', models.PositiveIntegerField(default=0, verbose_name='حالات محتملة')),
                ('cases_confirmed', models.PositiveIntegerField(default=0, verbose_name='حالات مؤكدة')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='الوفيات')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MODERATE', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='MODERATE', max_length=20, verbose_name='مستوى الخطورة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('UNDER_REVIEW', 'قيد المراجعة'), ('NATIONAL_ASSESSMENT', 'تقييم وطني'), ('NFP_REVIEW', 'مراجعة نقطة الاتصال'), ('NOTIFIABLE', 'واجب الإبلاغ'), ('SUBMITTED', 'أُرسل لمنظمة الصحة'), ('FOLLOW_UP', 'متابعة'), ('CLOSED', 'مغلق')], default='DRAFT', max_length=30, verbose_name='الحالة')),
                ('submitted_to_who_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال لمنظمة الصحة')),
                ('who_reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع الخارجي لمنظمة الصحة')),
                ('is_international_impact', models.BooleanField(default=False, verbose_name='تأثير دولي محتمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihr_events', to='laboratory.disease', verbose_name='المرض')),
                ('emergency_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihr_event', to='emergency_eoc.emergencyevent', verbose_name='حدث الطوارئ المرتبط')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihr_events', to='organization.locality', verbose_name='المحلية')),
                ('nfp_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ihr_events', to=settings.AUTH_USER_MODEL, verbose_name='مصادق نقطة الاتصال')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihr_events', to='masterdata.entrypoint', verbose_name='المنفذ')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ihr_events', to=settings.AUTH_USER_MODEL, verbose_name='المُبلّغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ihr_events', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihr_events', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'حدث IHR',
                'verbose_name_plural': 'أحداث IHR',
                'ordering': ['-date_detected', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NationalFocalPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfp_type', models.CharField(choices=[('PRIMARY', 'أساسي'), ('ALTERNATE', 'بديل'), ('DEPUTY', 'نائب')], default='PRIMARY', max_length=20, verbose_name='نوع النقطة')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='المؤسسة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('appointed_at', models.DateField(verbose_name='تاريخ التعيين')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfp_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نقطة اتصال وطنية',
                'verbose_name_plural': 'نقاط الاتصال الوطنية',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard', models.CharField(max_length=300, verbose_name='الخطر')),
                ('geographic_spread', models.CharField(blank=True, max_length=300, verbose_name='الانتشار الجغرافي')),
                ('transmission', models.CharField(blank=True, max_length=300, verbose_name='نمط الانتقال')),
                ('international_travel', models.CharField(blank=True, max_length=300, verbose_name='السفر الدولي')),
                ('poe_impact', models.CharField(blank=True, max_length=300, verbose_name='أثر نقاط الدخول')),
                ('response_capacity', models.CharField(blank=True, max_length=300, verbose_name='جهوزية الاستجابة')),
                ('overall_risk', models.CharField(choices=[('LOW', 'منخفض'), ('MODERATE', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='MODERATE', max_length=20, verbose_name='الخطر الكلي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التقييم')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='ihr.ihrevent', verbose_name='الحدث')),
            ],
            options={
                'verbose_name': 'تقييم مخاطر',
                'verbose_name_plural': 'تقييمات المخاطر',
            },
        ),
        migrations.CreateModel(
            name='SPARAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='الدرجة')),
                ('evidence', models.TextField(blank=True, verbose_name='الأدلة')),
                ('gaps', models.TextField(blank=True, verbose_name='الفجوات')),
                ('action_plan', models.TextField(blank=True, verbose_name='خطة التحسين')),
                ('comments', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spar_assessments', to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='ihr.sparindicator', verbose_name='المؤشر')),
            ],
            options={
                'verbose_name': 'تقييم SPAR',
                'verbose_name_plural': 'تقييمات SPAR',
                'ordering': ['year', 'indicator__order'],
                'unique_together': {('year', 'indicator')},
            },
        ),
    ]
