# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('body_text', models.TextField(verbose_name='النص')),
                ('body_html', models.TextField(blank=True, verbose_name='نص HTML')),
                ('sms_body', models.CharField(blank=True, max_length=160, verbose_name='نص الرسالة النصية')),
                ('channel', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('push', 'إشعار'), ('websocket', 'WebSocket')], max_length=20, verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_token', models.CharField(max_length=255, unique=True, verbose_name='رمز الجهاز')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20, verbose_name='المنصة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز جهاز',
                'verbose_name_plural': 'رموز الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=20, verbose_name='القناة')),
                ('recipient', models.CharField(max_length=255, verbose_name='المستلم')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='الموضوع')),
                ('body', models.TextField(blank=True, verbose_name='النص')),
                ('status', models.CharField(choices=[('sent', 'أُرسلت'), ('failed', 'فشلت'), ('pending', 'قيد الإرسال')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationtemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
