# Generated by Django 5.0.14 on 2026-09-13 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=512, unique=True, verbose_name='نقطة دفع المتصفح')),
                ('p256dh', models.CharField(max_length=256, verbose_name='مفتاح العميل (p256dh)')),
                ('auth', models.CharField(max_length=64, verbose_name='سرّ المصادقة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك إشعار ويب',
                'verbose_name_plural': 'اشتراكات إشعارات الويب',
                'ordering': ['-created_at'],
            },
        ),
    ]
