# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('travelers', '0002_country_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_temperature', models.FloatField(blank=True, null=True, verbose_name='درجة الحرارة')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='تشبع الأكسجين')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانقباضي')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانبساطي')),
                ('observed_symptoms', models.JSONField(blank=True, default=list, verbose_name='الأعراض الملاحظة')),
                ('officer_notes', models.TextField(blank=True, verbose_name='ملاحظات الموظف')),
                ('screened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفحص')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='ports.port', verbose_name='المنفذ')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='travelers.traveler', verbose_name='المسافر')),
            ],
            options={
                'verbose_name': 'فحص صحي',
                'verbose_name_plural': 'الفحوصات الصحية',
                'ordering': ['-screened_at'],
            },
        ),
    ]
