# Generated by Django 5.0.14 on 2026-08-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_bridge_to_entrypoint'),
        ('masterdata', '0001_initial'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthscreening',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='masterdata.entrypoint', verbose_name='المنفذ'),
        ),
    ]
