# Generated by Django 5.0.14 on 2026-09-01 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0005_entrypoint_address_entrypoint_email_entrypoint_phone'),
        ('organization', '0004_station_orgassignment_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='اسم الجهاز')),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'حاسب آلي'), ('LAPTOP', 'حاسب محمول'), ('PRINTER', 'طابعة'), ('SCANNER', 'ماسح ضوئي'), ('NETWORK', 'موجه شبكة'), ('SERVER', 'خادم'), ('OTHER', 'أخرى')], default='COMPUTER', max_length=20, verbose_name='النوع')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='الرقم التسلسلي')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('MAINTENANCE', 'قيد الصيانة'), ('REPAIR', 'مُعطّل'), ('INACTIVE', 'متوقف')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_assets', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_assets', to='masterdata.entrypoint', verbose_name='نقطة الدخول')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_assets', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'أصل تقني',
                'verbose_name_plural': 'الأصول التقنية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود النظام')),
                ('name', models.CharField(max_length=120, verbose_name='اسم النظام')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالعربية')),
                ('status', models.CharField(choices=[('ONLINE', 'مُتصل'), ('WARNING', 'تحذير'), ('OFFLINE', 'متوقف')], default='ONLINE', max_length=20, verbose_name='الحالة')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فحص')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_systems', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'نظام تقني',
                'verbose_name_plural': 'الأنظمة التقنية',
                'ordering': ['name_ar', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected', models.BooleanField(default=True, verbose_name='متصل')),
                ('ping_ms', models.PositiveSmallIntegerField(default=0, verbose_name='زمن الاستجابة (مللي ثانية)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('entry_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_network', to='masterdata.entrypoint', verbose_name='نقطة الدخول')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_networks', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'حالة شبكة',
                'verbose_name_plural': 'حالة الشبكات',
                'ordering': ['entry_point__order'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_no', models.CharField(max_length=30, unique=True, verbose_name='رقم التذكرة')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('CRITICAL', 'حرجة'), ('HIGH', 'عالية'), ('MEDIUM', 'متوسطة'), ('LOW', 'منخفضة')], default='MEDIUM', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد المعالجة'), ('RESOLVED', 'مُعالجة'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المُسند إليه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='المُنشئ')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_tickets', to='masterdata.entrypoint', verbose_name='نقطة الدخول')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_tickets', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
    ]
