# Generated by Django 5.0.14 on 2026-09-03 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود التكامل')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('status', models.CharField(choices=[('CONNECTED', 'متصل'), ('WARNING', 'تأخير'), ('ERROR', 'خطأ')], default='CONNECTED', max_length=20, verbose_name='الحالة')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تكامل حكومي',
                'verbose_name_plural': 'التكاملات الحكومية',
                'ordering': ['order', 'name_ar'],
            },
        ),
    ]
