# Generated by Django 5.0.14 on 2026-08-15 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('color', models.CharField(default='#0B5CAD', max_length=9, verbose_name='اللون')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قطاع (نوع)',
                'verbose_name_plural': 'القطاعات (أنواع الحجر)',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SectionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_label', models.CharField(blank=True, max_length=120, verbose_name='العنوان الوظيفي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='masterdata.section', verbose_name='القسم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masterdata_memberships', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عضو قسم',
                'verbose_name_plural': 'أعضاء الأقسام',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='masterdata.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'الولايات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('kind', models.CharField(choices=[('SEAPORT', 'ميناء بحري'), ('LAND_PORT', 'منفذ بري'), ('AIRPORT', 'مطار')], max_length=20, verbose_name='النوع')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='masterdata.state', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'منفذ دخول',
                'verbose_name_plural': 'منافذ الدخول',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations_direct', to='masterdata.entrypoint', verbose_name='منفذ الدخول (مباشرة)')),
            ],
            options={
                'verbose_name': 'محطة حجر صحي',
                'verbose_name_plural': 'محطات الحجر الصحي',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='masterdata.station', verbose_name='المحطة'),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('entry_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='masterdata.entrypoint', verbose_name='منفذ الدخول')),
            ],
            options={
                'verbose_name': 'منشأة/طرفية',
                'verbose_name_plural': 'المنشآت/الطرفيات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='station',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='masterdata.terminal', verbose_name='المنشأة'),
        ),
    ]
