# Generated by Django 5.0.14 on 2026-08-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('public', '0003_healthcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_points', to='public.sector', verbose_name='القطاع الإداري'),
        ),
    ]
