# Generated by Django 5.0.14 on 2026-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_entrypoint_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='entrypoint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='entrypoint',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
    ]
