# Generated by Django 5.0.14 on 2026-09-07 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_entrypoint_address_entrypoint_email_entrypoint_phone'),
        ('organization', '0006_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_points', to='organization.locality', verbose_name='المحلية'),
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('kind', models.CharField(choices=[('HOSPITAL', 'مستشفى'), ('HEALTH_CENTER', 'مركز صحي'), ('PRIMARY_UNIT', 'وحدة صحية أولية'), ('CLINIC', 'عيادة'), ('QUARANTINE', 'محجر صحي'), ('OTHER', 'أخرى')], default='HEALTH_CENTER', max_length=20, verbose_name='النوع')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='masterdata.entrypoint', verbose_name='منفذ الدخول')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organization.locality', verbose_name='المحلية')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='organization.sector', verbose_name='القطاع الإداري')),
            ],
            options={
                'verbose_name': 'وحدة صحية',
                'verbose_name_plural': 'الوحدات الصحية',
                'ordering': ['order', 'name_ar'],
            },
        ),
    ]
