# Generated by Django 5.0.14 on 2026-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_merge_sdpor_to_ep_port_sudan'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='location_geo',
            field=models.JSONField(blank=True, default=dict, verbose_name='الموقع الجغرافي'),
        ),
    ]
