# Generated by Django 5.0.14 on 2026-09-29 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borders_health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordershift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_shifts', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='quarantinecase',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=30, unique=True, verbose_name='رقم الحالة'),
        ),
        migrations.AlterField(
            model_name='travelerhealthrecord',
            name='entry_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت العبور'),
        ),
    ]
