# Generated by Django 5.0.14 on 2026-09-29 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borders_health', '0002_alter_bordershift_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderemergency',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_emergencies_reported', to=settings.AUTH_USER_MODEL, verbose_name='المبلِّغ'),
        ),
        migrations.AlterField(
            model_name='borderhealthincident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_incidents_reported', to=settings.AUTH_USER_MODEL, verbose_name='المبلِّغ'),
        ),
        migrations.AlterField(
            model_name='bordernotification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='travelerhealthrecord',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_traveler_records', to=settings.AUTH_USER_MODEL, verbose_name='المُقيِّم'),
        ),
    ]
