# Generated by Django 5.0.14 on 2026-09-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borders_health', '0003_alter_borderemergency_reported_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercertificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='أصدرها'),
        ),
        migrations.AlterField(
            model_name='borderdecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='المُقرِّر'),
        ),
    ]
