# Generated by Django 5.0.14 on 2026-09-29 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borders_health', '0004_alter_bordercertificate_issued_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordersample',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_samples_collected', to=settings.AUTH_USER_MODEL, verbose_name='المسحوب'),
        ),
        migrations.AlterField(
            model_name='borderscreening',
            name='screened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_screenings_performed', to=settings.AUTH_USER_MODEL, verbose_name='الفاحص'),
        ),
        migrations.AlterField(
            model_name='isolationcase',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_isolation_started', to=settings.AUTH_USER_MODEL, verbose_name='بدأها'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_vehicle_inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش'),
        ),
    ]
