# Generated by Django 5.0.14 on 2026-09-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borders_health', '0005_alter_bordersample_collected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinecase',
            name='case_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='رقم الحالة'),
        ),
    ]
