# Generated by Django 5.0.14 on 2026-09-30 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borders_health', '0006_alter_quarantinecase_case_number'),
        ('clinic', '0010_alter_clinicreferral_status'),
        ('emergency_eoc', '0005_emergencyevent_case_count_emergencyevent_death_count_and_more'),
        ('food_quarantine', '0025_alter_sampletest_status'),
        ('laboratory', '0005_add_public_result_code'),
        ('masterdata', '0008_entrypoint_location_geo'),
        ('screening', '0002_alter_healthscreening_port'),
        ('travelers', '0004_traveler_medical_file_no_traveler_qr_token'),
        ('vaccination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bordercertificate',
            index=models.Index(fields=['crossing', 'issue_date'], name='bh_ci_crt'),
        ),
        migrations.AddIndex(
            model_name='bordercrossing',
            index=models.Index(fields=['operating_status'], name='bh_o_xc'),
        ),
        migrations.AddIndex(
            model_name='bordercrossing',
            index=models.Index(fields=['neighbor_country'], name='bh_n_xc'),
        ),
        migrations.AddIndex(
            model_name='borderdecision',
            index=models.Index(fields=['crossing', 'decided_at'], name='bh_cd_dec'),
        ),
        migrations.AddIndex(
            model_name='borderemergency',
            index=models.Index(fields=['crossing', 'status'], name='bh_cs_emg'),
        ),
        migrations.AddIndex(
            model_name='borderfacility',
            index=models.Index(fields=['crossing', 'kind'], name='bh_ck_fac'),
        ),
        migrations.AddIndex(
            model_name='borderhealthincident',
            index=models.Index(fields=['crossing', 'status'], name='bh_cs_inc'),
        ),
        migrations.AddIndex(
            model_name='bordernotification',
            index=models.Index(fields=['crossing', 'sent_at'], name='bh_cs_ntf'),
        ),
        migrations.AddIndex(
            model_name='bordersample',
            index=models.Index(fields=['crossing', 'collected_at'], name='bh_cc_smp'),
        ),
        migrations.AddIndex(
            model_name='bordersample',
            index=models.Index(fields=['cargo_inspection', 'status'], name='bh_cs_smp'),
        ),
        migrations.AddIndex(
            model_name='borderscreening',
            index=models.Index(fields=['crossing', 'screened_at'], name='bh_cs_scr'),
        ),
        migrations.AddIndex(
            model_name='borderscreening',
            index=models.Index(fields=['traveler', 'crossing'], name='bh_tc_scr'),
        ),
        migrations.AddIndex(
            model_name='borderscreening',
            index=models.Index(fields=['crossing', 'decision'], name='bh_cd_scr'),
        ),
        migrations.AddIndex(
            model_name='bordershift',
            index=models.Index(fields=['crossing', 'shift_date'], name='bh_cs_shf'),
        ),
        migrations.AddIndex(
            model_name='borderstaff',
            index=models.Index(fields=['crossing', 'is_active'], name='bh_ci_stf'),
        ),
        migrations.AddIndex(
            model_name='cargoinspection',
            index=models.Index(fields=['crossing', 'scope', 'status'], name='bh_css_crg'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tracing_case', 'status'], name='bh_ts_con'),
        ),
        migrations.AddIndex(
            model_name='contacttracingcase',
            index=models.Index(fields=['crossing', 'status'], name='bh_cs_ctc'),
        ),
        migrations.AddIndex(
            model_name='healthdeclaration',
            index=models.Index(fields=['crossing', 'declared_at'], name='bh_cd_dcl'),
        ),
        migrations.AddIndex(
            model_name='healthdeclaration',
            index=models.Index(fields=['traveler', 'crossing'], name='bh_tc_dcl'),
        ),
        migrations.AddIndex(
            model_name='isolationcase',
            index=models.Index(fields=['crossing', 'status'], name='bh_cs_iso'),
        ),
        migrations.AddIndex(
            model_name='quarantinecase',
            index=models.Index(fields=['crossing', 'status'], name='bh_cs_qua'),
        ),
        migrations.AddIndex(
            model_name='quarantinecase',
            index=models.Index(fields=['crossing', 'entry_at'], name='bh_ce_qua'),
        ),
        migrations.AddIndex(
            model_name='travelerhealthrecord',
            index=models.Index(fields=['crossing', 'entry_at'], name='bh_ce_thr'),
        ),
        migrations.AddIndex(
            model_name='travelerhealthrecord',
            index=models.Index(fields=['traveler', 'crossing'], name='bh_tc_thr'),
        ),
        migrations.AddIndex(
            model_name='travelerhealthrecord',
            index=models.Index(fields=['crossing', 'risk_level'], name='bh_cr_thr'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['crossing', 'status'], name='bh_cs_veh'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['vehicle', 'inspection_date'], name='bh_vi_vin'),
        ),
    ]
