# Generated by Django 5.0.14 on 2026-08-05 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('title', models.CharField(max_length=200, verbose_name='اللقب الوظيفي')),
                ('qualification', models.CharField(blank=True, max_length=150, verbose_name='المؤهل')),
                ('specialization', models.CharField(blank=True, max_length=150, verbose_name='التخصص')),
                ('summary', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
                ('message', models.TextField(blank=True, verbose_name='كلمة المدير')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='director/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بيانات المدير القومي',
                'verbose_name_plural': 'بيانات المدير القومي',
            },
        ),
    ]
