# Generated by Django 5.0.14 on 2026-08-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_directorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'بيانات المدير القومي', 'verbose_name_plural': 'بيانات المدير القومي'},
        ),
    ]
