# Generated by Django 5.0.14 on 2026-08-27 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_directorprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('OFFICIAL', 'رسمي'), ('HEALTH', 'صحي'), ('ADMIN', 'إداري'), ('TRAVEL', 'سفر'), ('OTHER', 'أخرى')], default='OFFICIAL', max_length=20, verbose_name='الفئة')),
                ('priority', models.CharField(choices=[('NORMAL', 'عادي'), ('IMPORTANT', 'مهم'), ('URGENT', 'عاجل')], default='NORMAL', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'مراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم المرجعي')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النشر')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='الكاتب')),
                ('reviewer', models.CharField(blank=True, max_length=150, verbose_name='المراجع')),
                ('approver', models.CharField(blank=True, max_length=150, verbose_name='المعتمد')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='circulars/%Y/%m/', verbose_name='المرفق')),
            ],
            options={
                'verbose_name': 'تعميم',
                'verbose_name_plural': 'التعاميم',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='approver',
            field=models.CharField(blank=True, max_length=150, verbose_name='المعتمد'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=150, verbose_name='الكاتب'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reviewer',
            field=models.CharField(blank=True, max_length=150, verbose_name='المراجع'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'مراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=20, verbose_name='الحالة'),
        ),
    ]
