# Generated by Django 5.0.14 on 2026-08-31 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_circular_newsarticle_approver_newsarticle_author_and_more'),
        ('organization', '0004_station_orgassignment_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='الملف')),
                ('kind', models.CharField(choices=[('image', 'صورة'), ('document', 'وثيقة'), ('video', 'فيديو')], default='image', max_length=20, verbose_name='النوع')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='الحجم')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'الوسائط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('subtitle_ar', models.CharField(blank=True, max_length=500, verbose_name='الوصف بالعربية')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, verbose_name='الوصف بالإنجليزية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders/%Y/%m/', verbose_name='الصورة')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='نص الزر')),
                ('button_link', models.CharField(blank=True, max_length=500, verbose_name='رابط الزر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شريحة دعائية',
                'verbose_name_plural': 'الشرائح الدعائية',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='circular',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_circulars', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AddField(
            model_name='cmsdocument',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_documents', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_faq', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='عاجل'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='الكلمات المفتاحية'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_news', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='الرابط المختصر'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, verbose_name='الملخص'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='page',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_settings', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=100, verbose_name='المفتاح'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('slug', 'sector'), name='unique_page_slug_sector'),
        ),
        migrations.AddConstraint(
            model_name='sitesetting',
            constraint=models.UniqueConstraint(fields=('key', 'sector'), name='unique_site_setting_key_sector'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_media', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_uploads', to=settings.AUTH_USER_MODEL, verbose_name='رافع الملف'),
        ),
        migrations.AddField(
            model_name='slider',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_sliders', to='organization.sector', verbose_name='القطاع الإداري'),
        ),
    ]
