# Generated by Django 5.0.14 on 2026-08-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_mediaitem_slider_circular_sector_cmsdocument_sector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['key'], 'verbose_name': 'إعداد موقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
    ]
