# Generated by Django 6.1 on 2026-09-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_sitesetting_options'),
        ('organization', '0007_sector_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorprofile',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً للمدير القومي العام، أو اختر قطاعاً للمدير الخاص بذلك القطاع.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_profiles', to='organization.sector', verbose_name='القطاع'),
        ),
    ]
