# Generated by Django 5.0.14 on 2026-09-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_directorprofile_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorprofile',
            name='confirmation_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة حالة الاعتماد'),
        ),
        migrations.AddField(
            model_name='directorprofile',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='معتمد رسمياً'),
        ),
    ]
