# Generated by Django 6.1 on 2026-09-10 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_directorprofile_confirmation_note_and_more'),
        ('organization', '0007_sector_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='العنوان بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='الرابط المختصر')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('priority', models.CharField(choices=[('NORMAL', 'عادي'), ('IMPORTANT', 'مهم'), ('URGENT', 'عاجل')], default='NORMAL', max_length=20, verbose_name='الأولوية')),
                ('audience', models.JSONField(blank=True, default=list, verbose_name='الجمهور المستهدف')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية الظهور')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الظهور')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'مراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النشر')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='الكاتب')),
                ('reviewer', models.CharField(blank=True, max_length=150, verbose_name='المراجع')),
                ('approver', models.CharField(blank=True, max_length=150, verbose_name='المعتمد')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_announcements', to='organization.sector', verbose_name='القطاع الإداري')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات والتنبيهات',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
    ]
