# Generated by Django 5.0.14 on 2026-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='الكود'),
        ),
    ]
