# Generated by Django 5.0.14 on 2026-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_fee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('QUARANTINE', 'رسوم الحجر الصحي'), ('FOOD_CONTROL', 'رقابة الأغذية'), ('INSPECTION', 'التفتيش'), ('SAMPLING', 'أخذ العينات'), ('LAB', 'المختبر'), ('CERTIFICATE', 'الشهادات'), ('PEST_CONTROL', 'مكافحة النواقل'), ('OTHER', 'خدمات أخرى')], max_length=20, verbose_name='نوع الخدمة'),
        ),
    ]
