# Generated by Django 5.0.14 on 2026-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_reconciliation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('ISSUED', 'صادرة'), ('PENDING_PAYMENT', 'بانتظار الدفع'), ('PARTIAL', 'مسددة جزئياً'), ('PAID', 'مدفوعة'), ('RECONCILED', 'تسويت'), ('CANCELLED', 'ملغاة'), ('REFUNDED', 'مسترَدّة'), ('OVERDUE', 'متأخرة')], default='DRAFT', max_length=20, verbose_name='الحالة'),
        ),
    ]
