# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('RED_ALERT', 'إنذار أحمر'), ('OUTBREAK', 'تفشٍ')], max_length=30, verbose_name='النوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('location_geo', models.JSONField(blank=True, default=dict, verbose_name='الموقع الجغرافي')),
                ('status', models.CharField(choices=[('NEW', 'جديد'), ('PROCESSING', 'قيد المعالجة'), ('RESOLVED', 'تم الحل')], default='NEW', max_length=20, verbose_name='الحالة')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإطلاق')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنهاء')),
            ],
            options={
                'verbose_name': 'إنذار طوارئ',
                'verbose_name_plural': 'إنذارات الطوارئ',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الحدث')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('event_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الحدث')),
                ('source_type', models.CharField(choices=[('SCREENING', 'فحص'), ('LAB', 'مختبر'), ('CLINIC', 'عيادة'), ('PUBLIC', 'عام'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='المصدر')),
                ('source_id', models.UUIDField(blank=True, null=True, verbose_name='معرف المصدر')),
                ('severity', models.CharField(choices=[('LOW', 'منخفض'), ('MODERATE', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='MODERATE', max_length=20, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'تم التحديد'), ('VERIFIED', 'تم التحقق'), ('RESPONDING', 'قيد الاستجابة'), ('CONTROLLED', 'تحت السيطرة'), ('CLOSED', 'مغلق'), ('REJECTED', 'مرفوض')], default='IDENTIFIED', max_length=20, verbose_name='الحالة')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البلاغ')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='الدروس المستفادة')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
            ],
            options={
                'verbose_name': 'حدث طوارئ',
                'verbose_name_plural': 'أحداث الطوارئ',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='KillSwitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(verbose_name='السبب')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التفعيل')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
            ],
            options={
                'verbose_name': 'مفتاح إيقاف',
                'verbose_name_plural': 'مفاتيح الإيقاف',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponsePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='الخطوات')),
                ('required_resources', models.JSONField(blank=True, default=dict, verbose_name='الموارد المطلوبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خطة استجابة',
                'verbose_name_plural': 'خطط الاستجابة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrisisTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('INCIDENT_COMMANDER', 'قائد الحادث'), ('LOGISTICS', 'اللوجستيات'), ('MEDICAL_TEAM', 'فريق طبي'), ('COMMUNICATIONS', 'الاتصالات')], max_length=30, verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crisis_roles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عضو فريق أزمة',
                'verbose_name_plural': 'أعضاء فريق الأزمات',
            },
        ),
    ]
