# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency_eoc', '0001_initial'),
        ('ports', '0001_initial'),
        ('travelers', '0002_country_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ports.port', verbose_name='المنفذ'),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='travelers.traveler', verbose_name='المسافر'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='affected_travelers',
            field=models.ManyToManyField(blank=True, related_name='emergency_events', to='travelers.traveler', verbose_name='المسافرون المتأثرون'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='location_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='ports.port', verbose_name='المنفذ'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_events', to=settings.AUTH_USER_MODEL, verbose_name='المُبلغ'),
        ),
        migrations.AddField(
            model_name='crisisteammember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='emergency_eoc.emergencyevent', verbose_name='الحدث'),
        ),
        migrations.AddField(
            model_name='killswitch',
            name='activated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kill_switches', to=settings.AUTH_USER_MODEL, verbose_name='مفعل من'),
        ),
        migrations.AddField(
            model_name='killswitch',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_switches', to='ports.port', verbose_name='المنفذ'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='response_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='emergency_eoc.responseplan', verbose_name='خطة الاستجابة'),
        ),
        migrations.AlterUniqueTogether(
            name='crisisteammember',
            unique_together={('event', 'user', 'role')},
        ),
    ]
