# Generated by Django 5.0.14 on 2026-07-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_eoc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyevent',
            name='event_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='رقم الحدث'),
        ),
    ]
