# Generated by Django 5.0.14 on 2026-08-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_bridge_to_entrypoint'),
        ('emergency_eoc', '0003_alter_emergencyevent_event_number'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='masterdata.entrypoint', verbose_name='المنفذ'),
        ),
        migrations.AlterField(
            model_name='emergencyevent',
            name='location_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='masterdata.entrypoint', verbose_name='المنفذ'),
        ),
        migrations.AlterField(
            model_name='killswitch',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_switches', to='masterdata.entrypoint', verbose_name='المنفذ'),
        ),
    ]
