# Generated by Django 5.0.14 on 2026-07-31 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(choices=[('GREEN', 'أخضر'), ('YELLOW', 'أصفر'), ('RED', 'أحمر')], max_length=10, verbose_name='مستوى الخطر')),
                ('risk_score', models.FloatField(verbose_name='درجة الخطر')),
                ('decision_factors', models.JSONField(blank=True, default=dict, verbose_name='عوامل القرار')),
                ('recommendation', models.CharField(choices=[('ADMIT', 'إفراج'), ('QUARANTINE', 'حجر صحي'), ('REFER', 'إحالة')], max_length=20, verbose_name='التوصية')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التقييم')),
            ],
            options={
                'verbose_name': 'تقييم مخاطر',
                'verbose_name_plural': 'تقييمات المخاطر',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temp_weight', models.FloatField(default=1.0, verbose_name='وزن درجة الحرارة')),
                ('spo2_weight', models.FloatField(default=1.0, verbose_name='وزن الأكسجين')),
                ('symptom_weight', models.FloatField(default=5.0, verbose_name='وزن الأعراض')),
                ('origin_weight', models.FloatField(default=1.0, verbose_name='وزن المنشأ')),
                ('vaccine_weight', models.FloatField(default=1.0, verbose_name='وزن التطعيم')),
                ('yellow_threshold', models.FloatField(default=15.0, verbose_name='حد الأصفر')),
                ('red_threshold', models.FloatField(default=30.0, verbose_name='حد الأحمر')),
                ('red_temp_threshold', models.FloatField(default=39.0, verbose_name='حد الحرارة الأحمر')),
                ('red_spo2_threshold', models.FloatField(default=93.0, verbose_name='حد الأكسجين الأحمر')),
            ],
            options={
                'verbose_name': 'إعدادات تقييم المخاطر',
                'verbose_name_plural': 'إعدادات تقييم المخاطر',
            },
        ),
    ]
