# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_engine', '0001_initial'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='screening',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='screening.healthscreening', verbose_name='الفحص'),
        ),
    ]
