# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelers', '0002_country_risk_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('type', models.CharField(choices=[('AIRPORT', 'مطار'), ('SEAPORT', 'ميناء بحري'), ('LAND_PORT', 'منفذ بري')], max_length=20, verbose_name='النوع')),
                ('location_geo', models.JSONField(blank=True, default=dict, verbose_name='الموقع الجغرافي')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ports', to='travelers.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'منفذ',
                'verbose_name_plural': 'المنافذ',
                'ordering': ['code'],
            },
        ),
    ]
