# Generated by Django 5.0.14 on 2026-07-31 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='public.sector', verbose_name='القطاع'),
        ),
    ]
