# Generated by Django 5.0.14 on 2026-09-15 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0007_merge_sdpor_to_ep_port_sudan'),
        ('travelers', '0004_traveler_medical_file_no_traveler_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('who_code', models.CharField(blank=True, max_length=40, verbose_name='كود منظمة الصحة العالمي')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('route', models.CharField(choices=[('ORAL', 'فموي'), ('INJECTION', 'حقن'), ('INTRANASAL', 'بخاخ أنفي'), ('OTHER', 'أخرى')], default='INJECTION', max_length=15, verbose_name='طريق الإعطاء')),
                ('series', models.PositiveSmallIntegerField(default=1, verbose_name='عدد جرعات السلسلة الأولية')),
                ('booster_required', models.BooleanField(default=False, verbose_name='يتطلب جرعة تنشيطية')),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='الفاصل بين الجرعات (يوم)')),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة صلاحية الشهادة (يوم)')),
                ('required', models.BooleanField(default=False, verbose_name='إلزامي للسفر')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'لقاح',
                'verbose_name_plural': 'اللقاحات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=40, unique=True, verbose_name='رقم الشهادة')),
                ('status', models.CharField(choices=[('ACTIVE', 'سارية'), ('REVOKED', 'ملغاة'), ('EXPIRED', 'منتهية')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإصدار')),
                ('valid_until', models.DateField(verbose_name='صالحة حتى')),
                ('validity_days', models.PositiveIntegerField(default=0, verbose_name='مدة الصلاحية (يوم)')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='رمز التحقق')),
                ('verification_path', models.CharField(blank=True, max_length=200, verbose_name='مسار التحقق')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_vaccination_certificates', to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_certificates', to='travelers.traveler', verbose_name='المسافر')),
            ],
            options={
                'verbose_name': 'شهادة تطعيم دولية',
                'verbose_name_plural': 'شهادات التطعيم الدولية',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True, verbose_name='نتيجة التحقق')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_certificate_verifications', to=settings.AUTH_USER_MODEL, verbose_name='تحقق بواسطة')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='vaccination.vaccinationcertificate', verbose_name='الشهادة')),
            ],
            options={
                'verbose_name': 'عملية تحقق',
                'verbose_name_plural': 'عمليات التحقق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_type', models.CharField(choices=[('FIRST', 'الجرعة الأولى'), ('SECOND', 'الجرعة الثانية'), ('THIRD', 'الجرعة الثالثة'), ('BOOSTER', 'جرعة تنشيطية')], default='FIRST', max_length=10, verbose_name='نوع الجرعة')),
                ('dose_number', models.PositiveSmallIntegerField(default=1, verbose_name='رقم الجرعة')),
                ('administered_at', models.DateField(verbose_name='تاريخ التطعيم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('GIVEN', 'مُعطاة'), ('CANCELLED', 'ملغاة')], default='GIVEN', max_length=10, verbose_name='الحالة')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_recorded', to=settings.AUTH_USER_MODEL, verbose_name='سجّل بواسطة')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='travelers.traveler', verbose_name='المسافر')),
                ('vaccinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_administered', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب/المطعّم')),
            ],
            options={
                'verbose_name': 'سجل تطعيم',
                'verbose_name_plural': 'سجلات التطعيم',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationcertificate',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='vaccination.vaccinationrecord', verbose_name='الجرعة'),
        ),
        migrations.CreateModel(
            name='VaccinationSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('kind', models.CharField(choices=[('CLINIC', 'عيادة تطعيم'), ('PORT_POINT', 'نقطة تطعيم بمنفذ')], default='CLINIC', max_length=15, verbose_name='النوع')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_sites', to='masterdata.entrypoint', verbose_name='منفذ الدخول')),
            ],
            options={
                'verbose_name': 'عيادة تطعيم',
                'verbose_name_plural': 'عيادات التطعيم',
                'ordering': ['name_ar'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vaccination.vaccinationsite', verbose_name='المكان'),
        ),
        migrations.CreateModel(
            name='VaccinationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ar', models.CharField(max_length=150, verbose_name='العنوان بالعربية')),
                ('destination_region', models.CharField(blank=True, max_length=100, verbose_name='منطقة الوجهة')),
                ('min_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='أدنى عمر (يوم)')),
                ('max_age_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='أقصى عمر (يوم)')),
                ('required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('doses_required', models.PositiveSmallIntegerField(default=1, verbose_name='الجرعات المطلوبة')),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الصلاحية (يوم)')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vaccination.vaccine', verbose_name='اللقاح')),
            ],
            options={
                'verbose_name': 'قاعدة تطعيم',
                'verbose_name_plural': 'قواعد التطعيم',
                'ordering': ['vaccine__name_ar'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='vaccination.vaccine', verbose_name='اللقاح'),
        ),
        migrations.AddField(
            model_name='vaccinationcertificate',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccination.vaccine', verbose_name='اللقاح'),
        ),
        migrations.CreateModel(
            name='VaccineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=60, unique=True, verbose_name='رقم التشغيلة LOT')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='المُصنّع')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التصنيع')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('status', models.CharField(choices=[('ACTIVE', 'متاحة'), ('DEPLETED', 'نفدت'), ('EXPIRED', 'منتهية الصلاحية'), ('RETURNED', 'مرتجعة')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='vaccination.vaccine', verbose_name='اللقاح')),
            ],
            options={
                'verbose_name': 'تشغيلة لقاح',
                'verbose_name_plural': 'تشغيلات اللقاح',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vaccination.vaccinebatch', verbose_name='التشغيلة'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('IN', 'استلام'), ('OUT', 'صرف'), ('ADJUST', 'تسوية'), ('EXPIRED', 'انتهاء صلاحية')], max_length=10, verbose_name='النوع')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('reference_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='vaccination.vaccinationrecord', verbose_name='الجرعة المرتبطة')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vaccination.vaccinebatch', verbose_name='التشغيلة')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
    ]
