# Generated by Django 5.0.14 on 2026-10-05 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcertificate',
            name='replaces',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                db_index=True,
                related_name='replacement_chain',
                to='vaccination.VaccinationCertificate',
                verbose_name='الشهادة الأصل',
            ),
        ),
        migrations.AddField(
            model_name='vaccinationcertificate',
            name='replacement_reason',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                null=True,
                verbose_name='سبب الاستبدال',
            ),
        ),
        migrations.AddField(
            model_name='vaccinationcertificate',
            name='replaced_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='تاريخ الاستبدال',
            ),
        ),
    ]