# Generated by Django 5.0.14 on 2026-10-06 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_certificate_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('ISSUE', 'إصدار'), ('REPLACE', 'استبدال'), ('REISSUE', 'إعادة إصدار'), ('REVOKE', 'إلغاء')], max_length=20, verbose_name='الإجراء')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='vaccination.vaccinationcertificate', verbose_name='الشهادة')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_audit_logs', to='vaccination.vaccinationrecord', verbose_name='الجرعة')),
                ('source_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_audit_logs', to='vaccination.vaccinationcertificate', verbose_name='الشهادة الأصل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تدقيق حياة الشهادة',
                'verbose_name_plural': 'تدقيق دورة حياة الشهادات',
                'ordering': ['-created_at'],
            },
        ),
    ]
