# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest_number', models.CharField(max_length=50, unique=True, verbose_name='رقم البيان')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('origin_country', models.CharField(max_length=100, verbose_name='دولة المنشأ')),
                ('product_list', models.JSONField(blank=True, default=list, verbose_name='قائمة المنتجات')),
                ('arrival_date', models.DateField(verbose_name='تاريخ الوصول')),
                ('shipment_type', models.CharField(choices=[('IMPORT', 'وارد'), ('EXPORT', 'صادر')], default='IMPORT', max_length=10, verbose_name='النوع')),
                ('status', models.CharField(choices=[('RECEIVED', 'تم الاستلام'), ('UNDER_INSPECTION', 'قيد التفتيش'), ('AWAITING_LAB_RESULTS', 'بانتظار النتائج'), ('RELEASED', 'تم الإفراج'), ('REJECTED', 'مرفوض')], default='RECEIVED', max_length=25, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'شحنة غذائية',
                'verbose_name_plural': 'الشحنات الغذائية',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='FoodInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_notes', models.JSONField(blank=True, default=dict, verbose_name='ملاحظات التفتيش')),
                ('decision', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], max_length=20, verbose_name='القرار')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التفتيش')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_inspections', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
            ],
            options={
                'verbose_name': 'تفتيش غذائي',
                'verbose_name_plural': 'التفتيش الغذائي',
            },
        ),
        migrations.CreateModel(
            name='FoodReleaseCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('certificate_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الشهادة')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_certificates', to=settings.AUTH_USER_MODEL, verbose_name='المُصدر')),
            ],
            options={
                'verbose_name': 'شهادة إفراج غذائي',
                'verbose_name_plural': 'شهادات الإفراج الغذائي',
            },
        ),
        migrations.CreateModel(
            name='FoodSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_barcode', models.CharField(max_length=50, unique=True, verbose_name='باركود العينة')),
                ('sample_type', models.CharField(max_length=30, verbose_name='نوع العينة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد التحليل'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='food_quarantine.foodinspection', verbose_name='التفتيش')),
            ],
            options={
                'verbose_name': 'عينة غذائية',
                'verbose_name_plural': 'العينات الغذائية',
                'ordering': ['-created_at'],
            },
        ),
    ]
