# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_quarantine', '0001_initial'),
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshipment',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_shipments', to='ports.port', verbose_name='المنفذ'),
        ),
        migrations.AddField(
            model_name='foodreleasecertificate',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_certificate', to='food_quarantine.foodshipment', verbose_name='الشحنة'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='food_quarantine.foodshipment', verbose_name='الشحنة'),
        ),
    ]
