# Generated by Django 5.0.14 on 2026-08-06 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('bench', models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='MICROBIOLOGY', max_length=20, verbose_name='المختبر')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('method', models.CharField(blank=True, max_length=255, verbose_name='الطريقة')),
                ('reference_limit', models.CharField(blank=True, max_length=100, verbose_name='الحد المرجعي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'معامل تحليل',
                'verbose_name_plural': 'معاملات التحليل',
                'ordering': ['bench', 'order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='foodsample',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'قيد الاعتماد'), ('APPROVED', 'معتمد')], default='PENDING', max_length=20, verbose_name='حالة الاعتماد'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='bench',
            field=models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='MICROBIOLOGY', max_length=20, verbose_name='المختبر'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='موظف الاستقبال'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='reported_to_food_safety',
            field=models.BooleanField(default=False, verbose_name='أُرسلت نتائجها لنظام الرقابة الغذائية'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='sample_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='الرقم المرجعي'),
        ),
        migrations.AlterField(
            model_name='foodsample',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'تم الاستلام'), ('UNDER_TESTING', 'قيد التحليل'), ('COMPLETED', 'مكتملة'), ('REJECTED', 'مرفوضة')], default='RECEIVED', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='AnalysisCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('decision', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], max_length=20, verbose_name='القرار')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص النتائج')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ISSUED', 'صادر')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_analysis_certificates', to=settings.AUTH_USER_MODEL, verbose_name='المُصدر')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='food_quarantine.foodsample', verbose_name='العينة')),
            ],
            options={
                'verbose_name': 'شهادة تحليل',
                'verbose_name_plural': 'شهادات التحليل',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'قيد التنفيذ'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('result_value', models.FloatField(blank=True, null=True, verbose_name='قيمة النتيجة')),
                ('result_text', models.CharField(blank=True, max_length=100, verbose_name='النتيجة النصية')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('reference_limit', models.CharField(blank=True, max_length=100, verbose_name='الحد المرجعي')),
                ('decision', models.CharField(choices=[('PENDING', 'غير محسوم'), ('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق')], default='PENDING', max_length=20, verbose_name='القرار')),
                ('entered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإدخال')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنجاز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول التنفيذ')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_food_results', to=settings.AUTH_USER_MODEL, verbose_name='مدخل النتيجة')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_tests', to='food_quarantine.labparameter', verbose_name='المعامل')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='food_quarantine.foodsample', verbose_name='العينة')),
            ],
            options={
                'verbose_name': 'فحص مخبري',
                'verbose_name_plural': 'الفحوصات المخبرية',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sampletest',
            constraint=models.UniqueConstraint(fields=('sample', 'parameter'), name='unique_sample_parameter_test'),
        ),
    ]
