# Generated by Django 5.0.14 on 2026-08-07 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0003_labparameter_foodsample_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('fee_type', models.CharField(choices=[('INSPECTION', 'تفتيش'), ('SAMPLE', 'عينة'), ('ANALYSIS', 'تحليل'), ('CERTIFICATE', 'شهادة'), ('ADMIN', 'رسوم إدارية')], max_length=20, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بند رسوم',
                'verbose_name_plural': 'بنود الرسوم',
                'ordering': ['fee_type', 'amount'],
            },
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التعيين'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='assigned_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_food_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المفتش المعيّن'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_food_shipments', to=settings.AUTH_USER_MODEL, verbose_name='مُصدر القرار النهائي'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='decision_reason',
            field=models.TextField(blank=True, verbose_name='سبب القرار'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='fees_paid',
            field=models.BooleanField(default=False, verbose_name='الرسوم المسددة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('COMPLIANT', 'يتم الإفراج'), ('CONDITIONAL_RELEASE', 'إفراج مشروط'), ('REJECTED', 'رفض الشحنة'), ('HOLD', 'حجز الشحنة'), ('RE_EXPORT', 'إعادة تصدير'), ('DESTROY', 'إتلاف')], max_length=25, verbose_name='القرار النهائي'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_food_shipments', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب المسجّل'),
        ),
        migrations.AlterField(
            model_name='foodshipment',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'تم الاستلام'), ('FEES_DUE', 'مستحقة الرسوم'), ('AWAITING_INSPECTION', 'بانتظار التفتيش'), ('UNDER_INSPECTION', 'قيد التفتيش'), ('AWAITING_LAB_RESULTS', 'بانتظار النتائج'), ('AWAITING_DECISION', 'بانتظار القرار'), ('RELEASED', 'تم الإفراج'), ('CONDITIONAL_RELEASE', 'إفراج مشروط'), ('REJECTED', 'مرفوض'), ('HOLD', 'محجوزة'), ('RE_EXPORT', 'إعادة تصدير'), ('DESTROYED', 'إتلاف')], default='RECEIVED', max_length=25, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='FoodDecisionCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('certificate_type', models.CharField(choices=[('RELEASED', 'شهادة الإفراج'), ('CONDITIONAL_RELEASE', 'شهادة إفراج مشروط'), ('REJECTED', 'شهادة الرفض'), ('HOLD', 'شهادة الحجز'), ('RE_EXPORT', 'شهادة إعادة التصدير'), ('DESTROY', 'شهادة الإتلاف')], max_length=25, verbose_name='نوع الشهادة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ISSUED', 'صادرة')], default='ISSUED', max_length=10, verbose_name='الحالة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإصدار')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('certificate_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الشهادة')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_shipment_decision_certificates', to=settings.AUTH_USER_MODEL, verbose_name='المُصدر')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_certificates', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'شهادة قرار نهائي',
                'verbose_name_plural': 'شهادات القرار النهائي',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('items', models.JSONField(default=list, verbose_name='بنود الفاتورة')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('PENDING', 'معلقة'), ('PAID', 'مدفوعة')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإصدار')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_food_invoices', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب/المحاسب المُصدر')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_food_payments', to=settings.AUTH_USER_MODEL, verbose_name='المحاسب المستلم')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'فاتورة رسوم',
                'verbose_name_plural': 'فواتير الرسوم',
                'ordering': ['-created_at'],
            },
        ),
    ]
