# Generated by Django 5.0.14 on 2026-08-07 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0004_foodfee_foodshipment_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshipment',
            name='referral_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع الإحالة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='referred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإحالة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_food_shipments', to=settings.AUTH_USER_MODEL, verbose_name='مُحيل الشحنة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='referred_from',
            field=models.CharField(blank=True, choices=[('LAND_BORDER_HEALTH', 'نظام الحجر الصحي للمعابر البرية'), ('PORT_HEALTH', 'نظام الحجر الصحي للموانئ'), ('AIRPORT_HEALTH', 'نظام الحجر الصحي للمطارات')], max_length=30, verbose_name='مصدر الإحالة'),
        ),
    ]
