# Generated by Django 5.0.14 on 2026-08-09 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0005_foodshipment_referral_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('scope', models.CharField(choices=[('IMPORT', 'وارد'), ('EXPORT', 'صادر'), ('BOTH', 'كلاهما')], default='BOTH', max_length=20, verbose_name='نطاق الشحنة')),
                ('benchmark', models.CharField(choices=[('WEIGHT', 'بالوزن'), ('PACKAGES', 'بعدد العبوات')], default='WEIGHT', max_length=20, verbose_name='الأساس')),
                ('threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الحد الأدنى')),
                ('samples_per_unit', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='عدد عينات لكل وحدة')),
                ('max_samples', models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى للعينات')),
                ('default_reason', models.CharField(choices=[('ROUTINE', 'روتيني'), ('SUSPECTED', 'اشتباه فساد'), ('FIRST_ENTRY', 'أول ورود')], default='ROUTINE', max_length=20, verbose_name='السبب الافتراضي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سياسة عينات',
                'verbose_name_plural': 'سياسات العينات',
                'ordering': ['order', 'threshold'],
            },
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم التشغيلة'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='container_condition',
            field=models.CharField(blank=True, max_length=100, verbose_name='حالة الماعون'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='container_status',
            field=models.CharField(blank=True, max_length=150, verbose_name='حالة الحاوية'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='damaged_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد العبوات التالفة'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='damaged_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الوزن التالف'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='package_condition',
            field=models.CharField(blank=True, max_length=150, verbose_name='حالة العبوات'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإنتاج'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='sound_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد العبوات السليمة'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='sound_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الوزن السليم'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الحرارة'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='sampling_reason',
            field=models.CharField(choices=[('ROUTINE', 'روتيني'), ('SUSPECTED', 'اشتباه فساد'), ('FIRST_ENTRY', 'أول ورود')], default='ROUTINE', max_length=20, verbose_name='سبب أخذ العينة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='bill_of_lading',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم البوليصة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم شهادة الاعتماد'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='clearing_agent',
            field=models.CharField(blank=True, max_length=150, verbose_name='المخلّص الجمركي'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='customs_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الجمركي'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='exporter_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المُصدِّر (للمصدر)'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='inspection_required',
            field=models.BooleanField(default=True, verbose_name='يلزم التفتيش'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='loading_port',
            field=models.CharField(blank=True, max_length=150, verbose_name='ميناء الشحن'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='message_type',
            field=models.CharField(choices=[('COMMERCIAL', 'تجارية'), ('RELIEF', 'إغاثة'), ('EXEMPT', 'إعفاء')], default='COMMERCIAL', max_length=20, verbose_name='نوع الرسالة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='samples_required',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد العينات المطلوبة'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إحالة الطلب'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الوزن الإجمالي (كغ)'),
        ),
        migrations.AddField(
            model_name='foodshipment',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم الباخرة'),
        ),
        migrations.AlterField(
            model_name='foodinspection',
            name='decision',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NEEDS_ANALYSIS', 'يحتاج تحليل')], max_length=20, verbose_name='القرار'),
        ),
        migrations.AlterField(
            model_name='foodshipment',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('COMPLIANT', 'يتم الإفراج'), ('CONDITIONAL_RELEASE', 'إفراج مشروط'), ('PARTIAL_RELEASE', 'إفراج جزئي'), ('TEMPORARY_RELEASE', 'إفراج مؤقت'), ('REJECTED', 'رفض الشحنة'), ('HOLD', 'حجز الشحنة'), ('RE_EXPORT', 'إعادة تصدير'), ('TRANSFER', 'تحويل الشحنة'), ('DESTROY', 'إتلاف')], max_length=25, verbose_name='القرار النهائي'),
        ),
        migrations.AlterField(
            model_name='foodshipment',
            name='referred_from',
            field=models.CharField(blank=True, choices=[('LAND_BORDER_HEALTH', 'نظام الحجر الصحي للمعابر الحدية'), ('PORT_HEALTH', 'نظام الحجر الصحي للموانئ'), ('AIRPORT_HEALTH', 'نظام الحجر الصحي للمطارات')], max_length=30, verbose_name='مصدر الإحالة'),
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='الماركة')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='المنشأ')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الوزن (كغ)')),
                ('package_count', models.PositiveIntegerField(default=0, verbose_name='عدد العبوات')),
                ('package_type', models.CharField(blank=True, max_length=100, verbose_name='نوع العبوة')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'صنف طلب',
                'verbose_name_plural': 'أصناف الطلبات',
                'ordering': ['created_at'],
            },
        ),
    ]
