# Generated by Django 5.0.14 on 2026-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0006_samplingpolicy_foodinspection_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingpolicy',
            name='package_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='حجم العبوة'),
        ),
        migrations.AddField(
            model_name='samplingpolicy',
            name='product_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='اسم الصنف (للمطابقة الرسمية)'),
        ),
        migrations.AddField(
            model_name='samplingpolicy',
            name='quantity',
            field=models.CharField(blank=True, max_length=30, verbose_name='كمية العينة (نص)'),
        ),
        migrations.AddField(
            model_name='samplingpolicy',
            name='quantity_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عدد وحدات العينة'),
        ),
        migrations.AddField(
            model_name='samplingpolicy',
            name='rate_pct',
            field=models.PositiveIntegerField(default=0, verbose_name='نسبة سحب الرسائل (100/75/25)'),
        ),
        migrations.AddField(
            model_name='samplingpolicy',
            name='risk_group',
            field=models.CharField(blank=True, choices=[('R1', 'المجموعة الأولى (خطورة عالية — 100%)'), ('R2', 'المجموعة الثانية (خطورة متوسطة — 75%)'), ('R3', 'المجموعة الثالثة (خطورة منخفضة — 25%)')], max_length=2, verbose_name='مجموعة المخاطر'),
        ),
        migrations.AddField(
            model_name='samplingpolicy',
            name='sampling_conditions',
            field=models.TextField(blank=True, verbose_name='شروط السحب'),
        ),
    ]
