# Generated by Django 5.0.14 on 2026-08-10 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0007_samplingpolicy_package_size_and_more'),
        ('travelers', '0003_alter_traveler_registration_status_travelerstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='الشركة المصنّعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'ماركة (سجل)',
                'verbose_name_plural': 'قائمة الماركات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ClearingAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم')),
                ('license_no', models.CharField(blank=True, max_length=100, verbose_name='رقم الترخيص')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='بيانات الاتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مخلّص جمركي (سجل)',
                'verbose_name_plural': 'قائمة المخلّصين',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Conveyance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='الاسم/الوصف')),
                ('conveyance_type', models.CharField(choices=[('SHIP', 'باخرة'), ('TRUCK', 'شاحنة'), ('REFRIGERATED_TRUCK', 'براد'), ('RAILCART', 'عربة قطار'), ('PLANE', 'طائرة شحن'), ('CONTAINER', 'حاوية'), ('TANKER', 'تنكر'), ('OTHER', 'أخرى')], default='OTHER', max_length=25, verbose_name='النوع')),
                ('registration_no', models.CharField(blank=True, max_length=100, verbose_name='رقم التسجيل')),
                ('capacity', models.CharField(blank=True, max_length=100, verbose_name='السعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وِعاء (سجل)',
                'verbose_name_plural': 'قائمة المواعين',
                'ordering': ['conveyance_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=300, unique=True, verbose_name='اسم الصنف')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='التصنيف الرئيسي')),
                ('subcategory', models.CharField(blank=True, max_length=200, verbose_name='التصنيف الفرعي')),
                ('risk_group', models.CharField(blank=True, choices=[('R1', 'المجموعة الأولى (خطورة عالية — 100%)'), ('R2', 'المجموعة الثانية (خطورة متوسطة — 75%)'), ('R3', 'المجموعة الثالثة (خطورة منخفضة — 25%)')], max_length=2, verbose_name='مجموعة المخاطر')),
                ('reference_quantity', models.CharField(blank=True, max_length=30, verbose_name='كمية العينة المرجعية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'صنف (سجل)',
                'verbose_name_plural': 'قائمة الأصناف',
                'ordering': ['category', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='نوع العبوة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع عبوة',
                'verbose_name_plural': 'أنواع العبوات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='بيانات الاتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_exporters', to='travelers.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'مصدّر (سجل)',
                'verbose_name_plural': 'قائمة المصدّرين',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='بيانات الاتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_suppliers', to='travelers.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'مورّد (سجل)',
                'verbose_name_plural': 'قائمة المورّدين',
                'ordering': ['name_ar'],
            },
        ),
    ]
