# Generated by Django 5.0.14 on 2026-08-12 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0008_brand_clearingagent_conveyance_foodproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SHIP_INSPECTION', 'رسوم التفتيش الصحي للبواخر'), ('HEALTH_SERVICES', 'الخدمات الصحية'), ('VACCINATION', 'التطعيمات'), ('MEDICAL_FITNESS', 'اللياقة الطبية'), ('PEST_CONTROL', 'التفتيش والمكافحة'), ('CERTIFICATE', 'الشهادات'), ('VIOLATION', 'المخالفات'), ('FOOD_IMPORT', 'المواد الغذائية الواردة'), ('FOOD_EXPORT', 'المواد الغذائية الصادرة'), ('UNLOADING', 'رسوم الإنزالات'), ('MICRO_TEST', 'الفحوصات الميكروبية'), ('CHEMICAL_TEST', 'الفحوصات الكيميائية')], max_length=30, verbose_name='القسم')),
                ('name_ar', models.CharField(max_length=250, verbose_name='الاسم بالعربية')),
                ('amount_sdg', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الجنيه (SDG)')),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الدولار (USD)')),
                ('currency_note', models.CharField(blank=True, max_length=50, verbose_name='ملاحظة عملة')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='الكود')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='السنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بند تعرفة الكرنتينة',
                'verbose_name_plural': 'تعرفة رسوم الكرنتينة',
                'ordering': ['year', 'category', 'order', 'id'],
            },
        ),
    ]
