# Generated by Django 5.0.14 on 2026-08-15 19:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0009_quarantinefee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مصدر عينة',
                'verbose_name_plural': 'مصادر العينات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='foodsample',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='المحلل'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='classification',
            field=models.CharField(choices=[('REFERENCE', 'مرجعية'), ('ANALYSIS', 'للتحليل')], default='ANALYSIS', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='collection_status',
            field=models.CharField(choices=[('PENDING', 'غير محصّل'), ('PAID', 'محصّل'), ('EXEMPT', 'معفاة')], default='PENDING', max_length=20, verbose_name='حالة التحصيل'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='منسّق عينات المختبر'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='رئيس القسم'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='dispatch_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإرسال'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='موظف الإرسال'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رسوم التحليل'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='requesting_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='الجهة الطالبة'),
        ),
        migrations.AlterField(
            model_name='foodsample',
            name='bench',
            field=models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='MICROBIOLOGY', max_length=20, verbose_name='قسم المختبر'),
        ),
        migrations.AlterField(
            model_name='foodsample',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='food_quarantine.foodinspection', verbose_name='التفتيش'),
        ),
        migrations.AlterField(
            model_name='foodsample',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'تم الاستلام'), ('COORDINATED', 'تم التنسيق'), ('ASSIGNED', 'أُسندت للقسم'), ('UNDER_TESTING', 'قيد التحليل'), ('READY_FOR_APPROVAL', 'جاهزة للاعتماد'), ('APPROVED', 'معتمدة'), ('DISPATCHED', 'أُرسلت النتائج'), ('COMPLETED', 'مكتملة'), ('REJECTED', 'مرفوضة')], default='RECEIVED', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_department', models.CharField(max_length=120, verbose_name='من (القسم)')),
                ('to_department', models.CharField(max_length=120, verbose_name='إلى (القسم)')),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت النقل')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام')),
                ('condition', models.CharField(blank=True, max_length=200, verbose_name='حالة العينة')),
                ('seal_number', models.CharField(blank=True, max_length=120, verbose_name='رقم الختم')),
                ('remarks', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_received', models.BooleanField(default=False, verbose_name='تم الاستلام')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plus_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستلم')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='food_quarantine.foodsample', verbose_name='العينة')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_samples', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الناقل')),
            ],
            options={
                'verbose_name': 'حدث حيازة',
                'verbose_name_plural': 'سلسلة حيازة العينات',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم المرجعي')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المادة / العينة')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='المنشأ / الدفعة')),
                ('storage_location', models.CharField(blank=True, max_length=120, verbose_name='موقع التخزين')),
                ('coding', models.CharField(blank=True, max_length=120, verbose_name='الترميز')),
                ('seal_number', models.CharField(blank=True, max_length=120, verbose_name='رقم الختم')),
                ('condition_on_arrival', models.CharField(blank=True, max_length=200, verbose_name='حالة العينة عند الاستلام')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الاستلام')),
                ('status', models.CharField(choices=[('STORED', 'مخزنة'), ('RETRIEVED', 'تم الرجوع إليها'), ('DISCARDED', 'أُعدمت')], default='STORED', max_length=20, verbose_name='الحالة')),
                ('retrieved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرجوع')),
                ('remarks', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reference_samples', to=settings.AUTH_USER_MODEL, verbose_name='موظف الاستلام')),
                ('retrieved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieved_reference_samples', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي رجع إليها')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_samples', to='food_quarantine.samplesource', verbose_name='المصدر')),
            ],
            options={
                'verbose_name': 'عينة مرجعية',
                'verbose_name_plural': 'العينات المرجعية',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='foodsample',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_samples', to='food_quarantine.samplesource', verbose_name='مصدر العينة'),
        ),
    ]
