# Generated by Django 5.0.14 on 2026-08-15 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0010_samplesource_foodsample_analyst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsample',
            name='reception_decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت قرار الاستلام'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='reception_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_food_sample_reception', to=settings.AUTH_USER_MODEL, verbose_name='مُصدِّر قرار الاستلام'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='reception_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة قرار الاستلام'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='reception_status',
            field=models.CharField(choices=[('RECEIVED', 'تم الاستلام'), ('ACCEPTED', 'مقبولة'), ('CONDITIONALLY_ACCEPTED', 'قبول مشروط'), ('REJECTED', 'مرفوضة (الاستلام)')], default='RECEIVED', max_length=30, verbose_name='حالة الاستلام'),
        ),
        migrations.AddField(
            model_name='labparameter',
            name='detection_limit',
            field=models.CharField(blank=True, max_length=100, verbose_name='حد الكشف'),
        ),
        migrations.AddField(
            model_name='labparameter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر التحليل'),
        ),
        migrations.AddField(
            model_name='labparameter',
            name='sla_max_days',
            field=models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى للإنهاء (يوم)'),
        ),
        migrations.AddField(
            model_name='labparameter',
            name='sla_min_days',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للإنهاء (يوم)'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='مدير المختبر المُعتمِد'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='device_used',
            field=models.CharField(blank=True, max_length=255, verbose_name='الجهاز المستخدم'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='method_used',
            field=models.CharField(blank=True, max_length=255, verbose_name='طريقة الاختبار'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='reagent_lot',
            field=models.CharField(blank=True, max_length=120, verbose_name='رقم تشغيلة الكاشف'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='رئيس القسم المراجِع'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AlterField(
            model_name='sampletest',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'غير محسوم'), ('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('INCONCLUSIVE', 'غير حاسم'), ('NOT_APPLICABLE', 'لا ينطبق')], default='PENDING', max_length=20, verbose_name='القرار'),
        ),
        migrations.AlterField(
            model_name='sampletest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'قيد التنفيذ'), ('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسلة للمراجعة'), ('REVIEWED', 'راجعها رئيس القسم'), ('APPROVED', 'اعتمدها مدير المختبر'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='SampleInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='بنود الفاتورة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('currency', models.CharField(default='SDG', max_length=10, verbose_name='العملة')),
                ('status', models.CharField(choices=[('PENDING', 'معلقة'), ('PAID', 'مدفوعة'), ('EXEMPT', 'معفاة')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإصدار')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الإيصال')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('exemption_reason', models.TextField(blank=True, verbose_name='سبب الإعفاء')),
                ('exempted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإعفاء')),
                ('exempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exempted_sample_fees', to=settings.AUTH_USER_MODEL, verbose_name='موظف الإعفاء')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sample_invoices', to=settings.AUTH_USER_MODEL, verbose_name='مُصدِر الفاتورة')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_sample_payments', to=settings.AUTH_USER_MODEL, verbose_name='المحصل')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_invoice', to='food_quarantine.foodsample', verbose_name='العينة')),
            ],
            options={
                'verbose_name': 'فاتورة تحليل عينة',
                'verbose_name_plural': 'فواتير تحليل العينات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleTestRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(verbose_name='الإصدار السابق')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='لقطة القيم القديمة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_revisions', to=settings.AUTH_USER_MODEL, verbose_name='مُصدِّر التعديل')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='food_quarantine.sampletest', verbose_name='الفحص')),
            ],
            options={
                'verbose_name': 'نسخة نتيجة',
                'verbose_name_plural': 'نسخ النتائج',
                'ordering': ['-version'],
            },
        ),
    ]
