# Generated by Django 5.0.14 on 2026-08-15 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0011_foodsample_reception_decision_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobiologicalLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='وحدة القياس')),
                ('n', models.PositiveIntegerField(default=5, verbose_name='n — عدد وحدات العينة')),
                ('c', models.PositiveIntegerField(default=0, verbose_name='c — الحد الأقصى للوحدات بين m و M')),
                ('m', models.DecimalField(blank=True, db_column='m_limit', decimal_places=6, max_digits=20, null=True, verbose_name='m — الحد المقبول')),
                ('M', models.DecimalField(blank=True, db_column='Mmax', decimal_places=6, max_digits=20, null=True, verbose_name='M — الحد الأقصى')),
                ('plan', models.CharField(choices=[('TWO_CLASS', 'خطة من فئتين (2-Class)'), ('THREE_CLASS', 'خطة من ثلاث فئات (3-Class)'), ('PRESENCE_ABSENCE', 'حضور/غياب')], default='THREE_CLASS', max_length=20, verbose_name='نوع الخطة')),
                ('rule_json', models.JSONField(blank=True, default=dict, verbose_name='قواعد قابلة للتهيئة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حد ميكروبيولوجي',
                'verbose_name_plural': 'الحدود الميكروبيولوجية',
                'ordering': ['-version__version', 'microorganism__code'],
            },
        ),
        migrations.CreateModel(
            name='Microorganism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم العلمي')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('detection_type', models.CharField(choices=[('PRESENCE_ABSENCE', 'حضور/غياب'), ('QUANTITATIVE', 'كمّي')], default='QUANTITATIVE', max_length=20, verbose_name='نوع الكشف')),
                ('default_unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة الافتراضية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'كائن دقيق',
                'verbose_name_plural': 'الكائنات الدقيقة',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('reference_standard', models.CharField(blank=True, max_length=200, verbose_name='المرجع القياسي')),
                ('detection_limit', models.CharField(blank=True, max_length=100, verbose_name='حد الكشف')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة')),
                ('sample_quantity', models.CharField(blank=True, max_length=100, verbose_name='كمية العينة')),
                ('incubation_parameters', models.CharField(blank=True, max_length=255, verbose_name='شروط الحضانة/المعالجة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طريقة اختبار',
                'verbose_name_plural': 'طرق الاختبار',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='الكود'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التقييم الآلي'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='evaluation',
            field=models.CharField(blank=True, choices=[('PENDING', 'غير محسوم'), ('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('INCONCLUSIVE', 'غير حاسم'), ('NOT_APPLICABLE', 'لا ينطبق')], help_text='قرار محرك التقييم الآلي وفق المواصفة (n/c/m/M)', max_length=20, verbose_name='التقييم الآلي'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='evaluation_reason',
            field=models.TextField(blank=True, verbose_name='سبب التقييم الآلي'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='spec_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='لقطة المواصفة المعتمدة وقت التحليل'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='micro_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='food_quarantine.microbiologicallimit', verbose_name='حد المواصفة الميكروبيولوجية'),
        ),
        migrations.AddField(
            model_name='microbiologicallimit',
            name='microorganism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='food_quarantine.microorganism', verbose_name='الكائن الدقيق'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='food_quarantine.productcategory', verbose_name='الفئة الأم')),
            ],
            options={
                'verbose_name': 'فئة غذائية',
                'verbose_name_plural': 'الفئات الغذائية',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MicrobiologicalSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='رمز المواصفة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المواصفة')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('reference', models.TextField(blank=True, verbose_name='المرجع التشريعي/الفني')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'فعالة'), ('ARCHIVED', 'مؤرشفة')], default='DRAFT', max_length=10, verbose_name='الحالة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_micro_specs', to=settings.AUTH_USER_MODEL, verbose_name='المُعتمِد')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='food_quarantine.foodproduct', verbose_name='المنتج')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='food_quarantine.productcategory', verbose_name='فئة الغذاء')),
            ],
            options={
                'verbose_name': 'مواصفة ميكروبيولوجية',
                'verbose_name_plural': 'المواصفات الميكروبيولوجية',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='micro_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='food_quarantine.productcategory', verbose_name='الفئة الميكروبيولوجية'),
        ),
        migrations.CreateModel(
            name='SampleUnitResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.PositiveIntegerField(verbose_name='رقم الوحدة')),
                ('result_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='القيمة')),
                ('qualifier', models.CharField(blank=True, choices=[('POSITIVE', 'موجبة'), ('NEGATIVE', 'سالبة'), ('TENTATIVE', 'مشكوك فيها')], max_length=20, verbose_name='النوعية')),
                ('result_unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإدخال')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_unit_results', to=settings.AUTH_USER_MODEL, verbose_name='المُدخل')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_results', to='food_quarantine.sampletest', verbose_name='الفحص')),
            ],
            options={
                'verbose_name': 'نتيجة وحدة عينة',
                'verbose_name_plural': 'نتائج وحدات العينة',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(verbose_name='رقم الإصدار')),
                ('effective_from', models.DateField(verbose_name='تاريخ السريان')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_spec_versions', to=settings.AUTH_USER_MODEL, verbose_name='المُعتمِد')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='food_quarantine.microbiologicalspecification', verbose_name='المواصفة')),
            ],
            options={
                'verbose_name': 'نسخة مواصفة',
                'verbose_name_plural': 'نسخ المواصفات',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ResultEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('INCONCLUSIVE', 'غير حاسم')], max_length=20, verbose_name='القرار')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل التقييم')),
                ('engine_version', models.CharField(blank=True, max_length=40, verbose_name='نسخة المحرك')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التقييم')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ran_micro_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='مُنفّذ التقييم')),
                ('limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='food_quarantine.microbiologicallimit', verbose_name='الحد المطبق')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='food_quarantine.sampletest', verbose_name='الفحص')),
                ('spec_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='food_quarantine.specificationversion', verbose_name='نسخة المواصفة المطبقة')),
            ],
            options={
                'verbose_name': 'تقييم آلي',
                'verbose_name_plural': 'التقييمات الآلية',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.AddField(
            model_name='microbiologicallimit',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='food_quarantine.specificationversion', verbose_name='نسخة المواصفة'),
        ),
        migrations.AddField(
            model_name='microbiologicallimit',
            name='test_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='food_quarantine.testmethod', verbose_name='طريقة الاختبار'),
        ),
        migrations.AddConstraint(
            model_name='sampleunitresult',
            constraint=models.UniqueConstraint(fields=('test', 'unit_number'), name='unique_test_unit'),
        ),
        migrations.AddConstraint(
            model_name='specificationversion',
            constraint=models.UniqueConstraint(fields=('specification', 'version'), name='unique_spec_version'),
        ),
    ]
