# Generated by Django 5.0.14 on 2026-08-16 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0012_microbiologicallimit_microorganism_testmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsample',
            name='priority',
            field=models.CharField(choices=[('LOW', 'منخفضة'), ('NORMAL', 'عادية'), ('HIGH', 'عالية'), ('URGENT', 'عاجلة')], default='NORMAL', max_length=10, verbose_name='أولوية التحليل'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='priority_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر تحديث للأولوية'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='priority_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prioritized_food_samples', to=settings.AUTH_USER_MODEL, verbose_name='محدّث الأولوية'),
        ),
    ]
