# Generated by Django 5.0.14 on 2026-08-16 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0013_foodsample_priority_foodsample_priority_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletest',
            name='qc_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات مراجعة الجودة'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='qc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت مراجعة الجودة'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='qc_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_reviewed_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='مراجِع الجودة'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='qc_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار المراجعة'), ('PASSED', 'مطابق'), ('FAILED', 'غير مطابق')], default='PENDING', max_length=10, verbose_name='مراجعة الجودة'),
        ),
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الجهاز (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم الجهاز (إنجليزي)')),
                ('model_number', models.CharField(blank=True, max_length=120, verbose_name='رقم الموديل')),
                ('bench', models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='CHEMISTRY', max_length=20, verbose_name='قسم المختبر')),
                ('status', models.CharField(choices=[('OPERATIONAL', 'تشغيلية'), ('UNDER_MAINTENANCE', 'قيد الصيانة'), ('OUT_OF_SERVICE', 'خارج الخدمة')], default='OPERATIONAL', max_length=20, verbose_name='الحالة')),
                ('last_calibrated', models.DateField(blank=True, null=True, verbose_name='آخر معايرة')),
                ('next_calibration_due', models.DateField(blank=True, null=True, verbose_name='موعد المعايرة القادم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_lab_equipment', to=settings.AUTH_USER_MODEL, verbose_name='مُسجِّل الجهاز')),
            ],
            options={
                'verbose_name': 'جهاز معملي',
                'verbose_name_plural': 'الأجهزة المختبرية',
                'ordering': ['bench', 'name_ar'],
            },
        ),
    ]
