# Generated by Django 5.0.14 on 2026-08-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0014_sampletest_qc_notes_sampletest_qc_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsample',
            name='analysis_request_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='رقم طلب التحليل'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='batch_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='رقم التشغيلة Batch'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='العلامة التجارية'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم المفتش'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='origin_country',
            field=models.CharField(blank=True, max_length=80, verbose_name='بلد المنشأ'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='packaging_condition',
            field=models.CharField(blank=True, max_length=40, verbose_name='حالة العبوة'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='نوع العبوة'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإنتاج'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='الكمية'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='وحدة الكمية'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='reception_checklist',
            field=models.JSONField(blank=True, default=dict, verbose_name='قائمة فحص القبول'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=120, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='station',
            field=models.CharField(blank=True, max_length=120, verbose_name='الموقع / المحطة'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='درجة الحرارة °C'),
        ),
        migrations.AddField(
            model_name='foodsample',
            name='units_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الوحدات'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='original_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_copies', to='food_quarantine.foodsample', verbose_name='العينة الأصلية'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='quantity',
            field=models.CharField(blank=True, max_length=60, verbose_name='كمية العينة'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='retention_duration',
            field=models.CharField(blank=True, max_length=60, verbose_name='مدة الاحتفاظ'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='retention_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب الحفظ'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='storage_temperature',
            field=models.CharField(blank=True, max_length=40, verbose_name='درجة الحفظ'),
        ),
    ]
