# Generated by Django 5.0.14 on 2026-08-18 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0015_foodsample_analysis_request_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الكاشف (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم الكاشف (إنجليزي)')),
                ('bench', models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='MICROBIOLOGY', max_length=20, verbose_name='القسم')),
                ('lot_number', models.CharField(blank=True, max_length=120, verbose_name='رقم التشغيلة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة')),
                ('status', models.CharField(choices=[('AVAILABLE', 'متوفر'), ('LOW', 'كمية منخفضة'), ('EXPIRED', 'منتهي الصلاحية'), ('DISPOSED', 'تم التخلص')], default='AVAILABLE', max_length=10, verbose_name='الحالة')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='المورد')),
                ('certificate_ref', models.CharField(blank=True, max_length=120, verbose_name='مرجع شهادة التحليل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'كاشف',
                'verbose_name_plural': 'الكواشف',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('REVIEW', 'مراجعة'), ('APPROVE', 'اعتماد'), ('REJECT', 'رفض'), ('ASSIGN', 'إسناد'), ('QC', 'مراجعة جودة'), ('CAPA', 'إجراء تصحيحي'), ('LOGIN', 'دخول'), ('LOGOUT', 'خروج')], max_length=20, verbose_name='الفعل')),
                ('object_type', models.CharField(max_length=60, verbose_name='نوع الكائن')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='معرّف الكائن')),
                ('object_label', models.CharField(blank=True, max_length=255, verbose_name='وصف الكائن')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق (Audit Trail)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nc_number', models.CharField(blank=True, max_length=60, unique=True, verbose_name='رقم عدم المطابقة')),
                ('nc_type', models.CharField(choices=[('SAMPLE', 'عينة'), ('TEST', 'اختبار'), ('QC', 'جودة'), ('EQUIPMENT', 'جهاز'), ('REAGENT', 'كاشف'), ('METHOD', 'طريقة'), ('PERSONNEL', 'موظف'), ('DOCUMENTATION', 'توثيق'), ('RESULT', 'نتيجة'), ('SLA', 'التزام زمني')], default='TEST', max_length=20, verbose_name='النوع')),
                ('bench', models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='MICROBIOLOGY', max_length=20, verbose_name='القسم')),
                ('severity', models.CharField(choices=[('MINOR', 'طفيف'), ('MAJOR', 'جوهري'), ('CRITICAL', 'حرج')], default='MINOR', max_length=10, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('UNDER_INVESTIGATION', 'قيد التحقيق'), ('AWAITING_CAPA', 'بانتظار CAPA'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=40, verbose_name='نوع المرجع')),
                ('reference_number', models.CharField(blank=True, max_length=120, verbose_name='رقم المرجع')),
                ('root_cause', models.TextField(blank=True, verbose_name='التحليل الجذري')),
                ('capa_required', models.BooleanField(default=False, verbose_name='يتطلب CAPA')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='مُبلِّغ')),
            ],
            options={
                'verbose_name': 'عدم مطابقة',
                'verbose_name_plural': 'عدم المطابقة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CpaRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('root_cause', models.TextField(blank=True, verbose_name='التحليل الجذري')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي')),
                ('preventive_action', models.TextField(blank=True, verbose_name='الإجراء الوقائي')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('VERIFICATION', 'قيد التحقق'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('verification_notes', models.TextField(blank=True, verbose_name='ملاحظات التحقق')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_capa', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('non_conformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_records', to='food_quarantine.nonconformity', verbose_name='عدم المطابقة')),
            ],
            options={
                'verbose_name': 'سجل CAPA',
                'verbose_name_plural': 'سجلات CAPA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qc_number', models.CharField(blank=True, max_length=60, unique=True, verbose_name='رقم سجل الجودة')),
                ('bench', models.CharField(choices=[('MICROBIOLOGY', 'الأحياء الدقيقة'), ('CHEMISTRY', 'الكيمياء'), ('TOXICOLOGY', 'السموم'), ('MOLECULAR', 'الجزيئي')], default='MICROBIOLOGY', max_length=20, verbose_name='القسم')),
                ('control_type', models.CharField(max_length=120, verbose_name='نوع الضابط/العينة الضابطة')),
                ('lot_number', models.CharField(blank=True, max_length=120, verbose_name='رقم التشغيلة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('PASSED', 'مطابق'), ('FAILED', 'غير مطابق')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('severity', models.CharField(choices=[('MINOR', 'طفيف'), ('MAJOR', 'جوهري'), ('CRITICAL', 'حرج')], default='MINOR', max_length=10, verbose_name='الخطورة')),
                ('result_value', models.FloatField(blank=True, null=True, verbose_name='قيمة نتيجة الضابط')),
                ('expected_value', models.FloatField(blank=True, null=True, verbose_name='القيمة المتوقعة')),
                ('tolerance', models.FloatField(blank=True, null=True, verbose_name='حد التسامح')),
                ('qc_notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة')),
                ('affected_tests', models.ManyToManyField(blank=True, related_name='affected_qc_records', to='food_quarantine.sampletest', verbose_name='النتائج المتأثرة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_records_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='مراجِع الجودة')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_records', to='food_quarantine.sampletest', verbose_name='الفحص المرتبط')),
            ],
            options={
                'verbose_name': 'سجل مراجعة الجودة',
                'verbose_name_plural': 'سجلات مراجعة الجودة (QC)',
                'ordering': ['-created_at'],
            },
        ),
    ]
