# Generated by Django 5.0.14 on 2026-08-19 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0017_alter_reagent_options_materialcatalog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='رقم الطريقة')),
                ('name_ar', models.CharField(max_length=250, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=250, verbose_name='الاسم (إنجليزي)')),
                ('source', models.CharField(choices=[('ISO', 'ISO'), ('AOAC', 'AOAC'), ('CODEX', 'Codex'), ('SSMO', 'SSMO'), ('OTHER', 'مرجع آخر معتمد')], default='AOAC', max_length=20, verbose_name='المصدر')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='النسخة')),
                ('matrix', models.CharField(blank=True, max_length=200, verbose_name='المصفوفة/المجال')),
                ('applicable_organism', models.CharField(blank=True, max_length=200, verbose_name='الكائنات المطبقة')),
                ('lod', models.CharField(blank=True, max_length=100, verbose_name='حد الكشف LOD')),
                ('loq', models.CharField(blank=True, max_length=100, verbose_name='حد الكمية LOQ')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة')),
                ('validation_status', models.CharField(choices=[('VALIDATED', 'مُصدَّق عليها (Validated)'), ('VERIFIED', 'تم التحقق منها (Verified)'), ('PERFORMANCE_TESTED', 'مختبرة الأداء (PTM)'), ('PENDING', 'قيد الاعتماد'), ('INVALID', 'غير صالحة')], default='VALIDATED', max_length=30, verbose_name='حالة الاعتماد')),
                ('reference_standard', models.CharField(blank=True, max_length=200, verbose_name='المرجع')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'طريقة تحليلية',
                'verbose_name_plural': 'الطرق التحليلية',
                'ordering': ['source', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('priority', models.PositiveIntegerField(default=10, verbose_name='ترتيب الأولوية')),
                ('source_type', models.CharField(choices=[('NATIONAL_LAW', 'قانون/تشريع وطني'), ('SUDANESE_STANDARD', 'مواصفة سودانية'), ('REGULATORY_DECISION', 'قرار تنظيمي/سياسة'), ('CONTRACT_DESTINATION', 'اشتراط تعاقدي/بلد المقصد'), ('GSO_REFERENCE', 'مرجع GSO معتمد'), ('CODEX_REFERENCE', 'مرجع Codex')], default='SUDANESE_STANDARD', max_length=40, verbose_name='نوع المرجع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعالة')),
            ],
            options={
                'verbose_name': 'قاعدة تطبيق تنظيمية',
                'verbose_name_plural': 'قواعد التطبيق التنظيمية',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.AddField(
            model_name='sampletest',
            name='applied_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='food_quarantine.analyticalmethod', verbose_name='طريقة التحليل المطبقة'),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='رقم المواصفة')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='العنوان (إنجليزي)')),
                ('source', models.CharField(choices=[('SSMO', 'المواصفة السودانية SSMO'), ('GSO', 'المواصفة الخليجية GSO'), ('CODEX', 'Codex Alimentarius'), ('ISO', 'ISO'), ('AOAC', 'AOAC'), ('OTHER', 'مرجع آخر معتمد')], default='SSMO', max_length=20, verbose_name='المصدر')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='الدولة/الجهة')),
                ('document_reference', models.CharField(blank=True, max_length=200, verbose_name='المرجع الوثائقي')),
                ('mandatory', models.BooleanField(default=True, verbose_name='إلزامية')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('ACTIVE', 'فعالة'), ('ARCHIVED', 'مؤرشفة')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_standards', to=settings.AUTH_USER_MODEL, verbose_name='المُعتمِد')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='food_quarantine.foodproduct', verbose_name='المنتج')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='food_quarantine.productcategory', verbose_name='فئة الغذاء')),
            ],
            options={
                'verbose_name': 'مواصفة/معيار',
                'verbose_name_plural': 'المواصفات والمعايير',
                'ordering': ['source', 'code'],
            },
        ),
        migrations.AddField(
            model_name='sampletest',
            name='applied_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='food_quarantine.standard', verbose_name='المواصفة المطبقة'),
        ),
        migrations.CreateModel(
            name='StandardRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit_type', models.CharField(choices=[('MAXIMUM', 'حد أقصى (≤)'), ('MINIMUM', 'حد أدنى (≥)'), ('RANGE', 'مدى (بين)'), ('SPECIFIED', 'قيمة محددة'), ('PRESENCE_ABSENCE', 'حضور/غياب')], default='MAXIMUM', max_length=30, verbose_name='نوع الحد')),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='الحد الأدنى')),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='الحد الأقصى')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('n', models.PositiveIntegerField(default=5, verbose_name='n — عدد وحدات العينة')),
                ('c', models.PositiveIntegerField(default=0, verbose_name='c — الحد الأقصى للوحدات بين m و M')),
                ('m', models.DecimalField(blank=True, db_column='m_limit', decimal_places=6, max_digits=20, null=True, verbose_name='m — الحد المقبول')),
                ('M', models.DecimalField(blank=True, db_column='Mmax', decimal_places=6, max_digits=20, null=True, verbose_name='M — الحد الأقصى')),
                ('plan', models.CharField(choices=[('TWO_CLASS', 'خطة من فئتين (2-Class)'), ('THREE_CLASS', 'خطة من ثلاث فئات (3-Class)'), ('PRESENCE_ABSENCE', 'حضور/غياب')], default='THREE_CLASS', max_length=30, verbose_name='نوع الخطة')),
                ('rule_json', models.JSONField(blank=True, default=dict, verbose_name='قواعد قابلة للتهيئة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='food_quarantine.analyticalmethod', verbose_name='طريقة التحليل')),
                ('microorganism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_requirements', to='food_quarantine.microorganism', verbose_name='الكائن الدقيق')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_requirements', to='food_quarantine.labparameter', verbose_name='المعامل/التحليل')),
            ],
            options={
                'verbose_name': 'متطلب مواصفة',
                'verbose_name_plural': 'متطلبات المواصفات',
                'ordering': ['version__effective_from', 'parameter__code', 'microorganism__code'],
            },
        ),
        migrations.AddField(
            model_name='sampletest',
            name='applied_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='food_quarantine.standardrequirement', verbose_name='المتطلب المطبق'),
        ),
        migrations.CreateModel(
            name='StandardVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=30, verbose_name='رقم/سنة الإصدار')),
                ('effective_from', models.DateField(verbose_name='تاريخ السريان')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('document_reference', models.CharField(blank=True, max_length=200, verbose_name='المرجع الوثائقي للنسخة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_standard_versions', to=settings.AUTH_USER_MODEL, verbose_name='المُعتمِد')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='food_quarantine.standard', verbose_name='المواصفة')),
            ],
            options={
                'verbose_name': 'نسخة مواصفة',
                'verbose_name_plural': 'نسخ المواصفات',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='standardrequirement',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='food_quarantine.standardversion', verbose_name='نسخة المواصفة'),
        ),
        migrations.AddField(
            model_name='sampletest',
            name='applied_standard_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='food_quarantine.standardversion', verbose_name='نسخة المواصفة المطبقة'),
        ),
        migrations.AddConstraint(
            model_name='standardversion',
            constraint=models.UniqueConstraint(fields=('standard', 'version'), name='unique_standard_version'),
        ),
    ]
