# Generated by Django 5.0.14 on 2026-08-22 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0018_analyticalmethod_regulatoryrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshipment',
            name='transport_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات وسيلة النقل (AWB/شاحنة/معبر…)'),
        ),
        migrations.AlterField(
            model_name='foodshipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('RECEIVED', 'تم الاستلام'), ('FEES_DUE', 'مستحقة الرسوم'), ('AWAITING_INSPECTION', 'بانتظار التفتيش'), ('UNDER_INSPECTION', 'قيد التفتيش'), ('AWAITING_LAB_RESULTS', 'بانتظار النتائج'), ('AWAITING_DECISION', 'بانتظار القرار'), ('RELEASED', 'تم الإفراج'), ('CONDITIONAL_RELEASE', 'إفراج مشروط'), ('REJECTED', 'مرفوض'), ('HOLD', 'محجوزة'), ('RE_EXPORT', 'إعادة تصدير'), ('DESTROYED', 'إتلاف')], default='RECEIVED', max_length=25, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ShipmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('CUSTOMS', 'البيان الجمركي'), ('HEALTH_CERT', 'الشهادة الصحية'), ('ORIGIN_CERT', 'شهادة المنشأ'), ('INVOICE', 'الفاتورة'), ('PACKING_LIST', 'قائمة التعبئة'), ('AWB_BL', 'AWB / B/L'), ('ANALYSIS_CERT', 'شهادة التحليل'), ('OTHER', 'مستند إضافي')], max_length=20, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='food_shipments/%Y/%m/', verbose_name='الملف')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_attachments', to=settings.AUTH_USER_MODEL, verbose_name='رافع المستند')),
            ],
            options={
                'verbose_name': 'مستند شحنة',
                'verbose_name_plural': 'مستندات الشحنات',
                'ordering': ['-created_at'],
            },
        ),
    ]
