# Generated by Django 5.0.14 on 2026-08-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0019_foodshipment_transport_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinvoice',
            name='paid_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات التحصيل'),
        ),
        migrations.AddField(
            model_name='foodinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدي'), ('BANK_CARD', 'شبكة بنكية'), ('BANK_TRANSFER', 'تحويل بنكي'), ('ELECTRONIC', 'إلكتروني')], max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
