# Generated by Django 5.0.14 on 2026-08-23 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0020_foodinvoice_paid_notes_foodinvoice_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinspection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_inspections_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='المراجع'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='supervisor_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات إشرافية'),
        ),
        migrations.AddField(
            model_name='foodinspection',
            name='supervisor_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار مراجعة رئيس القسم'), ('APPROVED', 'معتمد من رئيس القسم'), ('RETURNED', 'مُرجع لإعادة التفتيش')], default='PENDING', max_length=20, verbose_name='حالة مراجعة المشرف'),
        ),
    ]
