# Generated by Django 5.0.14 on 2026-09-04 14:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0022_alter_foodshipment_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentattachment',
            name='rejected_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض/التصحيح'),
        ),
        migrations.AddField(
            model_name='shipmentattachment',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'مرفوع'), ('RECEIVED', 'تم الاستلام'), ('UNDER_REVIEW', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('CORRECTION_REQUIRED', 'مطلوب تصحيح')], default='UPLOADED', max_length=24, verbose_name='حالة المستند'),
        ),
        migrations.CreateModel(
            name='FoodShipmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('CREATED', 'تم إنشاء الطلب'), ('DOCS_UPLOADED', 'تم رفع المستندات'), ('DOCS_COMPLETE', 'اكتملت المستندات'), ('SUBMITTED', 'تم إرسال الطلب'), ('ADMIN_REVIEW', 'المراجعة الإدارية'), ('REFERRED_TO_ACCOUNTANT', 'تمت الإحالة للمحاسب'), ('FEES_ASSESSED', 'تم احتساب الرسوم'), ('FEES_CONFIRMED', 'تم تأكيد الرسوم'), ('REFERRED_TO_INSPECTOR', 'تمت الإحالة للمفتش'), ('INSPECTION', 'التفتيش'), ('SAMPLING', 'أخذ العينات'), ('LABORATORY', 'المختبر'), ('AWAITING_DECISION', 'بانتظار القرار'), ('DECISION', 'القرار'), ('RELEASED', 'تم الإفراج'), ('REJECTED', 'مرفوض'), ('CORRECTION', 'مطلوب تصحيح'), ('OTHER', 'حدث آخر')], max_length=30, verbose_name='المرحلة')),
                ('message', models.TextField(blank=True, verbose_name='الوصف')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحدث')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='food_quarantine.foodshipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'حدث طلب غذائي',
                'verbose_name_plural': 'أحداث الطلبات الغذائية (التسلسل الزمني)',
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
    ]
