# Generated by Django 6.1 on 2026-09-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0023_shipmentattachment_rejected_reason_and_more'),
        ('organization', '0007_sector_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsample',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='القطاع الإداري المرتبط بالعينة (بوابة القطاع المعملية)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_samples', to='organization.sector', verbose_name='القطاع'),
        ),
    ]
