# Generated by Django 6.1 on 2026-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_quarantine', '0024_foodsample_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'قيد التنفيذ'), ('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسلة للمراجعة'), ('REVIEWED', 'راجعها رئيس القسم'), ('APPROVED', 'اعتمدها مدير المختبر'), ('COMPLETED', 'مكتمل'), ('RETEST', 'إعادة فحص')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
    ]
