# Generated by Django 5.0.14 on 2026-07-31 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='مفتاح API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نظام خارجي',
                'verbose_name_plural': 'الأنظمة الخارجية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_name', models.CharField(max_length=50, verbose_name='اسم التكامل')),
                ('request_type', models.CharField(max_length=50, verbose_name='نوع الطلب')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الطلب')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='رمز الحالة')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
            ],
            options={
                'verbose_name': 'سجل تكامل',
                'verbose_name_plural': 'سجلات التكامل',
                'ordering': ['-request_timestamp'],
            },
        ),
    ]
