# Generated by Django 5.0.14 on 2026-08-05 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم التطبيق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='مفتاح API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تطبيق مطور',
                'verbose_name_plural': 'تطبيقات المطورين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50, verbose_name='نوع الحدث')),
                ('endpoint_url', models.URLField(verbose_name='رابط النقطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integration.developerapp', verbose_name='التطبيق')),
            ],
            options={
                'verbose_name': 'نقطة ويب هوك',
                'verbose_name_plural': 'نقاط الويب هوك',
                'ordering': ['app', 'event_type'],
            },
        ),
    ]
