# Generated by Django 5.0.14 on 2026-10-01 10:05

from django.db import migrations, models


def backfill_status_from_status_code(apps, schema_editor):
    """اشتق حالة السجلات القديمة من `status_code` الموجود فعلاً.

    الصفوف السابقة تحمل رمز HTTP فقط. `UNKNOWN` (القيمة الافتراضية) صار
    إجابةً صادقة لكنها غير مفيدة للmonitoring، فبينما الرمز موجود نستخدمه:
    2xx/3xx ⇐ SUCCESS، ما عدا ذلك ⇐ FAILED، و`status_code IS NULL` ⇐ يبقى
    UNKNOWN لأن التبادل الداخلي (مثل IHR) لا يُرجع رمزاً.

    الاتجاه لا يمكن اشتقاقه من `request_type` بذكاء: `*_SEND` و`*_RECEIVE`
    اصطلاح متقطع لا يغطي كل الأسماء، والاشتقاق الخاطئ أسوأ من `UNKNOWN`.
    """
    log_model = apps.get_model('integration', 'IntegrationLog')

    log_model.objects.filter(
        status_code__isnull=False, status_code__gte=200, status_code__lt=400
    ).update(status='SUCCESS')
    log_model.objects.filter(
        status_code__isnull=False
    ).exclude(status_code__gte=200, status_code__lt=400).update(status='FAILED')
    # status_code IS NULL يبقى UNKNOWN عمداً.


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_developerapp_webhookendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='معرّف الارتباط'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='direction',
            field=models.CharField(choices=[('INBOUND', 'وارد'), ('OUTBOUND', 'صادر'), ('UNKNOWN', 'غير محدَّد')], default='UNKNOWN', max_length=10, verbose_name='الاتجاه'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='المدة (مللي ثانية)'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'نجح'), ('FAILED', 'فشل'), ('PENDING', 'بانتظار'), ('RETRY', 'إعادة محاولة'), ('UNKNOWN', 'غير محدَّد')], default='UNKNOWN', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration_name', '-request_timestamp'], name='intlog_name_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['status', '-request_timestamp'], name='intlog_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['correlation_id'], name='intlog_corr_idx'),
        ),
        migrations.RunPython(backfill_status_from_status_code, migrations.RunPython.noop),
    ]
