# Generated by Django 5.0.14 on 2026-10-01 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_integrationlog_monitoring_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Organization model state only (table already exists as integration_externalentity)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Organization',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                        ('name_en', models.CharField(max_length=120, verbose_name='الاسم (إنجليزي)')),
                        ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                        ('org_type', models.CharField(choices=[('INTERNATIONAL', 'دولية'), ('GOVERNMENT', 'حكومية'), ('LABORATORY', 'مختبر'), ('HOSPITAL', 'مستشفى'), ('PARTNER', 'شريك'), ('OTHER', 'أخرى')], max_length=20, verbose_name='النوع')),
                        ('country', models.CharField(blank=True, max_length=2, verbose_name='الكود الدولي ISO')),
                        ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('PENDING', 'معلق'), ('INACTIVE', 'غير نشط')], default='PENDING', max_length=20, verbose_name='الحالة')),
                        ('technical_contact_name', models.CharField(blank=True, max_length=100, verbose_name='جهة الاتصال')),
                        ('technical_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                        ('technical_contact_phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                        ('api_key_encrypted', models.TextField(blank=True, verbose_name='مفتاح API (مشفّر)')),
                        ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                        ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                    ],
                    options={
                        'verbose_name': 'منظمة خارجية',
                        'verbose_name_plural': 'المنظمات الخارجية',
                        'ordering': ['name_en'],
                        'db_table': 'integration_externalentity',
                    },
                ),
            ],
            database_operations=[],
        ),

        # ApiEndpoint
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='الكود')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('protocol', models.CharField(choices=[('REST', 'REST'), ('SOAP', 'SOAP'), ('SFTP', 'SFTP'), ('ODATA', 'OData'), ('GRPC', 'gRPC')], default='REST', max_length=20, verbose_name='البروتوكول')),
                ('scope', models.CharField(choices=[('DISEASE', 'Disease'), ('SURVEILLANCE', 'Surveillance'), ('VACCINATION', 'Vaccination'), ('IHR', 'IHR'), ('LABORATORY', 'Laboratory'), ('HEALTH_EVENT', 'Health Event'), ('REFERENCE', 'Reference Data')], default='REFERENCE', max_length=20, verbose_name='التصنيف')),
                ('base_url', models.URLField(verbose_name='الرابط الأساسي')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='الإصدار')),
                ('auth_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المصادقة')),
                ('doc_url', models.URLField(blank=True, verbose_name='رابط التوثيق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحقق')),
            ],
            options={
                'verbose_name': 'نقطة API',
                'verbose_name_plural': 'نقاط API',
            },
        ),

        # EncryptedCredentialValue
        migrations.CreateModel(
            name='EncryptedCredentialValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_type', models.CharField(choices=[('API_KEY', 'API Key'), ('OAUTH_SECRET', 'OAuth Secret'), ('CERTIFICATE', 'شهادة'), ('TOKEN', 'Token'), ('OTHER', 'أخرى')], max_length=20, verbose_name='النوع')),
                ('key_name', models.CharField(max_length=80, verbose_name='اسم المفتاح')),
                ('encrypted_value', models.TextField(verbose_name='القيمة المشفّرة')),
            ],
            options={
                'verbose_name': 'سر التكامل',
                'verbose_name_plural': 'أسرار التكامل',
            },
        ),

        # Integration
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('DEV', 'تطويري'), ('SANDBOX', 'تجريبي'), ('PRODUCTION', 'إنتاجي')], default='SANDBOX', max_length=20, verbose_name='البيئة')),
                ('status', models.CharField(choices=[('NOT_CONFIGURED', 'غير مُعدّ'), ('PENDING', 'معلق'), ('CONFIGURED', 'مُعدّ'), ('VERIFIED', 'موثَّق'), ('FAILED', 'فشل'), ('DISABLED', 'معطّل')], default='NOT_CONFIGURED', max_length=24, verbose_name='الحالة')),
                ('auth_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المصادقة')),
                ('base_url', models.URLField(blank=True, verbose_name='الرابط الأساسي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحقق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='integration.apiendpoint', verbose_name='نقطة API')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='integration.organization', verbose_name='المنظمة')),
            ],
            options={
                'verbose_name': 'تكامل',
                'verbose_name_plural': 'التكاملات',
            },
        ),

        # IntegrationHealth
        migrations.CreateModel(
            name='IntegrationHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_type', models.CharField(max_length=60, verbose_name='نوع الفحص')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('detail', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('checked_by', models.CharField(blank=True, max_length=100, verbose_name='الفاحص')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفحص')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='integration.integration', verbose_name='التكامل')),
            ],
            options={
                'verbose_name': 'سجل صحة',
                'verbose_name_plural': 'سجلات الصحة',
                'ordering': ['-checked_at'],
            },
        ),

        # WebhookSubscription
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50, verbose_name='نوع الحدث')),
                ('endpoint_url', models.URLField(verbose_name='رابط النقطة')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='السر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر توصيل')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='أعطال')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integration.integration', verbose_name='التكامل')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integration.organization', verbose_name='المنظمة')),
            ],
            options={
                'verbose_name': 'ويب هوك',
                'verbose_name_plural': 'ويب هوك',
            },
        ),

        # WebhookDelivery
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'معلق'), ('SUCCESS', 'نجح'), ('FAILED', 'فشل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='رمز HTTP')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الطلب')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='الخطأ')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='المدة')),
                ('fired_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integration.webhooksubscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'توصيل ويب هوك',
                'verbose_name_plural': 'توصيلات ويب هوك',
                'ordering': ['-fired_at'],
            },
        ),

        # AuditLog
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='المستخدم')),
                ('action', models.CharField(max_length=60, verbose_name='الإجراء')),
                ('resource_type', models.CharField(max_length=60, verbose_name='نوع المورد')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='معرّف المورد')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('result', models.CharField(choices=[('SUCCESS', 'نجح'), ('FAILURE', 'فشل'), ('BLOCKED', 'محظور')], default='SUCCESS', max_length=20, verbose_name='النتيجة')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-created_at'],
            },
        ),

        # DataScope (depends on Organization, ApiEndpoint)
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('READ', 'قراءة'), ('WRITE', 'كتابة')], max_length=10, verbose_name='الاتجاه')),
                ('resource', models.CharField(max_length=80, verbose_name='المورد')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المنح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='integration.apiendpoint', verbose_name='نقطة API')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_scopes', to=settings.AUTH_USER_MODEL, verbose_name='الممنوح من')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='integration.organization', verbose_name='المنظمة')),
            ],
            options={
                'verbose_name': 'نطاق بيانات',
                'verbose_name_plural': 'نطاقات البيانات',
            },
        ),

        # EncryptedCredentialValue FK to Integration
        migrations.AddField(
            model_name='encryptedcredentialvalue',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integration.integration', verbose_name='التكامل'),
        ),

        # Add unique_together constraints
        migrations.AddConstraint(
            model_name='encryptedcredentialvalue',
            constraint=models.UniqueConstraint(fields=('integration', 'key_type', 'key_name'), name='unique_credential_per_integration'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('organization', 'endpoint'), name='unique_integration_per_org_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='datascope',
            constraint=models.UniqueConstraint(fields=('organization', 'endpoint', 'direction', 'resource'), name='unique_datascope_per_org_endpoint_direction_resource'),
        ),
    ]