# Generated by Django 5.0.14 on 2026-10-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_organization_schema_and_apiendpoint_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiendpoint',
            options={'ordering': ['code'], 'verbose_name': 'نقطة API', 'verbose_name_plural': 'نقاط API'},
        ),
        migrations.AlterModelOptions(
            name='encryptedcredentialvalue',
            options={'ordering': ['key_type', 'key_name'], 'verbose_name': 'سر التكامل', 'verbose_name_plural': 'أسرار التكامل'},
        ),
    ]
