# Generated by Django 5.0.14 on 2026-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المنشأة / الجهة'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CITIZEN', 'مواطن'), ('TRAVELER', 'مسافر'), ('IMPORTER', 'مستورد'), ('EXPORTER', 'مصدر'), ('COMPANY', 'شركة'), ('GOVERNMENT', 'جهة حكومية'), ('MINISTRY_STAFF', 'موظف وزارة')], default='CITIZEN', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
