# Generated by Django 5.0.14 on 2026-08-01 11:57

from django.db import migrations, models


def empty_strings_to_null(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(phone='').update(phone=None)
    User.objects.filter(national_id='').update(national_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_name_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الجوال'),
        ),
        migrations.RunPython(empty_strings_to_null, migrations.RunPython.noop),
    ]
