# Generated by Django 5.0.14 on 2026-08-03 12:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_national_id_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_permissions',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to='accounts.permission', verbose_name='صلاحيات محظورة'),
        ),
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_code', models.CharField(max_length=100, verbose_name='كود الصلاحية')),
                ('action', models.CharField(choices=[('GRANT', 'منح'), ('DENY', 'رفض'), ('REVOKE', 'إلغاء')], max_length=10, verbose_name='الإجراء')),
                ('granted', models.BooleanField(verbose_name='ممنوحة')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='وكيل المستخدم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تدقيق صلاحيات',
                'verbose_name_plural': 'تدقيق الصلاحيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'عام'), ('POINT', 'نقطة حدودية'), ('PORT', 'ميناء'), ('REGION', 'منطقة')], default='GLOBAL', max_length=20, verbose_name='نوع النطاق')),
                ('scope_id', models.UUIDField(blank=True, null=True, verbose_name='معرف النطاق')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أُعطي بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.role', verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعيين دور',
                'verbose_name_plural': 'تعيينات الأدوار',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'scope_type', 'scope_id'), name='unique_role_assignment'),
        ),
    ]
