# Generated by Django 5.0.14 on 2026-08-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rbac_roleassignment_permissionaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='scope_type',
            field=models.CharField(choices=[('GLOBAL', 'عام'), ('POINT', 'نقطة حدودية'), ('PORT', 'ميناء'), ('REGION', 'منطقة'), ('SECTOR', 'قطاع إداري'), ('STATION', 'محطة'), ('DEPARTMENT', 'إدارة')], default='GLOBAL', max_length=20, verbose_name='نوع النطاق'),
        ),
    ]
