# Generated by Django 5.0.14 on 2026-08-06 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_roleassignment_scope_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ البداية'),
        ),
    ]
