# Generated by Django 5.0.14 on 2026-08-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_roleassignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_scope',
            field=models.CharField(choices=[('GLOBAL', 'عام'), ('POINT', 'نقطة حدودية'), ('PORT', 'ميناء'), ('REGION', 'منطقة'), ('SECTOR', 'قطاع إداري'), ('DEPARTMENT', 'إدارة'), ('STATION', 'محطة')], default='GLOBAL', max_length=20, verbose_name='النطاق الافتراضي'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='scope_type',
            field=models.CharField(choices=[('GLOBAL', 'عام'), ('POINT', 'نقطة حدودية'), ('PORT', 'ميناء'), ('REGION', 'منطقة'), ('SECTOR', 'قطاع إداري'), ('DEPARTMENT', 'إدارة'), ('STATION', 'محطة')], default='GLOBAL', max_length=20, verbose_name='نوع النطاق'),
        ),
    ]
