# Generated by Django 5.0.14 on 2026-08-08 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_role_default_scope_alter_roleassignment_scope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الحساب'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='المصادقة الثنائية'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم الوظيفي')),
                ('full_name_ar', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالعربية')),
                ('full_name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='المسمى الوظيفي')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'على رأس العمل'), ('ON_LEAVE', 'إجازة'), ('SUSPENDED', 'موقوف'), ('TERMINATED', 'منتهي الخدمة')], default='ACTIVE', max_length=20, verbose_name='حالة الموظف')),
                ('internal_phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف الداخلي')),
                ('office', models.CharField(blank=True, max_length=200, verbose_name='المكتب')),
                ('preferred_contact', models.CharField(choices=[('EMAIL', 'البريد الإلكتروني'), ('SMS', 'رسالة نصية'), ('PHONE', 'اتصال هاتفي'), ('IN_APP', 'داخل النظام')], default='EMAIL', max_length=20, verbose_name='وسيلة التواصل المفضلة')),
                ('language', models.CharField(choices=[('AR', 'العربية'), ('EN', 'English')], default='AR', max_length=10, verbose_name='اللغة')),
                ('theme', models.CharField(choices=[('LIGHT', 'فاتح'), ('DARK', 'داكن')], default='LIGHT', max_length=10, verbose_name='المظهر')),
                ('timezone', models.CharField(default='Africa/Khartoum', max_length=50, verbose_name='المنطقة الزمنية')),
                ('notify_email', models.BooleanField(default=True, verbose_name='الإشعار عبر البريد')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='الإشعار عبر الرسائل')),
                ('notify_in_app', models.BooleanField(default=True, verbose_name='الإشعار داخل النظام')),
                ('signature_status', models.CharField(choices=[('UNREGISTERED', 'غير مسجلة'), ('REGISTERED', 'مسجلة'), ('VERIFIED', 'موثّقة'), ('EXPIRED', 'منتهية')], default='UNREGISTERED', max_length=20, verbose_name='حالة التوقيع')),
                ('certificate', models.CharField(blank=True, max_length=255, verbose_name='الشهادة')),
                ('signature_issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('signature_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف موظف',
                'verbose_name_plural': 'ملفات الموظفين',
                'ordering': ['-updated_at'],
            },
        ),
    ]
