# Generated by Django 5.0.14 on 2026-08-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_account_expires_at_user_is_mfa_enabled_and_more'),
        ('public', '0003_healthcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='public.sector', verbose_name='القطاع'),
        ),
    ]
