# Generated by Django 5.0.14 on 2026-08-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_sector'),
        ('organization', '0004_station_orgassignment_station'),
        ('masterdata', '0003_bridge_sector_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.sector', verbose_name='القطاع'),
        ),
    ]
