# Generated by Django 5.0.14 on 2026-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_traveller_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_verified',
            field=models.BooleanField(default=False, help_text='التحقق من الهوية عبر سوداباس', verbose_name='تم التحقق من الهوية'),
        ),
        migrations.AddField(
            model_name='user',
            name='sudapass_subject_id',
            field=models.CharField(blank=True, help_text='معرّف المواطن الموحّد من نظام سوداباس (الهوية الرقمية القومية)', max_length=255, null=True, unique=True, verbose_name='معرف سوداباس'),
        ),
    ]
