# Generated by Django 5.0.14 on 2026-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_identity_verified_user_sudapass_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='معرّف تسجيل دخول اختياري يُسمح بالدخول به بدلاً من البريد', max_length=50, null=True, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
