# Generated by Django 5.0.14 on 2026-09-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identity_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sudapass_subject_id',
        ),
    ]
