# Generated by Django 5.0.14 on 2026-09-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_identity_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشهادة'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الطوارئ'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الاتصال الطارئ'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'دائم'), ('CONTRACT', 'عقد'), ('TEMPORARY', 'مؤقت'), ('CONSULTANT', 'مستشار'), ('INTERN', 'متدرب')], default='PERMANENT', max_length=20, verbose_name='نوع العمل'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='home_address',
            field=models.TextField(blank=True, verbose_name='العنوان المنزلي'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية فترة الاختبار'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='accounts.employeeprofile', verbose_name='المدير المباشر'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص'),
        ),
    ]
