# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('iata_code', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='كود IATA')),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='كود ICAO')),
                ('contact_info', models.JSONField(blank=True, default=dict, verbose_name='معلومات الاتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شركة نقل',
                'verbose_name_plural': 'شركات النقل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('category', models.CharField(choices=[('FLIGHT_SUSPENSION', 'تعليق رحلات'), ('ENTRY_REQUIREMENTS', 'متطلبات الدخول'), ('EPIDEMIC_ALERT', 'إنذار وبائي'), ('GENERAL', 'إعلان عام')], max_length=30, verbose_name='الفئة')),
                ('priority', models.CharField(choices=[('HIGH', 'عالي'), ('MEDIUM', 'متوسط'), ('LOW', 'منخفض')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إشعار صحي',
                'verbose_name_plural': 'الإشعارات الصحية',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_number', models.CharField(max_length=20, verbose_name='رقم جواز السفر')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('seat_number', models.CharField(blank=True, max_length=10, verbose_name='رقم المقعد')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
            ],
            options={
                'verbose_name': 'مسافر في الكشف',
                'verbose_name_plural': 'مسافرو الكشف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='manifests/%Y/%m/', verbose_name='الملف')),
                ('status', models.CharField(choices=[('UPLOADED', 'تم الرفع'), ('PROCESSING', 'قيد المعالجة'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], default='UPLOADED', max_length=20, verbose_name='الحالة')),
                ('total_passengers', models.PositiveIntegerField(default=0, verbose_name='عدد المسافرين')),
                ('error_report', models.JSONField(blank=True, default=dict, verbose_name='تقرير الأخطاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
            ],
            options={
                'verbose_name': 'كشف المسافرين',
                'verbose_name_plural': 'كشوف المسافرين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_number', models.CharField(max_length=20, verbose_name='رقم الرحلة')),
                ('flight_type', models.CharField(choices=[('AIR', 'جوي'), ('SEA', 'بحري'), ('LAND', 'بري')], default='AIR', max_length=10, verbose_name='النوع')),
                ('origin_code', models.CharField(max_length=10, verbose_name='رمز المغادرة')),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True, verbose_name='موعد المغادرة')),
                ('scheduled_arrival', models.DateTimeField(verbose_name='موعد الوصول')),
                ('status', models.CharField(choices=[('SCHEDULED', 'مجدولة'), ('MANIFEST_UPLOADED', 'تم رفع الكشف'), ('IN_TRANSIT', 'في الطريق'), ('ARRIVED', 'وصلت'), ('CANCELLED', 'ملغاة')], default='SCHEDULED', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='carriers.carrier', verbose_name='شركة النقل')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'ordering': ['-scheduled_arrival'],
            },
        ),
    ]
