# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0001_initial'),
        ('ports', '0001_initial'),
        ('travelers', '0002_country_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='ports.port', verbose_name='المنفذ الوجهة'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_origin', to='travelers.country', verbose_name='دولة المغادرة'),
        ),
        migrations.AddField(
            model_name='manifestpassenger',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_passengers', to='travelers.country', verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='manifestpassenger',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_entries', to='travelers.traveler', verbose_name='المسافر المطابق'),
        ),
        migrations.AddField(
            model_name='passengermanifest',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='carriers.flight', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='manifestpassenger',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='carriers.passengermanifest', verbose_name='الكشف'),
        ),
    ]
