# Generated by Django 5.0.14 on 2026-08-10 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='api_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='مفتاح API'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إنشاء المفتاح'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الرسمي'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='last_api_use_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام للمفتاح'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='last_api_use_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP لآخر استخدام'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='الشعار (رابط)'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.CreateModel(
            name='CarrierMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='الممثل الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='carriers.carrier', verbose_name='شركة النقل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_member', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عضو شركة نقل',
                'verbose_name_plural': 'أعضاء شركات النقل',
                'ordering': ['-is_primary', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الاطلاع')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_acknowledgements', to='carriers.carrier', verbose_name='شركة النقل')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='carriers.healthnotice', verbose_name='الإشعار')),
            ],
            options={
                'verbose_name': 'إقرار إشعار',
                'verbose_name_plural': 'إقرارات الإشعارات',
            },
        ),
        migrations.AddConstraint(
            model_name='noticeacknowledgement',
            constraint=models.UniqueConstraint(fields=('carrier', 'notice'), name='unique_carrier_notice_ack'),
        ),
    ]
