# Generated by Django 5.0.14 on 2026-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrier_address_carrier_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengermanifest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manifests/%Y/%m/', verbose_name='الملف'),
        ),
    ]
