# Generated by Django 5.0.14 on 2026-08-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0004_alter_passengermanifest_file'),
        ('travelers', '0003_alter_traveler_registration_status_travelerstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights_origin', to='travelers.country', verbose_name='دولة المغادرة'),
        ),
    ]
