# Generated by Django 5.0.14 on 2026-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0005_alter_flight_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestpassenger',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
    ]
