# Generated by Django 5.0.14 on 2026-08-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_bridge_to_entrypoint'),
        ('carriers', '0006_alter_manifestpassenger_date_of_birth'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='masterdata.entrypoint', verbose_name='المنفذ الوجهة'),
        ),
    ]
