# Generated by Django 5.0.14 on 2026-09-13 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0007_alter_flight_destination_port'),
        ('emergency_eoc', '0005_emergencyevent_case_count_emergencyevent_death_count_and_more'),
        ('masterdata', '0007_merge_sdpor_to_ep_port_sudan'),
        ('travelers', '0004_traveler_medical_file_no_traveler_qr_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierApiUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=255, verbose_name='الموارد (Endpoint)')),
                ('method', models.CharField(max_length=10, verbose_name='الطريقة (Method)')),
                ('status_code', models.PositiveIntegerField(default=0, verbose_name='رمز الاستجابة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='وكيل المستخدم')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='زمن الاستجابة (مللي ثانية)')),
                ('is_rate_limited', models.BooleanField(default=False, verbose_name='تم خفض الحد')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='الحمولة المرسلة')),
            ],
            options={
                'verbose_name': 'سجل استخدام API',
                'verbose_name_plural': 'سجلات استخدام API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarrierRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('iata_code', models.CharField(blank=True, max_length=3, verbose_name='كود IATA')),
                ('icao_code', models.CharField(blank=True, max_length=4, verbose_name='كود ICAO')),
                ('contact_name', models.CharField(max_length=150, verbose_name='اسم جهة الاتصال')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='مستندات الإثبات (روابط)')),
                ('requested_scopes', models.JSONField(blank=True, default=list, verbose_name='الصلاحيات المطلوبة')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الممثل الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عضو شركة نقل',
                'verbose_name_plural': 'أعضاء شركات النقل',
                'ordering': ['-is_primary', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='FlightHealthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SUSPECTED_INFECTION', 'اشتباه إصابة معدية'), ('CONFIRMED_INFECTION', 'إصابة مؤكدة'), ('SYMPTOM_ALERT', 'إنذار أعراض'), ('INFLIGHT_DEATH', 'وفاة على المتن'), ('MEDICAL_EMERGENCY', 'طوارئ طبية'), ('EXPOSURE_RISK', 'خطر تعرّض/مخالطة'), ('OTHER', 'أخرى')], default='SUSPECTED_INFECTION', max_length=25, verbose_name='الفئة')),
                ('severity', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('CRITICAL', 'حرجة')], default='MEDIUM', max_length=10, verbose_name='الخطورة')),
                ('status', models.CharField(choices=[('REPORTED', 'تم الإبلاغ'), ('UNDER_REVIEW', 'قيد المراجعة'), ('ACTION_REQUIRED', 'إجراء مطلوب'), ('RESOLVED', 'تمت المعالجة'), ('CLOSED', 'مغلق')], default='REPORTED', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('affected_count', models.PositiveIntegerField(default=1, verbose_name='عدد الحالات المؤثرة')),
                ('is_crew_related', models.BooleanField(default=False, verbose_name='تخصّ الطاقم')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='الأعراض')),
                ('reporter_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المُبلّغ')),
                ('reported_via', models.CharField(default='API', max_length=20, verbose_name='قناة الإبلاغ')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإبلاغ')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإسناد')),
                ('quarantine_state', models.CharField(blank=True, help_text='PENDING / IN_QUARANTINE / ISOLATED / RELEASED', max_length=20, verbose_name='حالة الحجر/العزل')),
                ('health_facility', models.CharField(blank=True, max_length=200, verbose_name='المرفق الصحي المعالج')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات المعالجة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التصعيد')),
                ('transmitted_to_eoc_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال الإخطار إلى EOC')),
            ],
            options={
                'verbose_name': 'حدث صحي للرحلة',
                'verbose_name_plural': 'الأحداث الصحية للرحلات',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightHealthEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20, verbose_name='من حالة')),
                ('to_status', models.CharField(max_length=20, verbose_name='إلى حالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'سجل انتقال حدث صحي',
                'verbose_name_plural': 'سجلات انتقال الأحداث الصحية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='carriermember',
            options={'ordering': ['carrier', '-is_primary', 'user__full_name'], 'verbose_name': 'عضو شركة النقل', 'verbose_name_plural': 'أعضاء شركات النقل'},
        ),
        migrations.AddField(
            model_name='carrier',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, verbose_name='عناوين IP المسموحة'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='api_error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أخطاء API'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='api_scopes',
            field=models.JSONField(blank=True, default=list, verbose_name='صلاحيات API (Scopes)'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='client_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='معرّف العميل (Client ID)'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='client_secret_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إنشاء سر العميل'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='client_secret_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='سر العميل (مُشفّر)'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='compliance_class',
            field=models.CharField(choices=[('N', 'غير مصنف'), ('B', 'برونزي'), ('S', 'فضي'), ('G', 'ذهبي')], default='N', max_length=10, verbose_name='تصنيف الامتثال'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='last_api_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر خطأ API'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='last_health_event_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة حدث صحي'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='rate_limit_daily',
            field=models.PositiveIntegerField(default=10000, verbose_name='حد الطلبات اليومي'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=120, verbose_name='حد الطلبات في الدقيقة'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'بانتظار المراجعة'), ('APPROVED', 'معتمدة'), ('REJECTED', 'مرفوضة'), ('SUSPENDED', 'موقوفة')], default='APPROVED', max_length=20, verbose_name='حالة التسجيل'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراجعة'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_carriers', to=settings.AUTH_USER_MODEL, verbose_name='راجعها'),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='نوع الطائرة/الوسيلة'),
        ),
        migrations.AddField(
            model_name='flight',
            name='crew_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أفراد الطاقم'),
        ),
        migrations.AddField(
            model_name='flight',
            name='previous_origin_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='رمز آخر محطة سابقة'),
        ),
        migrations.AddField(
            model_name='manifestpassenger',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('X', 'غير محدد')], default='X', max_length=1, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='manifestpassenger',
            name='is_crew',
            field=models.BooleanField(default=False, verbose_name='أحد أفراد الطاقم'),
        ),
        migrations.AddField(
            model_name='manifestpassenger',
            name='previous_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifest_passengers_previous', to='travelers.country', verbose_name='دولة المغادرة السابقة'),
        ),
        migrations.AlterField(
            model_name='carriermember',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='الممثل الرئيسي'),
        ),
        migrations.AlterField(
            model_name='carriermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddConstraint(
            model_name='carriermember',
            constraint=models.UniqueConstraint(fields=('user', 'carrier'), name='uq_carriermember_user_carrier'),
        ),
        migrations.AddField(
            model_name='carrierapiusagelog',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='carriers.carrier', verbose_name='شركة النقل'),
        ),
        migrations.AddField(
            model_name='carrierregistrationrequest',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='carriers.carrier', verbose_name='شركة النقل'),
        ),
        migrations.AddField(
            model_name='carrierregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_registration_reviews', to=settings.AUTH_USER_MODEL, verbose_name='راجعها'),
        ),
        migrations.AddField(
            model_name='carrierregistrationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_member', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='flighthealthevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flight_health_events', to=settings.AUTH_USER_MODEL, verbose_name='مُسند إلى'),
        ),
        migrations.AddField(
            model_name='flighthealthevent',
            name='destination_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_health_events', to='masterdata.entrypoint', verbose_name='منفذ الوصول المعني'),
        ),
        migrations.AddField(
            model_name='flighthealthevent',
            name='emergency_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_health_events', to='emergency_eoc.emergencyevent', verbose_name='حدث الطوارئ المرتبط (EOC)'),
        ),
        migrations.AddField(
            model_name='flighthealthevent',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='carriers.flight', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='flighthealthevent',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_flight_health_events', to=settings.AUTH_USER_MODEL, verbose_name='المُبلّغ (مستخدم)'),
        ),
        migrations.AddField(
            model_name='flighthealtheventlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_health_transitions', to=settings.AUTH_USER_MODEL, verbose_name='غيّرها'),
        ),
        migrations.AddField(
            model_name='flighthealtheventlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='carriers.flighthealthevent', verbose_name='الحدث'),
        ),
    ]
