# Generated by Django 5.0.14 on 2026-09-13 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _copy_user_to_submitted_by(apps, schema_editor):
    Register = apps.get_model('carriers', 'CarrierRegistrationRequest')
    for reg in Register.objects.all().only('id', 'user_id'):
        if reg.user_id:
            reg.submitted_by_id = reg.user_id
            reg.save(update_fields=['submitted_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0008_carrierapiusagelog_carrierregistrationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrierregistrationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب تسجيل شركة نقل', 'verbose_name_plural': 'طلبات تسجيل شركات النقل'},
        ),
        migrations.RemoveField(
            model_name='carrierregistrationrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='carrierregistrationrequest',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='carrierregistrationrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_registration_submissions', to=settings.AUTH_USER_MODEL, verbose_name='قدّم الطلب'),
        ),
        migrations.RunPython(
            code=_copy_user_to_submitted_by,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='carrierregistrationrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='carrierregistrationrequest',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='carriers.carrier', verbose_name='شركة النقل الناتجة'),
        ),
        migrations.AlterField(
            model_name='manifestpassenger',
            name='gender',
            field=models.CharField(choices=[('X', 'غير محدد'), ('M', 'ذكر'), ('F', 'أنثى')], default='X', max_length=1, verbose_name='الجنس'),
        ),
    ]
