# Generated by Django 5.0.14 on 2026-09-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0009_alter_carrierregistrationrequest_options_and_more'),
        ('masterdata', '0007_merge_sdpor_to_ep_port_sudan'),
        ('travelers', '0004_traveler_medical_file_no_traveler_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='company_type',
            field=models.CharField(choices=[('NATIONAL', 'شركة طيران وطنية'), ('REGIONAL', 'شركة طيران إقليمية'), ('INTERNATIONAL', 'شركة طيران دولية'), ('CARGO', 'شركة شحن جوي/بحري'), ('MARITIME', 'شركة ملاحة بحرية'), ('LAND', 'شركة نقل بري'), ('PRIVATE', 'خاصة'), ('OTHER', 'أخرى')], default='NATIONAL', max_length=20, verbose_name='نوع الشركة'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers', to='travelers.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='ports',
            field=models.ManyToManyField(blank=True, related_name='carriers', to='masterdata.entrypoint', verbose_name='المنافذ'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمدة'), ('REJECTED', 'مرفوضة'), ('SUSPENDED', 'موقوفة')], default='APPROVED', max_length=20, verbose_name='حالة التسجيل'),
        ),
    ]
