# Generated by Django 5.0.14 on 2026-09-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0011_hashed_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='api_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='بصمة مفتاح API (SHA-256)'),
        ),
    ]
