# Generated by Django 5.0.14 on 2026-10-03 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0012_alter_carrier_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإقرار')),
                ('officer_name', models.CharField(blank=True, max_length=150, verbose_name='اسم الضابط المسؤول')),
                ('officer_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف الضابط')),
                ('doctor_name', models.CharField(blank=True, max_length=150, verbose_name='اسم الطبيب على المتن')),
                ('doctor_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف الطبيب')),
                ('passenger_count', models.PositiveIntegerField(default=0, verbose_name='عدد الركاب')),
                ('crew_count', models.PositiveIntegerField(default=0, verbose_name='عدد أفراد الطاقم')),
                ('ill_passenger_count', models.PositiveIntegerField(default=0, verbose_name='عدد الحالات الممرضة')),
                ('has_medical_emergency', models.BooleanField(default=False, verbose_name='حالة طوارئ طبية')),
                ('symptoms_present', models.BooleanField(default=False, verbose_name='أعراض مرصودة على المتن')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُقدَّم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('APPROVED', 'مُعتمد'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التقديم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_declarations', to='carriers.carrier', verbose_name='شركة النقل')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_declaration', to='carriers.flight', verbose_name='الرحلة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_health_declarations', to=settings.AUTH_USER_MODEL, verbose_name='مُراجع الإقرار')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_health_declarations', to=settings.AUTH_USER_MODEL, verbose_name='مُقدِّم الإقرار')),
            ],
            options={
                'verbose_name': 'إقرار صحي',
                'verbose_name_plural': 'الإقرارات الصحية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthDeclarationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20, verbose_name='من حالة')),
                ('to_status', models.CharField(max_length=20, verbose_name='إلى حالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_declaration_transitions', to=settings.AUTH_USER_MODEL, verbose_name='غيّرها')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='carriers.healthdeclaration', verbose_name='الإقرار')),
            ],
            options={
                'verbose_name': 'سجل انتقال إقرار صحي',
                'verbose_name_plural': 'سجلات انتقال الإقرارات الصحية',
                'ordering': ['-created_at'],
            },
        ),
    ]
