# Generated by Django 5.0.14 on 2026-10-03 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0013_healthdeclaration_healthdeclarationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20, verbose_name='من حالة')),
                ('to_status', models.CharField(max_length=20, verbose_name='إلى حالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_status_transitions', to=settings.AUTH_USER_MODEL, verbose_name='غيّرها')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='carriers.flight', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'سجل انتقال حالة الرحلة',
                'verbose_name_plural': 'سجلات انتقال حالة الرحلة',
                'ordering': ['-created_at'],
            },
        ),
    ]
