# Generated by Django 5.0.14 on 2026-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0014_flightstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighthealthevent',
            name='quarantine_state',
            field=models.CharField(blank=True, choices=[('PENDING', 'معلق'), ('IN_QUARANTINE', 'في الحجر'), ('ISOLATED', 'معزول'), ('RELEASED', 'أُفرج عنه')], help_text='PENDING / IN_QUARANTINE / ISOLATED / RELEASED', max_length=20, verbose_name='حالة الحجر/العزل'),
        ),
    ]
