# Generated by Django 5.0.14 on 2026-10-03 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0015_alter_flighthealthevent_quarantine_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('AIRCRAFT_DOCUMENT', 'مستند طائرة'), ('FLIGHT_DOCUMENT', 'مستند رحلة'), ('MANIFEST_DOCUMENT', 'مستند كشف'), ('HEALTH_DOCUMENT', 'مستند صحي'), ('LICENSE', 'رخصة'), ('CERTIFICATE', 'شهادة'), ('OTHER', 'أخرى')], default='OTHER', max_length=30, verbose_name='نوع المستند')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='carrier_documents/%Y/%m/', verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='carriers.carrier', verbose_name='شركة النقل')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='carriers.flight', verbose_name='الرحلة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='رفعها')),
            ],
            options={
                'verbose_name': 'مستند ناقل',
                'verbose_name_plural': 'مستندات الناقلات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['carrier', 'document_type'], name='carriers_ca_carrier_9bbd0f_idx'), models.Index(fields=['flight'], name='carriers_ca_flight__74fb9b_idx')],
            },
        ),
    ]
