# Generated by Django 5.0.14 on 2026-08-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipinspection',
            name='accommodation_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='أماكن الإقامة'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='cleanliness_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='النظافة العامة'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='clinic_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='العيادة الطبية'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='kitchen_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='المطابخ'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='storeroom_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='المخازن'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='toilet_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='دورات المياه'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='ventilation_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='التهوية'),
        ),
        migrations.AlterField(
            model_name='shipinspection',
            name='water_tank_status',
            field=models.CharField(choices=[('COMPLIANT', 'مطابق'), ('NON_COMPLIANT', 'غير مطابق'), ('NOT_APPLICABLE', 'غير متاح')], default='COMPLIANT', max_length=20, verbose_name='خزانات المياه'),
        ),
    ]
