# Generated by Django 5.0.14 on 2026-10-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_entrypoint_location_geo'),
        ('port_health', '0002_alter_shipinspection_accommodation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaport',
            name='entry_point',
            field=models.OneToOneField(blank=True, help_text='Canonical EntryPoint (SEAPORT kind) this SeaPort extends. Scoping and permissions resolve via this relationship.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sea_port', to='masterdata.entrypoint', verbose_name='منفذ الدخول الموحد'),
        ),
    ]
