# Generated by Django 5.0.14 on 2026-10-03 13:47

from django.db import migrations
from django.db.models import F


def link_seaports_to_entrypoints(apps, schema_editor):
    """
    Link existing SeaPort records to canonical masterdata.EntryPoint.
    This migration implements the Phase 0A approved canonical mapping.

    LINK:
      PSC → EP_PORT_SUDAN
      OD  → EP_SUAKIN

    ARCHIVE (set is_active=False):
      NP  → archived (represented by T_NORTH terminal under EP_PORT_SUDAN)
      SP  → archived (represented by T_SOUTH terminal under EP_PORT_SUDAN)
      OSF → archived (phantom SeaPort, zero maritime dependencies; EP_OSEIF is LAND_PORT)

    CREATE (new SeaPort records linked to orphan SEAPORT EntryPoints):
      EP_MARSABASHAIR
      EP_ELKHAIR
      EP_ZUBEIR

    NOTE: This migration runs in test databases where masterdata may not be seeded.
    All operations are defensive — missing EntryPoints are logged but don't fail.
    """
    SeaPort = apps.get_model('port_health', 'SeaPort')
    EntryPoint = apps.get_model('masterdata', 'EntryPoint')

    def log(msg):
        # Use schema_editor.connection to avoid importing logging
        print(f'[port_health migration] {msg}')

    # --- LINK existing SeaPorts to EntryPoints ---
    # PSC → EP_PORT_SUDAN
    psc = SeaPort.objects.filter(code='PSC').first()
    ep_port_sudan = EntryPoint.objects.filter(code='EP_PORT_SUDAN').first()
    if psc and ep_port_sudan:
        psc.entry_point = ep_port_sudan
        psc.save(update_fields=['entry_point'])
        log('Linked PSC → EP_PORT_SUDAN')
    else:
        log('SKIP LINK: PSC or EP_PORT_SUDAN not found (expected in test DB without masterdata seed)')

    # OD → EP_SUAKIN
    od = SeaPort.objects.filter(code='OD').first()
    ep_suakin = EntryPoint.objects.filter(code='EP_SUAKIN').first()
    if od and ep_suakin:
        od.entry_point = ep_suakin
        od.save(update_fields=['entry_point'])
        log('Linked OD → EP_SUAKIN')
    else:
        log('SKIP LINK: OD or EP_SUAKIN not found')

    # --- ARCHIVE SeaPorts with zero maritime dependencies ---
    for code in ['NP', 'SP', 'OSF']:
        sp = SeaPort.objects.filter(code=code).first()
        if sp:
            sp.is_active = False
            sp.save(update_fields=['is_active'])
            log(f'Archived {code} (is_active=False)')

    # --- CREATE SeaPort records for orphan SEAPORT EntryPoints ---
    creates = [
        ('MBS', 'EP_MARSABASHAIR'),
        ('ELK', 'EP_ELKHAIR'),
        ('ZBR', 'EP_ZUBEIR'),
    ]
    for new_code, ep_code in creates:
        ep = EntryPoint.objects.filter(code=ep_code).first()
        if ep and not SeaPort.objects.filter(entry_point=ep).exists():
            SeaPort.objects.create(
                code=new_code,
                name_ar=ep.name_ar,
                name_en=ep.name_en or '',
                location=ep.location or '',
                is_active=ep.is_active,
                entry_point=ep,
                capacity=None,
                authorities='',
                description='Auto-created from masterdata EntryPoint (Phase 0B migration)',
            )
            log(f'Created SeaPort {new_code} linked to {ep_code}')
        else:
            log(f'SKIP CREATE: {new_code} / {ep_code} (EntryPoint missing or already linked)')


def reverse_link_seaports(apps, schema_editor):
    """
    Reverse the linking: unlink EntryPoints and restore is_active for archived ports.
    """
    SeaPort = apps.get_model('port_health', 'SeaPort')
    EntryPoint = apps.get_model('masterdata', 'EntryPoint')

    # Unlink all
    SeaPort.objects.update(entry_point=None)

    # Restore is_active for archived
    for code in ['NP', 'SP', 'OSF']:
        sp = SeaPort.objects.filter(code=code).first()
        if sp:
            sp.is_active = True
            sp.save(update_fields=['is_active'])

    # Delete created SeaPorts (by code)
    SeaPort.objects.filter(code__in=['MBS', 'ELK', 'ZBR']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('port_health', '0003_add_seaport_entry_point'),
    ]

    operations = [
        migrations.RunPython(link_seaports_to_entrypoints, reverse_link_seaports),
    ]