# Generated by Django 5.0.14 on 2026-10-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0015_alter_flighthealthevent_quarantine_state'),
        ('port_health', '0004_link_seaports_to_entrypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Canonical link to Carrier (ShippingCompany). Replaces free-text shipping_company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='carriers.carrier', verbose_name='شركة الملاحة'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=150, verbose_name='شركة الملاحة (نص حر)'),
        ),
    ]
