# Generated by Django 5.0.14 on 2026-10-03 17:45

from django.db import migrations


def map_vessels_to_carriers(apps, schema_editor):
    """
    Map existing Vessel shipping_company text values to Carrier records.

    Existing vessel shipping_company values (from seed_port_health):
      - "الخطوط البحرية السودانية" → create Carrier if not exists
      - "الشركة السودانية للملاحة" → create Carrier if not exists
      - "سيف السلام" → create Carrier if not exists
      - "الملاحة الخليجية" → create Carrier if not exists

    Also create VesselCompanyRelationship for each vessel with role=OPERATOR.
    """
    Vessel = apps.get_model('port_health', 'Vessel')
    Carrier = apps.get_model('carriers', 'Carrier')
    VesselCompanyRelationship = apps.get_model('shipping', 'VesselCompanyRelationship')

    # Mapping from vessel shipping_company text to Carrier data
    company_mapping = {
        'الخطوط البحرية السودانية': {
            'name': 'الخطوط البحرية السودانية',
            'name_en': 'Sudan Maritime Lines',
            'company_type': 'MARITIME',
            'code': 'SML',
        },
        'الشركة السودانية للملاحة': {
            'name': 'الشركة السودانية للملاحة',
            'name_en': 'Sudan Navigation Company',
            'company_type': 'MARITIME',
            'code': 'SNC',
        },
        'سيف السلام': {
            'name': 'سيف السلام',
            'name_en': 'Seif Al Salam',
            'company_type': 'MARITIME',
            'code': 'SFS',
        },
        'الملاحة الخليجية': {
            'name': 'الملاحة الخليجية',
            'name_en': 'Gulf Navigation',
            'company_type': 'MARITIME',
            'code': 'GLF',
        },
    }

    created_carriers = {}

    # Create Carrier records for each unique shipping_company
    for ship_co_name, carrier_data in company_mapping.items():
        carrier, created = Carrier.objects.get_or_create(
            name=carrier_data['name'],
            defaults={
                'name_en': carrier_data['name_en'],
                'company_type': carrier_data['company_type'],
                'iata_code': carrier_data['code'],
                'icao_code': carrier_data['code'][:4],
                'registration_status': 'APPROVED',
                'is_active': True,
            },
        )
        created_carriers[ship_co_name] = carrier

    # Map vessels to carriers
    for vessel in Vessel.objects.all():
        ship_co_name = vessel.shipping_company
        if ship_co_name and ship_co_name in created_carriers:
            carrier = created_carriers[ship_co_name]
            vessel.company = carrier
            vessel.save(update_fields=['company'])

            # Create VesselCompanyRelationship
            VesselCompanyRelationship.objects.get_or_create(
                vessel=vessel,
                company=carrier,
                role='OPERATOR',
                defaults={
                    'valid_from': vessel.arrival_date or None,
                    'is_primary': True,
                    'notes': f'Auto-mapped from legacy shipping_company: {ship_co_name}',
                },
            )


def reverse_map_vessels(apps, schema_editor):
    """Reverse: clear company FK and VesselCompanyRelationship."""
    Vessel = apps.get_model('port_health', 'Vessel')
    VesselCompanyRelationship = apps.get_model('shipping', 'VesselCompanyRelationship')

    Vessel.objects.update(company=None)
    VesselCompanyRelationship.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0015_alter_flighthealthevent_quarantine_state'),
        ('port_health', '0005_vessel_company_alter_vessel_shipping_company'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(map_vessels_to_carriers, reverse_code=migrations.RunPython.noop),
    ]