# Generated by Django 5.0.14 on 2026-10-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0016_carrierdocument'),
        ('port_health', '0006_map_vessels_to_carriers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Canonical link to Carrier (ShippingCompany): the current primary operating company. Multi-role and historical ownership is held by apps.shipping.VesselCompanyRelationship, not here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='carriers.carrier', verbose_name='شركة الملاحة'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='shipping_company',
            field=models.CharField(blank=True, help_text='DEPRECATED: legacy free-text company identity. Use `company` (ShippingCompany FK) for ownership; this column remains only until every consumer has migrated.', max_length=150, verbose_name='شركة الملاحة (نص حر — DEPRECATED)'),
        ),
    ]
