# Generated by Django 5.0.14 on 2026-10-05 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_health', '0007_alter_vessel_company_alter_vessel_shipping_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdeclaration',
            options={'ordering': ['-declaration_date', '-created_at', '-id'], 'verbose_name': 'إقرار صحي بحري', 'verbose_name_plural': 'الإقرارات الصحية البحرية'},
        ),
        migrations.AddField(
            model_name='healthdeclaration',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='healthdeclaration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة'),
        ),
        migrations.AddField(
            model_name='healthdeclaration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_maritime_declarations', to=settings.AUTH_USER_MODEL, verbose_name='مراجع الإقرار'),
        ),
        migrations.AddConstraint(
            model_name='healthdeclaration',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='ck_health_declaration_rejected_requires_reason'),
        ),
    ]
