from django.urls import path

from .views import (
    AssistantViewSet,
    ContactViewSet,
    DemoQrView,
    FoodShipmentTrackView,
    LabResultLookupView,
    PublicCountryViewSet,
    PublicDiseaseViewSet,
    PublicFlightView,
    PublicNoticeViewSet,
    PublicPortViewSet,
    PublicStatisticsView,
    SectorViewSet,
    ServiceCategoryViewSet,
    ServiceViewSet,
    TravelerLookupView,
    TravelRequirementsViewSet,
    VapidKeyView,
    VerifyCertificateView,
    VerifyQrView,
    WebPushSubscribeView,
)

urlpatterns = [
    path('contact/', ContactViewSet.as_view({'post': 'create', 'get': 'list'}), name='public-contact'),
    path('statistics/', PublicStatisticsView.as_view(), name='public-statistics'),
    path('assistant/chat/', AssistantViewSet.as_view({'post': 'chat'}), name='public-assistant-chat'),
    path('assistant/suggestions/', AssistantViewSet.as_view({'get': 'suggestions'}), name='public-assistant-suggestions'),
    path('assistant/topics/', AssistantViewSet.as_view({'get': 'topics'}), name='public-assistant-topics'),
    path('lookup/', TravelerLookupView.as_view(), name='public-traveler-lookup'),
    path('verify-qr/', VerifyQrView.as_view(), name='public-verify-qr'),
    path('verify-certificate/', VerifyCertificateView.as_view(), name='public-verify-certificate'),
    path('demo-qr/', DemoQrView.as_view(), name='public-demo-qr'),
    path('webpush/vapid-key/', VapidKeyView.as_view(), name='public-webpush-vapid-key'),
    path('webpush/subscribe/', WebPushSubscribeView.as_view(), name='public-webpush-subscribe'),
    path('laboratory/results/lookup/', LabResultLookupView.as_view(), name='public-lab-result-lookup'),
    path('sectors/', SectorViewSet.as_view({'get': 'list'}), name='public-sectors'),
    path('sectors/<uuid:pk>/', SectorViewSet.as_view({'get': 'retrieve'}), name='public-sector-detail'),
    path('sectors/<uuid:pk>/ports/', SectorViewSet.as_view({'get': 'ports'}), name='public-sector-ports'),
    path('sectors/<uuid:pk>/statistics/', SectorViewSet.as_view({'get': 'statistics'}), name='public-sector-statistics'),
    path('sectors/<uuid:pk>/news/', SectorViewSet.as_view({'get': 'news'}), name='public-sector-news'),
    path('ports/', PublicPortViewSet.as_view({'get': 'list'}), name='public-ports'),
    path('ports/map/', PublicPortViewSet.as_view({'get': 'map'}), name='public-ports-map'),
    path('ports/<uuid:pk>/', PublicPortViewSet.as_view({'get': 'retrieve'}), name='public-port-detail'),
    path('ports/<uuid:pk>/stats/', PublicPortViewSet.as_view({'get': 'stats'}), name='public-port-stats'),
    path('diseases/', PublicDiseaseViewSet.as_view({'get': 'list'}), name='public-diseases'),
    path('notices/', PublicNoticeViewSet.as_view({'get': 'list'}), name='public-notices'),
    path('travel-requirements/', TravelRequirementsViewSet.as_view({'get': 'list'}), name='public-travel-requirements'),
    path('countries/', PublicCountryViewSet.as_view({'get': 'list'}), name='public-countries'),
    path('flights/', PublicFlightView.as_view(), name='public-flight-status'),
    path('food/shipments/lookup/', FoodShipmentTrackView.as_view(), name='public-food-shipment-track'),
    path('services/', ServiceViewSet.as_view({'get': 'list'}), name='public-services'),
    path('services/<str:code>/', ServiceViewSet.as_view({'get': 'retrieve'}), name='public-service-detail'),
    path('service-categories/', ServiceCategoryViewSet.as_view({'get': 'list'}), name='public-service-categories'),
]
