# Generated by Django 5.0.14 on 2026-07-31 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
            ],
            options={
                'verbose_name': 'إحالة عيادة',
                'verbose_name_plural': 'إحالات العيادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=10, verbose_name='حالة الزيارة')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
            ],
            options={
                'verbose_name': 'زيارة عيادة',
                'verbose_name_plural': 'زيارات العيادات',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EMRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_notes', models.JSONField(blank=True, default=dict, verbose_name='الملاحظات السريرية')),
                ('vital_signs', models.JSONField(blank=True, default=dict, verbose_name='العلامات الحيوية')),
                ('physical_exam', models.JSONField(blank=True, default=dict, verbose_name='الفحص البدني')),
            ],
            options={
                'verbose_name': 'سجل طبي إلكتروني',
                'verbose_name_plural': 'السجلات الطبية الإلكترونية',
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_type', models.CharField(max_length=30, verbose_name='نوع العينة')),
                ('priority', models.CharField(choices=[('ROUTINE', 'عادي'), ('HIGH', 'عالي'), ('URGENT', 'عاجل')], default='ROUTINE', max_length=10, verbose_name='الأولوية')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='الباركود')),
                ('status', models.CharField(default='REQUESTED', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'طلب مخبري',
                'verbose_name_plural': 'الطلبات المخبرية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('generic_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم العام')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('interactions', models.JSONField(blank=True, default=list, verbose_name='التفاعلات')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(max_length=50, verbose_name='الجرعة')),
                ('frequency', models.CharField(max_length=50, verbose_name='التكرار')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدة العلاج بالأيام')),
                ('instructions', models.TextField(blank=True, verbose_name='التعليمات')),
            ],
            options={
                'verbose_name': 'وصفة طبية',
                'verbose_name_plural': 'الوصفات الطبية',
                'ordering': ['-created_at'],
            },
        ),
    ]
