# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreferral',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='ports.port', verbose_name='المنفذ'),
        ),
    ]
