# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0002_initial'),
        ('laboratory', '0001_initial'),
        ('screening', '0001_initial'),
        ('travelers', '0002_country_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreferral',
            name='screening',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_referral', to='screening.healthscreening', verbose_name='الفحص'),
        ),
        migrations.AddField(
            model_name='clinicreferral',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_referrals', to='travelers.traveler', verbose_name='المسافر'),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_visits', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب'),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinic.clinicreferral', verbose_name='الإحالة'),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='travelers.traveler', verbose_name='المسافر'),
        ),
        migrations.AddField(
            model_name='emrrecord',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emr', to='clinic.clinicvisit', verbose_name='الزيارة'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='laboratory.disease', verbose_name='المرض'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='clinic.clinicvisit', verbose_name='الزيارة'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.medication', verbose_name='الدواء'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.clinicvisit', verbose_name='الزيارة'),
        ),
    ]
