# Generated by Django 5.0.14 on 2026-09-08 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinicreferral_port'),
        ('masterdata', '0006_entrypoint_locality_healthfacility'),
        ('organization', '0006_locality'),
        ('screening', '0002_alter_healthscreening_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('kind', models.CharField(blank=True, choices=[('AIRPORT', 'مطار'), ('SEAPORT', 'ميناء بحري'), ('LAND_PORT', 'منفذ بري'), ('GENERAL', 'عام')], max_length=20, verbose_name='نوع المنفذ المناسب')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='الخدمات المقدمة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع وحدة عيادة',
                'verbose_name_plural': 'أنواع وحدات العيادات',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='clinicreferral',
            name='queue_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رقم الدور'),
        ),
        migrations.AddField(
            model_name='clinicreferral',
            name='source',
            field=models.CharField(choices=[('SCREENING', 'فحص منفذ الدخول'), ('WALK_IN', 'حضور مباشر'), ('TRANSFER', 'تحويل خارجي')], default='SCREENING', max_length=20, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='phase',
            field=models.CharField(choices=[('REGISTERED', 'مسجلة'), ('TRIAGED', 'تم الفرز'), ('EXAMINED', 'تم الفحص الطبي'), ('LABORATORY', 'مختبر'), ('DECISION', 'القرار الطبي'), ('CERTIFICATE', 'الشهادة'), ('CLOSED', 'مغلقة')], default='REGISTERED', max_length=20, verbose_name='مرحلة المعالجة'),
        ),
        migrations.AlterField(
            model_name='clinicreferral',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_referrals', to='screening.healthscreening', verbose_name='الفحص'),
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='الخدمات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('entry_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='masterdata.entrypoint', verbose_name='منفذ الدخول')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='organization.sector', verbose_name='القطاع الإداري')),
                ('clinic_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinic.clinictype', verbose_name='نوع الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة عيادة',
                'verbose_name_plural': 'وحدات العيادات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='clinicreferral',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clinic.clinic', verbose_name='وحدة العيادة'),
        ),
        migrations.AddField(
            model_name='clinicvisit',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinic.clinic', verbose_name='وحدة العيادة'),
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('DOCTOR', 'طبيب'), ('NURSE', 'ممرض'), ('LABORATORY', 'مختبر'), ('REGISTRATION', 'تسجيل'), ('ADMIN', 'إداري')], default='DOCTOR', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='clinic.clinic', verbose_name='الوحدة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_staff', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عضو كادر العيادة',
                'verbose_name_plural': 'كادر العيادات',
                'ordering': ['clinic__name_ar'],
                'unique_together': {('clinic', 'user')},
            },
        ),
    ]
