# Generated by Django 5.0.14 on 2026-09-08 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinictype_clinicreferral_queue_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'مرتفع'), ('EMERGENCY', 'طوارئ')], default='MEDIUM', max_length=20, verbose_name='درجة الخطورة')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='درجة الحرارة')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='نبض القلب')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='معدل التنفس')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='تشبع الأكسجين')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانقباضي')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='الضغط الانبساطي')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='الأعراض')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='الشكوى الرئيسية')),
                ('routing', models.CharField(choices=[('CLINIC', 'متابعة في العيادة'), ('HOSPITAL', 'تحويل للمستشفى'), ('ISOLATION', 'حجر صحي / عزل'), ('RELEASE', 'خروج')], default='CLINIC', max_length=20, verbose_name='التوجيه')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الفرز')),
                ('triaged_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفرز')),
                ('triaged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to=settings.AUTH_USER_MODEL, verbose_name='أجرى الفرز')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='clinic.clinicvisit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'سجل فرز',
                'verbose_name_plural': 'سجلات الفرز',
                'ordering': ['-triaged_at'],
            },
        ),
    ]
