# Generated by Django 5.0.14 on 2026-09-08 11:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_triagerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isolation_type', models.CharField(choices=[('HOSPITAL', 'تحويل للمستشفى'), ('CLINIC_ISOLATION', 'عزل بالعيادة'), ('QUARANTINE', 'حجر صحي إجباري')], default='CLINIC_ISOLATION', max_length=20, verbose_name='نوع العزل')),
                ('status', models.CharField(choices=[('ACTIVE', 'جاري'), ('RELEASED', 'خروج'), ('REMOVED', 'إنهاء/إلغاء')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('health_status', models.CharField(choices=[('STABLE', 'مستقر'), ('IMPROVING', 'أفضل'), ('WORSENING', 'تدهور'), ('CRITICAL', 'حرج')], default='STABLE', max_length=10, verbose_name='الحالة الصحية')),
                ('required_days', models.PositiveIntegerField(default=14, verbose_name='المدة المطلوبة (أيام)')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ البدء')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء المتوقع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('discharge_summary', models.TextField(blank=True, verbose_name='ملخص الخروج')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_isolation_records', to=settings.AUTH_USER_MODEL, verbose_name='أغلق بواسطة')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_isolation_records', to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isolation', to='clinic.clinicvisit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'سجل عزل',
                'verbose_name_plural': 'سجلات العزل',
                'ordering': ['-started_at'],
            },
        ),
    ]
