# Generated by Django 5.0.14 on 2026-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_isolationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolationrecord',
            name='severity',
            field=models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'مرتفع'), ('CRITICAL', 'حرج')], default='MEDIUM', max_length=10, verbose_name='درجة الخطورة'),
        ),
    ]
