# Generated by Django 5.0.14 on 2026-09-08 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_isolationrecord_severity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=40, unique=True, verbose_name='رقم الشهادة')),
                ('certificate_type', models.CharField(choices=[('CLEARANCE', 'شهادة خلو من الأمراض'), ('NEGATIVE', 'شهادة نتيجة سلبية'), ('MEDICAL', 'تقرير طبي')], default='CLEARANCE', max_length=20, verbose_name='نوع الشهادة')),
                ('verdict', models.CharField(choices=[('RELEASE', 'خروج/إجازة'), ('HOSPITAL', 'تحويل للمستشفى'), ('ISOLATION', 'عزل/حجر صحي')], default='RELEASE', max_length=20, verbose_name='التوصية النهائية')),
                ('decision', models.TextField(blank=True, verbose_name='مضمون القرار الطبي')),
                ('status', models.CharField(choices=[('ACTIVE', 'سارية'), ('REVOKED', 'ملغاة')], default='ACTIVE', max_length=10, verbose_name='الحالة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإصدار')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالحة حتى')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='رمز التحقق')),
                ('verification_path', models.CharField(blank=True, max_length=200, verbose_name='مسار التحقق')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_health_certificates', to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_certificate', to='clinic.clinicvisit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'شهادة صحية',
                'verbose_name_plural': 'الشهادات الصحية',
                'ordering': ['-issued_at'],
            },
        ),
    ]
