# Generated by Django 5.0.14 on 2026-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_healthcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreferral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'في الانتظار'), ('PRE_ACCEPT', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
    ]
