# Generated by Django 5.0.14 on 2026-10-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0015_alter_flighthealthevent_quarantine_state'),
        ('clinic', '0010_alter_clinicreferral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreferral',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_referrals', to='carriers.flight', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='clinicreferral',
            name='health_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_referrals', to='carriers.flighthealthevent', verbose_name='الحدث الصحي للرحلة'),
        ),
    ]
