from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from apps.accounts.models import Permission, Role, RoleAssignment, ScopeType

User = get_user_model()

RESOURCES = {
    'travelers': 'المسافرون',
    'screening': 'الفحوصات',
    'surveillance': 'الترصد الصحي',
    'laboratory': 'المختبر',
    'food': 'الغذاء',
    'emergency': 'الطوارئ',
    'reports': 'التقارير',
    'users': 'المستخدمون',
    'roles': 'الأدوار والصلاحيات',
    'ports': 'المنافذ',
    'risk': 'تقييم المخاطر',
    'notifications': 'الإشعارات',
    'settings': 'الإعدادات',
    'organization': 'الهيكل الإداري',
     'port_health': 'صحة الموانئ',
    'airport_health': 'صحة المطارات',
    'clinic': 'عيادات الحجر الصحي',
    'it': 'تقنية المعلومات',
    'db_admin': 'إدارة قاعدة البيانات',
    'chemistry': 'الكيمياء التحليلية',
    'quality': 'ضمان الجودة',
    'reagents': 'الكواشف والمواد',
    'ihr_event': 'أحداث اللوائح الصحية الدولية',
    'ihr_risk': 'تقييم مخاطر اللوائح الصحية الدولية',
    'ihr_nfp': 'نقطة الاتصال الوطنية للوائح الصحية',
    'ihr_spar': 'مؤشرات الاستعداد (SPAR)',
    'who_integration': 'تكامل منظمة الصحة العالمية',
    'who_logs': 'سجلات التكامل مع WHO',
    'who_diseases': 'الأمراض الوبائية العالمية (ICD-11)',
    'who_mappings': 'خرائط ربط ICD-11',
    'vaccination': 'التطعيم الدولي',
    'vector': 'مكافحة النواقل',
    'approval': 'الاعتماد',
    'content': 'المحتوى التوعوي',
    'finance': 'المالية والمحاسبة',
    'food_window': 'نافذة الأغذية',
    'food_samples': 'عينات الأغذية',
    'permissions': 'الصلاحيات (تعريف)',
    'role_assignments': 'تعيينات الأدوار',
}

ACTIONS = {
    'view': 'عرض',
    'add': 'إضافة',
    'edit': 'تعديل',
    'delete': 'حذف',
    'export': 'تصدير',
}

EXTRA_ACTIONS = {
    'travelers': {
        'review': 'مراجعة واعتماد طلبات المسافرين',
    },
    'ihr_event': {
        'submit': 'إرسال للمراجعة الوطنية',
        'assess': 'تقييم المخاطر',
        'approve': 'اعتماد وطني (NFP)',
        'notify': 'إخطار منظمة الصحة',
        'close': 'إغلاق',
        'reject': 'رفض',
    },
    'ihr_nfp': {
        'assign': 'تعيين نقطة اتصال وطنية',
    },
    'who_integration': {
        'test': 'اختبار الاتصال',
        'sync': 'مزامنة',
    },
    'who_diseases': {
        'sync': 'مزامنة الأمراض',
    },
    'who_mappings': {
        'review': 'مراجعة اقتراحات الربط',
        'approve': 'اعتماد اقتراحات الربط',
        'reject': 'رفض اقتراحات الربط',
        'search': 'البحث في تصنيف ICD-11',
    },
    'vaccination': {
        'issue': 'إصدار شهادات التطعيم',
        'verify': 'التحقق من شهادات التطعيم',
    },
    'vector': {
        'approve': 'اعتماد المسوحات والنتائج والعمليات',
        'close': 'إغلاق البؤر، البلاغات، وعمليات المكافحة',
        'assess': 'تقييم البلاغات وفتح البؤر',
    },
    'content': {
        'approve': 'اعتماد المحتوى',
        'publish': 'نشر المحتوى',
        'archive': 'أرشفة المحتوى',
    },
    'food_window': {
        'approve': 'اعتماد معاملات نافذة الأغذية',
    },
}

ALL_RESOURCES = list(RESOURCES.keys())


# الأدوار بخرائط الصلاحيات والنطاق الافتراضي لكل مستوى إداري
ROLES = [
    {
        'code': 'ADMIN',
        'name': 'System Administrator',
        'name_ar': 'مدير النظام',
        'description': 'صلاحيات كاملة على جميع وحدات المنصة',
        'default_scope': ScopeType.GLOBAL,
        'resources': ALL_RESOURCES,
    },
    {
        'code': 'DG_MANAGER',
        'name': 'Director General of Quarantine',
        'name_ar': 'مدير عام الحجر الصحي القومي',
        'description': 'الإشراف على جميع القطاعات واعتماد السياسات والتقارير الوطنية ومتابعة الأداء',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'reports': ['view', 'add', 'edit', 'delete', 'export'],
            'organization': ['view', 'export'],
            'travelers': ['view', 'export', 'review'],
            'screening': ['view', 'export'],
            'surveillance': ['view', 'export'],
            'laboratory': ['view'],
            'food': ['view'],
            'emergency': ['view'],
            'risk': ['view'],
            'port_health': ['view'],
            'ports': ['view'],
            'notifications': ['view'],
            'settings': ['view'],
            'ihr_event': ['view', 'export'],
            'ihr_risk': ['view'],
            'ihr_spar': ['view'],
            'who_logs': ['view'],
            'vaccination': ['view', 'export'],
        },
    },
    {
        'code': 'VICE_DG',
        'name': 'Deputy Director General',
        'name_ar': 'نائب المدير العام',
        'description': 'إدارة العمليات اليومية ومتابعة تنفيذ القرارات',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'reports': ['view', 'export'],
            'travelers': ['view', 'export'],
            'screening': ['view', 'export'],
            'surveillance': ['view', 'export'],
            'laboratory': ['view'],
            'food': ['view'],
            'emergency': ['view'],
            'risk': ['view'],
            'port_health': ['view'],
            'ports': ['view'],
            'notifications': ['view'],
            'settings': ['view'],
            'users': ['view'],
            'roles': ['view'],
        },
    },
    {
        'code': 'CENTRAL_MANAGER',
        'name': 'Central Department Manager',
        'name_ar': 'مدير إدارة مركزية',
        'description': 'إدارة تخصص على المستوى القومي (أغذية، موانئ، مطارات، معابر، مختبرات، ترصد...)',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'food': ['view', 'add', 'edit', 'export'],
            'laboratory': ['view', 'add', 'edit', 'export'],
            'port_health': ['view', 'add', 'edit', 'export'],
            'ports': ['view', 'export'],
            'screening': ['view', 'export'],
            'travelers': ['view'],
            'surveillance': ['view', 'add', 'edit', 'export'],
            'emergency': ['view'],
            'risk': ['view', 'add'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'AIRPORT_DIRECTOR',
        'name': 'Airport Quarantine Director',
        'name_ar': 'مدير الحجر الصحي بالمطار',
        'description': 'الرقابة التنفيذية على صحة المطارات: فحص الرحلات والمسافرين وصحة طاقم الطائرة والشحن الجوي',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'airport_health': ['view', 'add', 'edit', 'export'],
            'screening': ['view', 'export'],
            'surveillance': ['view', 'add', 'edit', 'export'],
            'travelers': ['view', 'review'],
            'laboratory': ['view', 'export'],
            'food': ['view', 'export'],
            'emergency': ['view'],
            'risk': ['view'],
            'ports': ['view'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'FOOD_DIRECTOR',
        'name': 'Food Safety Inspection Director',
        'name_ar': 'مدير إدارة رقابة الأغذية',
        'description': 'متابعة وتحليل الأداء الاستراتيجي لرقابة الأغذية القومية واتخاذ القرارات الإدارية المبنية على البيانات',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'food': ['view', 'add', 'edit', 'export'],
            'laboratory': ['view', 'add', 'edit', 'export'],
            'port_health': ['view', 'add', 'edit', 'export'],
            'ports': ['view', 'export'],
            'screening': ['view', 'export'],
            'surveillance': ['view', 'export'],
            'travelers': ['view'],
            'emergency': ['view'],
            'risk': ['view', 'add'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'SECTOR_MANAGER',
        'name': 'Sector Director',
        'name_ar': 'مدير القطاع',
        'description': 'إدارة جميع المحطات داخل القطاع ومتابعة مؤشرات الأداء واعتماد التقارير',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'reports': ['view', 'export'],
            'travelers': ['view', 'review'],
            'screening': ['view', 'export'],
            'surveillance': ['view', 'add', 'edit', 'export'],
            'laboratory': ['view'],
            'food': ['view'],
            'emergency': ['view'],
            'risk': ['view'],
            'port_health': ['view', 'export'],
            'ports': ['view'],
            'notifications': ['view'],
            'organization': ['view'],
            'it': ['view'],
            'ihr_event': ['view'],
        },
    },
    {
        'code': 'DEPT_MANAGER',
        'name': 'Department Manager',
        'name_ar': 'مدير إدارة القطاع',
        'description': 'إدارة قسم متخصص داخل القطاع ومتابعة رؤساء المحطات',
        'default_scope': ScopeType.DEPARTMENT,
        'resources': {
            'reports': ['view', 'export'],
            'travelers': ['view', 'review'],
            'screening': ['view', 'add', 'edit'],
            'laboratory': ['view', 'edit'],
            'food': ['view', 'edit'],
            'port_health': ['view', 'edit'],
            'risk': ['view'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'STATION_HEAD',
        'name': 'Station Head',
        'name_ar': 'رئيس المحطة / رئيس القسم',
        'description': 'مراجعة الطلبات وتوزيع المفتشين واعتماد نتائج المختبر وإصدار القرار النهائي',
        'default_scope': ScopeType.STATION,
        'resources': {
            'travelers': ['view', 'add', 'edit', 'review'],
            'screening': ['view', 'add', 'edit'],
            'laboratory': ['view', 'edit'],
            'food': ['view', 'edit'],
            'port_health': ['view', 'add', 'edit'],
            'risk': ['view'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'SECTOR_HEAD',
        'name': 'Food Safety Sector Head',
        'name_ar': 'مدير إدارة رقابة الأغذية بالقطاع',
        'description': 'إشراف قطاعي على منافذ رقابة الأغذية: مقارنة أداء المنافذ ومتابعة رؤساء الأقسام والمخاطر والإنفاذ',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'food': ['view', 'export'],
            'laboratory': ['view'],
            'risk': ['view'],
            'reports': ['view', 'export'],
            'ports': ['view'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'CLERK',
        'name': 'Clerk',
        'name_ar': 'الكاتب',
        'description': 'تسجيل الطلبات وإدخال البيانات ورفع المستندات',
        'default_scope': ScopeType.STATION,
        'resources': {
            'travelers': ['view', 'add', 'edit'],
            'screening': ['view', 'add'],
            'port_health': ['view', 'add'],
            'food': ['view', 'add'],
            'laboratory': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'LAB_RECEPTIONIST',
        'name': 'Sample Reception Officer',
        'name_ar': 'موظف استلام العينات',
        'description': 'أول نقطة دخول للعينة: إنشاء سجل العينة ومصدرها وبيانات المنتج ونوعها وكميتها وفحص حالتها واتخاذ قرار القبول/الرفض وطباعة الباركود وتسجيل سلسلة الحيازة. لا يدخل نتائج التحليل ولا يعدل المواصفات ولا يعتمد النتائج.',
        'default_scope': ScopeType.STATION,
        'resources': {
            'food': ['view', 'add', 'edit'],
            'laboratory': ['view'],
            'travelers': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'LAB_COORDINATOR',
        'name': 'Sample Coordinator',
        'name_ar': 'منسق عينات المختبر',
        'description': 'حلقة الوصل بين الاستلام والأقسام الفنية: مشاهدة العينات المقبولة وتصنيفها وتوزيعها وإنشاء أوامر التحليل وإرسالها للكيمياء أو الميكروبيولوجي وتحديد أولوية التحليل ومتابعة SLA وإعادة التوزيع. لا يدخل نتائج التحليل ولا يعتمدها.',
        'default_scope': ScopeType.STATION,
        'resources': {
            'food': ['view', 'add', 'edit'],
            'laboratory': ['view'],
            'travelers': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'ACCOUNTANT',
        'name': 'Accountant',
        'name_ar': 'المحاسب',
        'description': 'إصدار الفواتير وتحصيل الرسوم وإصدار الإيصالات',
        'default_scope': ScopeType.STATION,
        'resources': {
            'port_health': ['view', 'add', 'edit'],
            'food': ['view', 'add', 'edit'],
            'travelers': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'QUARANTINE_INSPECTOR',
        'name': 'Quarantine Health Inspector',
        'name_ar': 'مفتش الحجر الصحي',
        'description': 'التفتيش الصحي وتسجيل نتائج الزيارة والتوصية بالإجراءات',
        'default_scope': ScopeType.STATION,
        'resources': {
            'port_health': ['view', 'add', 'edit'],
            'screening': ['view', 'add', 'edit'],
            'surveillance': ['view', 'add', 'edit'],
            'travelers': ['view'],
            'food': ['view'],
            'laboratory': ['view'],
            'risk': ['view', 'add'],
            'reports': ['view'],
            'notifications': ['view'],
            'vaccination': ['view', 'add', 'verify'],
        },
    },
    {
        'code': 'EOC_OPERATOR',
        'name': 'Emergency Operations Centre Operator',
        'name_ar': 'مشغل غرفة عمليات الطوارئ',
        'description': 'متابعة الإنذارات والتدقيق على الحالات الوبائية وتأكيدها وتنسيق الاستجابة الميدانية',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'surveillance': ['view', 'add', 'edit', 'export'],
            'emergency': ['view', 'add', 'edit', 'export'],
            'screening': ['view', 'export'],
            'travelers': ['view', 'export'],
            'laboratory': ['view', 'export'],
            'food': ['view', 'export'],
            'risk': ['view', 'add'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'ports': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'EPIDEMIC_CONTROL_MANAGER',
        'name': 'Epidemic Control Manager',
        'name_ar': 'مدير مكافحة الأوبئة',
        'description': 'إدارة الترصد الصحي على المستوى القطاعي/القومي: تهيئة الأمراض واجبة الإبلاغ، الإشراف على محركات الإنذار المبكر (EWARS)، تحليل الاتجاهات، تنسيق الاستجابة الوبائية، التحقيقات الميدانية، والإبلاغ الإقليمي/الدولي',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'surveillance': ['view', 'add', 'edit', 'delete', 'export'],
            'emergency': ['view', 'add', 'edit', 'export'],
            'screening': ['view', 'export'],
            'travelers': ['view', 'export'],
            'laboratory': ['view', 'add', 'edit', 'export'],
            'food': ['view', 'export'],
            'risk': ['view', 'add', 'edit'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'ports': ['view'],
            'organization': ['view'],
            'ihr_event': ['view', 'add', 'submit', 'assess'],
            'ihr_risk': ['view', 'add'],
            'ihr_spar': ['view'],
        },
    },
    {
        'code': 'AIRPORT_INSPECTOR',
        'name': 'Airport Health Inspector',
        'name_ar': 'مفتش الحجر الصحي في المطار',
        'description': 'تفتيش الرحلات والمسافرين في المطار وتسجيل نتائج الفحص والإحالة',
        'default_scope': ScopeType.STATION,
        'resources': {
            'airport_health': ['view', 'add', 'edit'],
            'screening': ['view', 'add', 'edit'],
            'travelers': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'FOOD_INSPECTOR',
        'name': 'Food Safety Inspector',
        'name_ar': 'مفتش رقابة الأغذية',
        'description': 'فحص الشحنات الغذائية وسحب العينات وإعداد تقرير التفتيش',
        'default_scope': ScopeType.STATION,
        'resources': {
            'food': ['view', 'add', 'edit', 'delete'],
            'laboratory': ['view', 'add'],
            'reports': ['view'],
            'travelers': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'ENV_INSPECTOR',
        'name': 'Environmental Health Inspector',
        'name_ar': 'مفتش صحة البيئة',
        'description': 'فحص الاشتراطات البيئية ومتابعة مكافحة النواقل وإعداد التقارير البيئية',
        'default_scope': ScopeType.STATION,
        'resources': {
            'port_health': ['view', 'add', 'edit'],
            'surveillance': ['view', 'add', 'edit'],
            'emergency': ['view'],
            'risk': ['view'],
            'reports': ['view', 'add'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'NATIONAL_LAB_ADMIN',
        'name': 'National Laboratory Administration',
        'name_ar': 'الإدارة القومية للمعامل',
        'description': 'الإشراف القومي على المعامل القطاعية: متابعة جميع القطاعات، لوحة القيادة الوطنية، تقييم أداء المعامل، اعتماد النتائج الوطنية ومراقبة الكواشف والأجهزة',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'laboratory': ['view', 'add', 'edit', 'delete', 'export'],
            'chemistry': ['view', 'add', 'edit', 'export'],
            'quality': ['view', 'add', 'edit', 'delete'],
            'reagents': ['view', 'add', 'edit', 'delete'],
            'reports': ['view', 'add', 'edit', 'export'],
            'users': ['view', 'add', 'edit'],
            'organization': ['view', 'export'],
            'emergency': ['view'],
            'surveillance': ['view', 'export'],
            'notifications': ['view'],
            'settings': ['view'],
        },
    },
    {
        'code': 'LAB_MANAGER',
        'name': 'Laboratory Manager',
        'name_ar': 'مسؤول المختبر',
        'description': 'استلام العينات وتوزيعها على الفنيين واعتماد النتائج وإرسالها للنظام',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'add', 'edit', 'delete'],
            'reports': ['view', 'add'],
            'travelers': ['view'],
            'port_health': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'LAB_DIRECTOR',
        'name': 'Laboratory Director',
        'name_ar': 'مدير المختبر',
        'description': 'الإشراف على جميع أقسام المختبر، اعتماد النتائج النهائية، مراقبة الجودة وSLA والطاقة التشغيلية، متابعة عدم المطابقة. لا يدخل نتائج التحاليل بنفسه بل يراجع ويعتمد ما تمت مراجعته من رؤساء الأقسام.',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'add', 'edit', 'delete'],
            'reports': ['view', 'add', 'edit'],
            'travelers': ['view'],
            'port_health': ['view'],
            'notifications': ['view'],
            'approval': ['view', 'add', 'edit'],
        },
    },
    {
        'code': 'LAB_TECHNICIAN',
        'name': 'Laboratory Technician',
        'name_ar': 'فني المختبر',
        'description': 'إجراء التحاليل وإدخال النتائج وتوثيق الفحوصات',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'add', 'edit'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'CHEM_SECTION_HEAD',
        'name': 'Chemistry Section Head',
        'name_ar': 'رئيس قسم الكيمياء',
        'description': 'إدارة عينات الكيمياء وتوزيعها على المحللين ومتابعة التحاليل ومراجعة النتائج ومراجعة الجودة (QC) ومراقبة الأجهزة ومتابعة SLA',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'add', 'edit'],
            'reports': ['view'],
            'travelers': ['view'],
            'port_health': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'CHEM_ANALYST',
        'name': 'Chemistry Analyst',
        'name_ar': 'محلل كيميائي',
        'description': 'تنفيذ التحاليل الكيميائية وإدخال النتائج وحفظ السجلات وإدارة عينات الكيمياء',
        'default_scope': ScopeType.STATION,
        'resources': {
            'chemistry': ['view', 'add', 'edit'],
            'laboratory': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
            'travelers': ['view'],
        },
    },
    {
        'code': 'MICRO_SECTION_HEAD',
        'name': 'Microbiology Section Head',
        'name_ar': 'رئيس قسم الأحياء الدقيقة',
        'description': 'توزيع عينات الأحياء الدقيقة على المحللين ومتابعة عبء العمل ومراجعة النتائج ومراجعة الحدود الميكروبيولوجية (n/c/m/M) ومراجعة الجودة (QC) ومتابعة SLA. لا يعتمد النتيجة نهائياً ولا يعدل النتائج بنفسه ولا يعدل المواصفات',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'add', 'edit'],
            'reports': ['view'],
            'travelers': ['view'],
            'port_health': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'MICRO_ANALYST',
        'name': 'Microbiology Analyst',
        'name_ar': 'محلل الأحياء الدقيقة',
        'description': 'تنفيذ التحليل الميكروبيولوجي وتوثيق كل مرحلة (الزراعة، الحضانة، القراءة، العدّ الميكروبي، النتائج النوعية) وإدخال النتائج وإرسالها لرئيس قسم الأحياء الدقيقة للمراجعة. لا يعدل المواصفة ولا يعتمد النتائج ولا يحذف النتائج',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'add', 'edit'],
            'reports': ['view'],
            'notifications': ['view'],
            'settings': ['view'],
        },
    },
    {
        'code': 'QUALITY_ASSURANCE',
        'name': 'Quality Assurance Officer',
        'name_ar': 'مسؤول الجودة',
        'description': 'مراقبة سلامة النظام الفني للمختبر: المواصفات الميكروبيولوجية (n/c/m/M)، طرق الاختبار، مراجعة الجودة (QC)، المعايرة، الكواشف، الوثائق، عدم المطابقة (NC)، CAPA، وسجل التدقيق (Audit Trail). لا يعدل نتائج المحللين ولا يعتمد النتيجة النهائية ولا يدير المستخدمين ولا الرسوم',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'edit'],
            'reports': ['view'],
            'notifications': ['view'],
            'quality': ['view', 'add', 'edit'],
        },
    },
    {
        'code': 'IT_ADMIN',
        'name': 'IT Administrator',
        'name_ar': 'مسؤول تقنية المعلومات',
        'description': 'إدارة المستخدمين والخوادم ومراقبة النظام والدعم الفني',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'db_admin': ['view'],
            'users': ['view', 'add', 'edit', 'delete'],
            'roles': ['view'],
            'settings': ['view', 'add', 'edit'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'SECTOR_IT_MANAGER',
        'name': 'Sector IT Manager',
        'name_ar': 'مدير تقنية المعلومات للقطاع',
        'description': 'إدارة أنظمة تقنية المعلومات والأصول والتذاكر والشبكات والتقارير الفنية داخل القطاع',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'it': ['view', 'add', 'edit', 'delete', 'export'],
            'users': ['view'],
            'settings': ['view', 'edit'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'DBA_ADMIN',
        'name': 'Database Administrator',
        'name_ar': 'مسؤول قاعدة البيانات',
        'description': 'إدارة قواعد البيانات والنسخ الاحتياطي وتحسين الأداء',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'db_admin': ['view', 'add', 'edit', 'delete', 'export'],
            'settings': ['view', 'edit'],
            'users': ['view'],
            'roles': ['view'],
            'reports': ['view'],
        },
    },
    {
        'code': 'SECTOR_CONTENT_CONTRIBUTOR',
        'name': 'Sector Content Contributor',
        'name_ar': 'محرر محتوى قطاعي',
        'description': 'إنشاء وتعديل المسودات وإرسالها للمراجعة ضمن قطاعه',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'content': ['view', 'add', 'edit'],
            'reports': ['view'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'SECTOR_CONTENT_EDITOR',
        'name': 'Sector Content Editor',
        'name_ar': 'محرر محتوى قطاعي متقدم',
        'description': 'تحرير المحتوى وإعادة صياغته وإرساله للمراجعة ضمن قطاعه',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'content': ['view', 'add', 'edit'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'SECTOR_CONTENT_REVIEWER',
        'name': 'Sector Content Reviewer',
        'name_ar': 'مراجع محتوى قطاعي',
        'description': 'مراجعة المحتوى المقدَّم واعتماده أو إعادته للمسودة ضمن قطاعه',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'content': ['view', 'add', 'edit', 'approve'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'SECTOR_CONTENT_APPROVER',
        'name': 'Sector Content Approver',
        'name_ar': 'معتمد محتوى قطاعي',
        'description': 'النشر والأرشفة النهائية للمحتوى المعتمد ضمن قطاعه',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'content': ['view', 'add', 'edit', 'approve', 'publish', 'archive', 'delete'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
        },
    },
    {
        'code': 'NATIONAL_CONTENT_ADMIN',
        'name': 'National Content Administrator',
        'name_ar': 'مدير المحتوى القومي',
        'description': 'إشراف قومي على كل حسابات المحتوى: اعتماد ونشر وأرشفة عبر جميع القطاعات',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'content': ['view', 'add', 'edit', 'approve', 'publish', 'archive', 'delete'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
            'organization': ['view'],
            'users': ['view'],
        },
    },
    {
        'code': 'FOOD_WINDOW_CLERK',
        'name': 'Food Window Clerk',
        'name_ar': 'موظّف نافذة الأغذية',
        'description': 'تسجيل ومعالجة معاملات الشحنات على نافذة الأغذية (نطاق منفذ معيّن + سلع مدعومة)',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'food_window': ['view', 'add', 'edit'],
            'food_samples': ['view'],
            'reports': ['view'],
        },
    },
    {
        'code': 'FOOD_WINDOW_SUPERVISOR',
        'name': 'Food Window Supervisor',
        'name_ar': 'مشرف نافذة الأغذية',
        'description': 'إشراف على نوافذ الأغذية: اعتماد قرارات السلع وإغلاق المعاملات وتعيين الموظفين',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'food_window': ['view', 'add', 'edit', 'approve', 'delete'],
            'food_samples': ['view'],
            'reports': ['view', 'export'],
            'users': ['view'],
        },
    },
    {
        'code': 'AUDIT_ADMIN',
        'name': 'Security Administrator',
        'name_ar': 'مسؤول أمن المعلومات',
        'description': 'إدارة سياسات الأمن ومراجعة سجلات التدقيق ومتابعة الحوادث الأمنية',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'travelers': ['view'],
            'screening': ['view'],
            'laboratory': ['view'],
            'food': ['view'],
            'port_health': ['view'],
            'users': ['view'],
            'roles': ['view'],
            'settings': ['view'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'INTERNAL_AUDITOR',
        'name': 'Internal Auditor',
        'name_ar': 'المراجع الداخلي',
        'description': 'الاطلاع على التقارير ومراجعة العمليات ومتابعة الالتزام بالإجراءات',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'travelers': ['view'],
            'screening': ['view'],
            'laboratory': ['view'],
            'food': ['view'],
            'port_health': ['view'],
            'ports': ['view'],
            'risk': ['view'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'STANDARDS_OFFICER',
        'name': 'Standards & Compliance Officer',
        'name_ar': 'مسؤول المواصفات والمطابقة',
        'description': 'إدارة المواصفات والمعايير المرجعية (SSMO/GSO/Codex/ISO/AOAC)، الإصدارات، المتطلبات، الطرق التحليلية، وقواعد التطبيق التنظيمية. مراجعة وتحديث المواصفات، مقارنة المصادر، اعتماد التغييرات، وإدارة تاريخ السريان. لا يدخل نتائج التحاليل ولا يعتمد النتائج النهائية.',
        'default_scope': ScopeType.STATION,
        'resources': {
            'laboratory': ['view', 'edit'],
            'reports': ['view'],
            'quality': ['view', 'add', 'edit'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'CLINIC_DOCTOR',
        'name': 'Clinic Doctor',
        'name_ar': 'طبيب عيادة الحجر الصحي',
        'description': 'إدارة زيارات العيادات وتوثيق السجلات الطبية الإلكترونية وطلبات المختبر والوصفات الطبية للمسافرين المحولين من بوابة الفحص',
        'default_scope': ScopeType.POINT,
        'resources': {
            'clinic': ['view', 'add', 'edit', 'export'],
            'screening': ['view'],
            'travelers': ['view'],
            'laboratory': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
            'vaccination': ['view', 'add', 'edit', 'issue', 'verify'],
        },
    },
    {
        'code': 'NATIONAL_IT_DIRECTOR',
        'name': 'National IT Director',
        'name_ar': 'مدير تقنية المعلومات القومي',
        'description': 'الإشراف القومي على الأنظمة والبنية التحتية والأمن السيبراني والتكاملات الحكومية عبر جميع القطاعات، دون صلاحية تعديل البيانات الصحية أو المالية',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'it': ['view', 'add', 'edit', 'delete', 'export'],
            'users': ['view', 'add', 'edit'],
            'roles': ['view'],
            'settings': ['view', 'edit'],
            'reports': ['view', 'export'],
            'organization': ['view'],
            'notifications': ['view'],
            'who_integration': ['view', 'test'],
            'who_logs': ['view'],
        },
    },
    {
        'code': 'IHR_NFP',
        'name': 'National IHR Focal Point',
        'name_ar': 'نقطة الاتصال الوطنية للوائح الصحية الدولية (NFP)',
        'description': 'المرجع الوطني الوحيد المعتمد لدى منظمة الصحة العالمية: استقبال أحداث IHR بعد مراجعة الترصد والتقييم، الاعتماد الوطني، وإخطار منظمة الصحة. دون الصلاحية التقنية للتكامل (test/sync) ودون تعديل إعدادات WHOS. لا يُمنح إلا على المستوى القومي.',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'ihr_event': ['view', 'add', 'edit', 'export', 'submit', 'assess', 'approve', 'notify', 'close', 'reject'],
            'ihr_risk': ['view', 'add'],
            'ihr_nfp': ['view', 'assign'],
            'ihr_spar': ['view', 'export'],
            'surveillance': ['view', 'export'],
            'risk': ['view', 'add'],
            'reports': ['view', 'export'],
            'who_logs': ['view'],
            'who_diseases': ['view'],
            'who_mappings': ['view', 'review', 'approve', 'reject', 'export'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'WHO_INTEGRATION_OFFICER',
        'name': 'WHO Integration Officer',
        'name_ar': 'مسؤول التكامل مع منظمة الصحة العالمية',
        'description': 'المسؤول التقني لتكامل WHOS: اختبار الاتصال والمزامنة وسجلات التكامل وأمراض ICD-11 ومراقبة أحداث IHR المرسلة. لا يملك الاعتماد الوطني ولا إخطار الجهة المستجيبة ولا تعيين نقطة الاتصال (فصل مهام صارم).',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'who_integration': ['view', 'edit', 'test', 'sync', 'export'],
            'who_logs': ['view', 'export'],
            'who_diseases': ['view', 'edit', 'sync', 'export'],
            'who_mappings': ['view', 'add', 'edit', 'export', 'search'],
            'ihr_event': ['view'],
            'ihr_spar': ['view'],
            'it': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'NATIONAL_SURVEILLANCE_OFFICER',
        'name': 'National Surveillance Officer',
        'name_ar': 'مسؤول الترصد الصحي القومي',
        'description': 'المستوى القومي للترصد: متابعة البلاغات من القطاعات والمنافذ، تقييم المخاطر، والتوصية بالتصعيد إلى نقطة الاتصال الوطنية. لا يعتمد ولا يُخطِر منظمة الصحة ولا يدير تكامل WHO.',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'surveillance': ['view', 'add', 'edit', 'export'],
            'ihr_event': ['view', 'add', 'edit', 'submit', 'assess'],
            'ihr_risk': ['view', 'add'],
            'ihr_spar': ['view', 'add', 'edit'],
            'risk': ['view', 'add'],
            'emergency': ['view'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'SECTOR_IHR_OFFICER',
        'name': 'Sector IHR Officer',
        'name_ar': 'مسؤول اللوائح الصحية الدولية بالقطاع',
        'description': 'تجمع بلاغات المنافذ ضمن قطاعه، يقيّم المخاطر المبدئي ويرفع الأحداث للمراجعة الوطنية. لا يعتمد ولا يُخطِر منظمة الصحة ولا يطّلع على تكامل WHOS (نطاق قطاعي فقط).',
        'default_scope': ScopeType.SECTOR,
        'resources': {
            'surveillance': ['view', 'add', 'edit', 'export'],
            'ihr_event': ['view', 'add', 'edit', 'submit', 'assess'],
            'ihr_risk': ['view', 'add'],
            'risk': ['view', 'add'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'POE_HEALTH_OFFICER',
        'name': 'Point of Entry Health Officer',
        'name_ar': 'مسؤول الصحة بمنفذ الدخول',
        'description': 'المستوى الميداني: تسجيل الحالات المشتبهة والفحص الصحي بالمنفذ وإنشاء أحداث IHR (مسودة فقط). لا يرفع للمراجعة الوطنية ولا يعتمد ولا يطّلع على تكامل WHO. يُمنح على نطاق منفذ واحد.',
        'default_scope': ScopeType.POINT,
        'resources': {
            'screening': ['view', 'add', 'edit'],
            'clinic': ['view'],
            'ihr_event': ['view', 'add', 'edit'],
            'ihr_risk': ['view', 'add'],
            'risk': ['view', 'add'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'VACCINATION_MANAGER',
        'name': 'National Vaccination Manager',
        'name_ar': 'مدير التطعيم الدولي القومي',
        'description': 'الإدارة الكاملة لمنظومة التطعيم الدولي: اللقاحات والتشغيلات والمخزون والعيادات وقواعد التقييم والإصدار والتحقق والتقارير على المستوى القومي.',
        'default_scope': ScopeType.GLOBAL,
        'resources': {
            'vaccination': ['view', 'add', 'edit', 'delete', 'export', 'issue', 'verify'],
            'travelers': ['view', 'export'],
            'reports': ['view', 'export'],
            'notifications': ['view'],
        },
    },
    {
        'code': 'VACCINATION_OFFICER',
        'name': 'Vaccination Officer',
        'name_ar': 'مسؤول التطعيم',
        'description': 'تسجيل المسافرين وإعطاء الجرعات وإصدار الشهادات وإجراء التحقق — داخل عيادة أو نقطة تطعيم تابعة لمنفذ (نطاق منفذ).',
        'default_scope': ScopeType.POINT,
        'resources': {
            'vaccination': ['view', 'add', 'edit', 'issue', 'verify'],
            'travelers': ['view'],
            'reports': ['view'],
            'notifications': ['view'],
        },
    },
]


def resolve_permission_codes(resources) -> list[str]:
    if resources == ALL_RESOURCES:
        codes = []
        for res in ALL_RESOURCES:
            codes += [f'{res}:{act}' for act in ACTIONS]
            codes += [f'{res}:{act}' for act in EXTRA_ACTIONS.get(res, {})]
        return codes
    return [f'{res}:{action}' for res, actions in resources.items() for action in actions]


class Command(BaseCommand):
    help = 'بذر الصلاحيات والأدوار الافتراضية لنظام الصلاحيات (RBAC)'

    def handle(self, *args, **options):
        created_perms = 0
        updated_perms = 0
        for resource, resource_ar in RESOURCES.items():
            actions = {**ACTIONS, **EXTRA_ACTIONS.get(resource, {})}
            for action, action_ar in actions.items():
                code = f'{resource}:{action}'
                _, created = Permission.objects.update_or_create(
                    code=code,
                    defaults={
                        'name': f'{action_ar} {resource_ar}',
                        'resource': resource,
                        'action': action,
                    },
                )
                if created:
                    created_perms += 1
                else:
                    updated_perms += 1

        created_roles = 0
        updated_roles = 0
        for role_def in ROLES:
            role, created = Role.objects.update_or_create(
                code=role_def['code'],
                defaults={
                    'name': role_def['name'],
                    'name_ar': role_def['name_ar'],
                    'description': role_def.get('description', ''),
                    'default_scope': role_def['default_scope'],
                },
            )
            codes = resolve_permission_codes(role_def['resources'])
            role.permissions.set(Permission.objects.filter(code__in=codes))
            if created:
                created_roles += 1
            else:
                updated_roles += 1

        created_assignments = 0
        admin_role = Role.objects.filter(code='ADMIN').first()
        if admin_role:
            for user in User.objects.filter(is_staff=True, is_active=True):
                _, created = RoleAssignment.objects.get_or_create(
                    user=user,
                    role=admin_role,
                    scope_type=ScopeType.GLOBAL,
                    defaults={
                        'is_active': True,
                        'assigned_by': user,
                    },
                )
                if created:
                    created_assignments += 1

        total_perms = sum(
            len({**ACTIONS, **EXTRA_ACTIONS.get(res, {})}) for res in RESOURCES
        )
        self.stdout.write(
            self.style.SUCCESS(
                f'تم البذر بنجاح: {total_perms} صلاحية '
                f'({created_perms} جديدة، {updated_perms} محدثة) و {len(ROLES)} دور '
                f'({created_roles} جديدة، {updated_roles} محدثة) '
                f'و {created_assignments} تعيين دور جديد'
            )
        )