# Generated by Django 5.0.14 on 2026-08-04 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('region', models.CharField(blank=True, max_length=30, verbose_name='المنطقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('color', models.CharField(default='#0a6b58', max_length=9, verbose_name='اللون')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قطاع إداري',
                'verbose_name_plural': 'القطاعات الإدارية',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='OrgPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='المستوى الهرمي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.orgposition', verbose_name='المنصب الأعلى')),
            ],
            options={
                'verbose_name': 'منصب قيادي',
                'verbose_name_plural': 'المناصب القيادية',
                'ordering': ['level', 'order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('manager_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='organization.orgposition', verbose_name='المنصب المسؤول')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'قسم رئيسي',
                'verbose_name_plural': 'الأقسام الرئيسة',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='OrgAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='التعيين الرئيسي')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.department', verbose_name='القسم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_assignments', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.orgposition', verbose_name='المنصب')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'تعيين هيكلي',
                'verbose_name_plural': 'التعيينات الهيكلية',
                'ordering': ['-is_primary', '-start_date', '-created_at'],
            },
        ),
    ]
