# Generated by Django 5.0.14 on 2026-08-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name_ar'], 'verbose_name': 'قسم/وحدة', 'verbose_name_plural': 'الأقسام والوحدات'},
        ),
        migrations.AddField(
            model_name='department',
            name='kind',
            field=models.CharField(choices=[('DEPARTMENT', 'قسم رئيسي'), ('UNIT', 'وحدة فرعية'), ('ENTRY_POINT', 'نقطة دخول'), ('ENTRY_GROUP', 'مجموعة نقاط الدخول')], default='DEPARTMENT', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.department', verbose_name='القسم الأعلى'),
        ),
    ]
