# Generated by Django 5.0.14 on 2026-08-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_options_department_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.department', verbose_name='الوحدة/القسم'),
        ),
    ]
