# Generated by Django 5.0.14 on 2026-09-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_entrypoint_address_entrypoint_email_entrypoint_phone'),
        ('organization', '0004_station_orgassignment_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgassignment',
            name='entry_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_assignments', to='masterdata.entrypoint', verbose_name='نقطة الدخول'),
        ),
    ]
