# Generated by Django 5.0.14 on 2026-09-07 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_orgassignment_entry_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='الموقع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'محلية',
                'verbose_name_plural': 'المحليات',
                'ordering': ['order', 'name_ar'],
            },
        ),
    ]
