# Generated by Django 5.0.14 on 2026-10-03 17:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0015_alter_flighthealthevent_quarantine_state'),
        ('masterdata', '0008_entrypoint_location_geo'),
        ('port_health', '0005_vessel_company_alter_vessel_shipping_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('agent_type', models.CharField(choices=[('PORT_AGENT', 'وكيل ميناء'), ('SHIP_AGENT', 'وكيل سفينة'), ('CARGO_AGENT', 'وكيل شحن'), ('MANNING_AGENT', 'وكيل طاقم'), ('PROTECTING_AGENT', 'وكيل حماية')], default='PORT_AGENT', max_length=20, verbose_name='نوع الوكيل')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الترخيص')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='جهة الاتصال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACTIVE', 'نشط'), ('SUSPENDED', 'موقوف'), ('REVOKED', 'ملغى'), ('EXPIRED', 'منتهي')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='ساري من')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_agents', to='carriers.carrier', verbose_name='شركة الملاحة')),
                ('ports', models.ManyToManyField(blank=True, related_name='shipping_agents', to='masterdata.entrypoint', verbose_name='المنافذ المصرح بها')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'وكيل ملاحي',
                'verbose_name_plural': 'الوكلاء الملاحيون',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('STATUS_CHANGE', 'تغيير الحالة'), ('ASSIGN', 'إسناد'), ('REVOKE', 'إلغاء إسناد'), ('LICENSE_RENEW', 'تجديد ترخيص')], max_length=20, verbose_name='الفعل')),
                ('object_type', models.CharField(max_length=60, verbose_name='نوع الكائن')),
                ('object_id', models.CharField(max_length=80, verbose_name='معرّف الكائن')),
                ('object_label', models.CharField(blank=True, max_length=255, verbose_name='وصف الكائن')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق ملاحي',
                'verbose_name_plural': 'سجلات التدقيق الملاحي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VesselCompanyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'مالك'), ('OPERATOR', 'مشغل'), ('MANAGER', 'مدير'), ('CHARTERER', 'مستأجر')], default='OPERATOR', max_length=20, verbose_name='الدور')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='ساري من')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الدور الأساسي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_relationships', to='carriers.carrier', verbose_name='شركة الملاحة')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_relationships', to='port_health.vessel', verbose_name='السفينة')),
            ],
            options={
                'verbose_name': 'علاقة شركة بسفينة',
                'verbose_name_plural': 'علاقات الشركات بالسفن',
                'ordering': ['vessel', '-is_primary', 'role'],
            },
        ),
        migrations.AddConstraint(
            model_name='shippingagent',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number__gt', '')), fields=('company', 'license_number'), name='uq_shipping_agent_company_license'),
        ),
        migrations.AddConstraint(
            model_name='vesselcompanyrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vessel', 'company', 'role'), name='uq_vessel_company_role'),
        ),
    ]
