# Generated by Django 5.0.14 on 2026-10-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0016_carrierdocument'),
        ('port_health', '0006_map_vessels_to_carriers'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vesselcompanyrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('vessel', 'company', 'role'), name='uq_vessel_company_role_primary_active'),
        ),
        migrations.AddConstraint(
            model_name='vesselcompanyrelationship',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='ck_vessel_company_valid_dates'),
        ),
    ]
