# Generated by Django 5.0.14 on 2026-10-03 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_health', '0007_alter_vessel_company_alter_vessel_shipping_company'),
        ('shipping', '0002_vesselcompanyrelationship_uq_vessel_company_role_primary_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreArrivalNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُقدَّم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=20, verbose_name='حالة الإخطار')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('remarks', models.TextField(blank=True, verbose_name='ملاحظات مقدّم الإخطار')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_arrival_reviews', to=settings.AUTH_USER_MODEL, verbose_name='راجع الإخطار')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_arrival_submissions', to=settings.AUTH_USER_MODEL, verbose_name='قدّم الإخطار')),
                ('vessel_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_arrival_notification', to='port_health.vesselvisit', verbose_name='زيارة السفينة (نداء الميناء)')),
            ],
            options={
                'verbose_name': 'إخطار مسبق بسفينة',
                'verbose_name_plural': 'الإخطارات المسبقة للسفن',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='prearrivalnotification',
            constraint=models.CheckConstraint(check=models.Q(('reviewed_at__isnull', True), ('status__in', ['UNDER_REVIEW', 'ACCEPTED', 'REJECTED']), _connector='OR'), name='ck_pre_arrival_reviewed_at_requires_review'),
        ),
    ]
