# Generated by Django 5.0.14 on 2026-10-04 03:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_health', '0007_alter_vessel_company_alter_vessel_shipping_company'),
        ('shipping', '0003_prearrivalnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('STATUS_CHANGE', 'تغيير الحالة'), ('ASSIGN', 'إسناد'), ('REVOKE', 'إلغاء إسناد'), ('LICENSE_RENEW', 'تجديد ترخيص'), ('CLEARANCE_DECISION_RECORDED', 'تسجيل قرار إفراج')], max_length=32, verbose_name='الفعل'),
        ),
        migrations.CreateModel(
            name='PortClearanceDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('CLEARED', 'مُفرج عنها'), ('CONDITIONAL', 'إفراج مشروط'), ('REFUSED', 'مرفوض')], max_length=20, verbose_name='القرار')),
                ('reason', models.TextField(blank=True, verbose_name='المبرر')),
                ('conditions', models.TextField(blank=True, verbose_name='الشروط')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت القرار')),
                ('is_current', models.BooleanField(default=True, verbose_name='القرار الساري')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='port_clearance_decisions', to=settings.AUTH_USER_MODEL, verbose_name='المُقرِّر')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='shipping.portclearancedecision', verbose_name='يحل محل')),
                ('vessel_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_decisions', to='port_health.vesselvisit', verbose_name='زيارة السفينة')),
            ],
            options={
                'verbose_name': 'قرار إفراج صحي بحري',
                'verbose_name_plural': 'قرارات الإفراج الصحي البحري',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['vessel_visit', '-decided_at'], name='pa_clearance_visit')],
            },
        ),
        migrations.AddConstraint(
            model_name='portclearancedecision',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'REFUSED'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='ck_clearance_refused_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='portclearancedecision',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'CONDITIONAL'), _negated=True), models.Q(('conditions', ''), _negated=True), _connector='OR'), name='ck_clearance_conditional_requires_conditions'),
        ),
        migrations.AddConstraint(
            model_name='portclearancedecision',
            constraint=models.CheckConstraint(check=models.Q(('supersedes__isnull', True), models.Q(('supersedes', models.F('vessel_visit')), _negated=True), _connector='OR'), name='ck_clearance_supersedes_same_visit'),
        ),
    ]
