# Generated by Django 5.0.14 on 2026-10-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shippingauditlog_action_portclearancedecision_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portclearancedecision',
            name='ck_clearance_supersedes_same_visit',
        ),
    ]
