# Generated by Django 5.0.14 on 2026-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_remove_portclearancedecision_ck_clearance_supersedes_same_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('STATUS_CHANGE', 'تغيير الحالة'), ('ASSIGN', 'إسناد'), ('REVOKE', 'إلغاء إسناد'), ('LICENSE_RENEW', 'تجديد ترخيص'), ('CLEARANCE_DECISION_RECORDED', 'تسجيل قرار إفراج'), ('DEPARTURE_RECORDED', 'تسجيل مغادرة السفينة')], max_length=32, verbose_name='الفعل'),
        ),
    ]
