# Generated by Django 5.0.14 on 2026-10-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0016_carrierdocument'),
        ('shipping', '0006_alter_shippingauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingauditlog',
            name='company',
            field=models.ForeignKey(blank=True, help_text='شركة الملاحة المرتبطة بالكائن المُدقَّق — وليست شركة الفاعل. مثال: ضابط ميناء يسجّل مغادرة سفينة، فتبقى الشركة هي مالك السفينة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_audit_logs', to='carriers.carrier', verbose_name='شركة الملاحة'),
        ),
    ]
