# Generated by Django 5.0.14 on 2026-07-31 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icd_11_code', models.CharField(max_length=20, unique=True, verbose_name='كود ICD-11')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='الأعراض')),
                ('incubation_period_min', models.IntegerField(blank=True, null=True, verbose_name='فترة الحضانة الدنيا')),
                ('incubation_period_max', models.IntegerField(blank=True, null=True, verbose_name='فترة الحضانة القصوى')),
                ('transmission_methods', models.JSONField(blank=True, default=list, verbose_name='طرق الانتقال')),
                ('is_public_health_emergency', models.BooleanField(default=False, verbose_name='طوارئ صحية عامة')),
                ('ihr_category', models.CharField(choices=[('PHEIC', 'حالة طوارئ صحية عامة'), ('TARGETED_ERADICATION', 'استئصال مستهدف'), ('SURVEILLANCE_ONLY', 'ترصد فقط'), ('NOT_IHR', 'غير مدرج')], default='NOT_IHR', max_length=30, verbose_name='فئة IHR')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مرض',
                'verbose_name_plural': 'الأمراض',
                'ordering': ['icd_11_code'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseCaseDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('SUSPECTED', 'مشتبه'), ('PROBABLE', 'محتمل'), ('CONFIRMED', 'مؤكد'), ('NOT_A_CASE', 'ليس حالة')], max_length=20, verbose_name='نوع الحالة')),
                ('clinical_criteria', models.JSONField(blank=True, default=dict, verbose_name='المعايير السريرية')),
                ('lab_criteria', models.JSONField(blank=True, default=dict, verbose_name='المعايير المخبرية')),
                ('epidemiological_criteria', models.JSONField(blank=True, default=dict, verbose_name='المعايير الوبائية')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_definitions', to='laboratory.disease', verbose_name='المرض')),
            ],
            options={
                'verbose_name': 'تعريف حالة',
                'verbose_name_plural': 'تعاريف الحالات',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_barcode', models.CharField(max_length=50, unique=True, verbose_name='باركود العينة')),
                ('sample_type', models.CharField(choices=[('BLOOD', 'دم'), ('SWAB', 'مسحة'), ('URINE', 'بول')], max_length=30, verbose_name='نوع العينة')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت السحب')),
                ('status', models.CharField(choices=[('REGISTERED', 'مسجلة'), ('PROCESSING', 'قيد التحليل'), ('COMPLETED', 'مكتملة')], default='REGISTERED', max_length=20, verbose_name='الحالة')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_samples', to=settings.AUTH_USER_MODEL, verbose_name='جامع العينة')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='clinic.clinicvisit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'عينة مخبرية',
                'verbose_name_plural': 'العينات المخبرية',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('POSITIVE', 'إيجابي'), ('NEGATIVE', 'سلبي'), ('INCONCLUSIVE', 'غير حاسم')], max_length=20, verbose_name='النتيجة')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='القيمة')),
                ('approval_status', models.CharField(choices=[('PENDING', 'قيد الاعتماد'), ('APPROVED', 'معتمد')], default='PENDING', max_length=20, verbose_name='حالة الاعتماد')),
                ('result_date', models.DateTimeField(auto_now_add=True, verbose_name='وقت النتيجة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_results', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='laboratory.disease', verbose_name='المرض')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_results', to=settings.AUTH_USER_MODEL, verbose_name='المدخل')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labsample', verbose_name='العينة')),
            ],
            options={
                'verbose_name': 'نتيجة مخبرية',
                'verbose_name_plural': 'النتائج المخبرية',
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('severity_level', models.CharField(choices=[('MILD', 'بسيط'), ('MODERATE', 'متوسط'), ('SEVERE', 'شديد'), ('CRITICAL', 'حرج')], max_length=20, verbose_name='المستوى')),
                ('medications', models.JSONField(blank=True, default=list, verbose_name='الأدوية')),
                ('supportive_care', models.JSONField(blank=True, default=list, verbose_name='الرعاية الداعمة')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالأيام')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='laboratory.disease', verbose_name='المرض')),
            ],
            options={
                'verbose_name': 'بروتوكول علاج',
                'verbose_name_plural': 'بروتوكولات العلاج',
                'ordering': ['-version'],
            },
        ),
    ]
