# Generated by Django 5.0.14 on 2026-09-08 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labsection_samplenumbercounter_labsample_entry_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=250, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=250, verbose_name='الاسم بالإنجليزية')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_catalog', to='laboratory.labsection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'فحص متاح',
                'verbose_name_plural': 'الفحوص المتاحة',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
