# Generated by Django 5.0.14 on 2026-09-12 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labtestcatalog'),
        ('organization', '0007_sector_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_equipment', to='organization.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_non_conformities', to='organization.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='qcrecord',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_qc_records', to='organization.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reagents', to='organization.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='samplenumbercounter',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_counters', to='organization.sector', verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='samplenumbercounter',
            name='year',
            field=models.PositiveIntegerField(verbose_name='السنة'),
        ),
        migrations.AlterUniqueTogether(
            name='samplenumbercounter',
            unique_together={('year', 'sector')},
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_laboratories', to=settings.AUTH_USER_MODEL, verbose_name='مدير المعمل')),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to='organization.sector', verbose_name='القطاع')),
            ],
            options={
                'verbose_name': 'معمل قطاعي',
                'verbose_name_plural': 'المعامل القطاعية',
                'ordering': ['code'],
            },
        ),
    ]
